// ZORTON_16C6.c
// Generated by decompiling ZORTON.EXE
// using Reko decompiler version 0.9.2.3.

#include "ZORTON_16C6.h"

// 16C6:0008: Register word16 fn16C6_0008(Register byte ch)
// Called from:
//      main
word16 fn16C6_0008(byte ch)
{
	byte SCZDOP_9 = cond(0x00) | SCZDOP;
	byte ah_15 = SLICE(SCZDOP_9, byte, 8);
	byte bh_32 = SLICE(SCZDOP_9, byte, 8);
	word32 eax_143 = SEQ(eax_16_16, ah_15 & 0x0F & 0xF0, SCZDOP_9);
	if ((ah_15 & 0x0F & 0xF0) != 0xF0)
	{
		word16 cx_50 = SEQ(ch, 0x02);
		eax_143 = SEQ(eax_16_16, (bh_32 | 0xF0) & 0xF0, SCZDOP_9);
		Eq_12896 CDP_65 = SLICE(SCZDOP_9, bool, 5);
		if (((bh_32 | 0xF0) & 0xF0) != 0x00)
		{
			byte SCZDOP_66 = cond(cx_50 + 0x01) | CDP_65;
			word16 cx_176 = cx_50 + 0x01;
			if ((SCZDOP_66 ^ 0x00040000 ^ SCZDOP_66) != 0x00)
			{
				cx_176 = cx_50 + 0x02;
				if ((SCZDOP_66 ^ 0x00200000 ^ SCZDOP_66) != 0x00)
					cx_176 = cx_50 + 0x03;
			}
			eax_143 = SEQ(eax_16_16, (word16) (byte) cx_176);
		}
	}
	return (word16) eax_143;
}

