// ZORTON_0CE0.c
// Generated by decompiling ZORTON.EXE
// using Reko decompiler version 0.9.2.3.

#include "ZORTON_0CE0.h"

// 0CE0:0007: Register word16 fn0CE0_0007(Register Eq_2 ds, Register out (ptr16 Eq_8301) dsOut)
// Called from:
//      fn0CE0_08FC
word16 fn0CE0_0007(Eq_2 ds, struct Eq_8301 & dsOut)
{
	Eq_2 bx_18;
	Eq_2 cx_19;
	Eq_2 dx_20;
	Eq_2 ax_21 = fn0800_3615(ds, SEQ(ds, 1310), 0x8001, 0x2044, out cx_19, out dx_20, out bx_18);
	if (ax_21 == ~0x00)
	{
		word16 dx_298;
		word16 bx_299;
		word16 di_300;
		fn263F_03F3(cx_19, dx_20, bx_18, ds, out dx_298, out bx_299, out di_300, out ds);
	}
	word16 cx_290;
	word16 dx_291;
	word16 bx_292;
	fn0800_06AB(ds, ax_21, 0x04, 0x00, out cx_290, out dx_291, out bx_292);
	word16 cx_293;
	word16 dx_294;
	word16 bx_295;
	word16 dx_296;
	word16 bx_297;
	fn0800_2A93((byte) fn0800_3C87(ds, ax_21, seg28BA->tA0CC, 0xFA00, out cx_293, out dx_294, out bx_295), ds, ax_21, out dx_296, out bx_297);
	Eq_2 ds_129;
	Eq_8347 bp_126 = fn263F_033E(ds, SEQ(ds, 1322), out ds_129);
	Eq_2 sp_133 = <invalid>;
	word16 ax_144 = seg28BA->tA0B8;
	ss->*((word32) sp_133 + 0x0E) = seg28BA->tA0BA;
	ss->*((word32) sp_133 + 0x0C) = ax_144 + 0x02;
	struct Eq_8372 * es_bx_154 = seg28BA->tA0B8;
	ss->*((word32) sp_133 + 0x0A) = (uint16) es_bx_154->b0001 - 0x01;
	(ss->*((word32) sp_133 + 8)).u2 = (uint16) (seg28BA->tA0BA->*(word16) es_bx_154);
	fn2476_043B(ss->*((word32) sp_133 + 8), ss->*((word32) sp_133 + 0x0A), ss->*((word32) sp_133 + 0x0C));
	ss->*((word32) sp_133 + 0x0E) = ss;
	ss->*((word32) sp_133 + 0x0C) = bp_126 - 0x0A;
	ss->*((word32) sp_133 + 0x0A) = ds_129;
	(ss->*((word32) sp_133 + 8)).u0 = 1333;
	ss->*((word32) sp_133 + 6) = 0x28BA;
	ss->*((word32) sp_133 + 4) = ~0x6057;
	ss->*((word32) sp_133 + 2) = ds_129;
	(ss->*sp_133).u0 = 1333;
	Eq_2 ds_202;
	Eq_8347 bp_199 = fn263F_033E(ds_129, ss->*sp_133, out ds_202);
	Eq_2 sp_206 = <invalid>;
	ss->*((word32) sp_206 + 0x0E) = ss;
	ss->*((word32) sp_206 + 0x0C) = bp_199 - 0x0A;
	ss->*((word32) sp_206 + 0x0A) = ds_202;
	ss->*((word32) sp_206 + 8) = 0x0540;
	ss->*((word32) sp_206 + 6) = ds_202;
	ss->*((word32) sp_206 + 4) = 39906;
	ss->*((word32) sp_206 + 2) = ds_202;
	(ss->*sp_206).u0 = 0x0540;
	struct Eq_8301 * ds_236;
	word16 bp_251 = ss->*fn263F_033E(ds_202, ss->*sp_206, out ds_236);
	dsOut = ds_236;
	return bp_251;
}

// 0CE0:014B: void fn0CE0_014B(Register Eq_2 ds)
// Called from:
//      fn0CE0_0170
//      fn0CE0_023E
//      fn0CE0_030C
//      fn0CE0_03D4
void fn0CE0_014B(Eq_2 ds)
{
	Eq_2 dwLoc06_45;
	if ((seg28BA->tA184 & 0x01) != 0x00)
		dwLoc06_45 = SEQ(ds, 0x054C);
	else
		dwLoc06_45 = SEQ(ds, 0x0557);
	fn209F_08D2(ds, dwLoc06_45, 0x00);
}

// 0CE0:0170: Register Eq_2 fn0CE0_0170(Register Eq_2 ds, Stack Eq_8525 ptrArg04, Stack int16 wArg08, Stack Eq_2 dwArg0A)
// Called from:
//      fn0CE0_08FC
Eq_2 fn0CE0_0170(Eq_2 ds, Eq_8525 ptrArg04, int16 wArg08, Eq_2 dwArg0A)
{
	<type-error> Eq_2::* wArg04_142 = (word16) ptrArg04;
	__cli();
	word32 ebx_163;
	word32 edx_162;
	word16 cx_161;
	struct Eq_8535 * es_164;
	fn2425_01E8(ds, out cx_161, out edx_162, out ebx_163, out es_164);
	__sti();
	fn0CE0_014B(ds);
	Eq_2 es_103 = SLICE(ptrArg04, selector, 16);
	struct Eq_8556 Eq_2::* bx_36 = (word16) ptrArg04 + wArg08 *s 0x06;
	word16 dx_39 = (es_103->*bx_36).w0000;
	struct Eq_8565 Eq_2::* si_44 = (char *) wArg04_142 + (wArg08 + ~0x04) *s 0x06;
	(es_103->*si_44).w0002 = (es_103->*bx_36).w0002;
	(es_103->*si_44).w0000 = dx_39;
	struct Eq_8580 Eq_2::* bx_50 = (char *) wArg04_142 + wArg08 *s 0x06;
	(es_103->*bx_50).w0002 = 0x00;
	(es_103->*bx_50).w0000 = 0x00;
	((char *) wArg04_142 + (wArg08 + ~0x04) *s 0x06)[4] = ((char *) wArg04_142 + wArg08 *s 0x06)[4];
	((char *) wArg04_142 + wArg08 *s 0x06)[4] = 0x00;
	cup16 wLoc04_143;
	for (wLoc04_143 = 0x00; wLoc04_143 < 0x03; ++wLoc04_143)
	{
		struct Eq_8617 * es_bx_83 = SEQ(ds, (word16) ptrArg04)[wArg08 + ~0x04].ptr0000;
		es_bx_83->w0006 -= 0x12;
		fn1744_044D(dwArg0A);
		fn16CC_04CA(seg28BA->tA882);
		es_103.u0 = 0x28BA;
	}
	__cli();
	Eq_2 ds_123;
	word16 cx_165;
	word16 dx_166;
	word16 bx_167;
	fn2425_0286(es_103, ds, out cx_165, out dx_166, out bx_167, out ds_123);
	__sti();
	return ds_123;
}

// 0CE0:023E: Register Eq_2 fn0CE0_023E(Register Eq_2 ds, Stack Eq_8667 ptrArg04, Stack int16 wArg08, Stack Eq_2 dwArg0A)
// Called from:
//      fn0CE0_08FC
Eq_2 fn0CE0_023E(Eq_2 ds, Eq_8667 ptrArg04, int16 wArg08, Eq_2 dwArg0A)
{
	<type-error> Eq_2::* wArg04_142 = (word16) ptrArg04;
	__cli();
	word32 ebx_163;
	word32 edx_162;
	word16 cx_161;
	struct Eq_8677 * es_164;
	fn2425_01E8(ds, out cx_161, out edx_162, out ebx_163, out es_164);
	__sti();
	fn0CE0_014B(ds);
	Eq_2 es_103 = SLICE(ptrArg04, selector, 16);
	struct Eq_8690 Eq_2::* bx_36 = (word16) ptrArg04 + wArg08 *s 0x06;
	word16 dx_39 = (es_103->*bx_36).w0000;
	struct Eq_8699 Eq_2::* si_44 = (char *) wArg04_142 + (wArg08 + 0x05) *s 0x06;
	(es_103->*si_44).w0002 = (es_103->*bx_36).w0002;
	(es_103->*si_44).w0000 = dx_39;
	struct Eq_8714 Eq_2::* bx_50 = (char *) wArg04_142 + wArg08 *s 0x06;
	(es_103->*bx_50).w0002 = 0x00;
	(es_103->*bx_50).w0000 = 0x00;
	((char *) wArg04_142 + (wArg08 + 0x05) *s 0x06)[4] = ((char *) wArg04_142 + wArg08 *s 0x06)[4];
	((char *) wArg04_142 + wArg08 *s 0x06)[4] = 0x00;
	cup16 wLoc04_143;
	for (wLoc04_143 = 0x00; wLoc04_143 < 0x03; ++wLoc04_143)
	{
		struct Eq_8751 * es_bx_83 = SEQ(ds, (word16) ptrArg04)[wArg08 + 0x05].ptr0000;
		es_bx_83->w0006 += 0x12;
		fn1744_044D(dwArg0A);
		fn16CC_04CA(seg28BA->tA882);
		es_103.u0 = 0x28BA;
	}
	__cli();
	Eq_2 ds_123;
	word16 cx_165;
	word16 dx_166;
	word16 bx_167;
	fn2425_0286(es_103, ds, out cx_165, out dx_166, out bx_167, out ds_123);
	__sti();
	return ds_123;
}

// 0CE0:030C: Register Eq_2 fn0CE0_030C(Register Eq_2 ds, Stack Eq_8790 ptrArg04, Stack int16 wArg08, Stack Eq_2 dwArg0A)
// Called from:
//      fn0CE0_08FC
Eq_2 fn0CE0_030C(Eq_2 ds, Eq_8790 ptrArg04, int16 wArg08, Eq_2 dwArg0A)
{
	<type-error> Eq_2::* wArg04_142 = (word16) ptrArg04;
	__cli();
	word32 ebx_163;
	word32 edx_162;
	word16 cx_161;
	struct Eq_8800 * es_164;
	fn2425_01E8(ds, out cx_161, out edx_162, out ebx_163, out es_164);
	__sti();
	fn0CE0_014B(ds);
	Eq_2 es_103 = SLICE(ptrArg04, selector, 16);
	struct Eq_8813 Eq_2::* bx_36 = (word16) ptrArg04 + wArg08 *s 0x06;
	word16 dx_39 = (es_103->*bx_36).w0000;
	struct Eq_8822 Eq_2::* si_44 = (char *) wArg04_142 + (wArg08 - 0x01) *s 0x06;
	(es_103->*si_44).w0002 = (es_103->*bx_36).w0002;
	(es_103->*si_44).w0000 = dx_39;
	struct Eq_8837 Eq_2::* bx_50 = (char *) wArg04_142 + wArg08 *s 0x06;
	(es_103->*bx_50).w0002 = 0x00;
	(es_103->*bx_50).w0000 = 0x00;
	((char *) wArg04_142 + (wArg08 - 0x01) *s 0x06)[4] = ((char *) wArg04_142 + wArg08 *s 0x06)[4];
	((char *) wArg04_142 + wArg08 *s 0x06)[4] = 0x00;
	cup16 wLoc04_143;
	for (wLoc04_143 = 0x00; wLoc04_143 < 0x05; ++wLoc04_143)
	{
		struct Eq_8874 * es_bx_83 = SEQ(ds, (word16) ptrArg04)[wArg08 - 0x01].ptr0000;
		es_bx_83->w0004 -= 0x0E;
		fn1744_044D(dwArg0A);
		fn16CC_04CA(seg28BA->tA882);
		es_103.u0 = 0x28BA;
	}
	__cli();
	Eq_2 ds_123;
	word16 cx_165;
	word16 dx_166;
	word16 bx_167;
	fn2425_0286(es_103, ds, out cx_165, out dx_166, out bx_167, out ds_123);
	__sti();
	return ds_123;
}

// 0CE0:03D4: Register Eq_2 fn0CE0_03D4(Register Eq_2 ds, Stack Eq_8913 ptrArg04, Stack int16 wArg08, Stack Eq_2 dwArg0A)
// Called from:
//      fn0CE0_08FC
Eq_2 fn0CE0_03D4(Eq_2 ds, Eq_8913 ptrArg04, int16 wArg08, Eq_2 dwArg0A)
{
	<type-error> Eq_2::* wArg04_142 = (word16) ptrArg04;
	__cli();
	word32 ebx_163;
	word32 edx_162;
	word16 cx_161;
	struct Eq_8923 * es_164;
	fn2425_01E8(ds, out cx_161, out edx_162, out ebx_163, out es_164);
	__sti();
	fn0CE0_014B(ds);
	Eq_2 es_103 = SLICE(ptrArg04, selector, 16);
	struct Eq_8936 Eq_2::* bx_36 = (word16) ptrArg04 + wArg08 *s 0x06;
	word16 dx_39 = (es_103->*bx_36).w0000;
	struct Eq_8945 Eq_2::* si_44 = (char *) wArg04_142 + (wArg08 + 0x01) *s 0x06;
	(es_103->*si_44).w0002 = (es_103->*bx_36).w0002;
	(es_103->*si_44).w0000 = dx_39;
	struct Eq_8960 Eq_2::* bx_50 = (char *) wArg04_142 + wArg08 *s 0x06;
	(es_103->*bx_50).w0002 = 0x00;
	(es_103->*bx_50).w0000 = 0x00;
	((char *) wArg04_142 + (wArg08 + 0x01) *s 0x06)[4] = ((char *) wArg04_142 + wArg08 *s 0x06)[4];
	((char *) wArg04_142 + wArg08 *s 0x06)[4] = 0x00;
	cup16 wLoc04_143;
	for (wLoc04_143 = 0x00; wLoc04_143 < 0x05; ++wLoc04_143)
	{
		struct Eq_8997 * es_bx_83 = SEQ(ds, (word16) ptrArg04)[wArg08 + 0x01].ptr0000;
		es_bx_83->w0004 += 0x0E;
		fn1744_044D(dwArg0A);
		fn16CC_04CA(seg28BA->tA882);
		es_103.u0 = 0x28BA;
	}
	__cli();
	Eq_2 ds_123;
	word16 cx_165;
	word16 dx_166;
	word16 bx_167;
	fn2425_0286(es_103, ds, out cx_165, out dx_166, out bx_167, out ds_123);
	__sti();
	return ds_123;
}

// 0CE0:0547: Register word16 fn0CE0_0547()
// Called from:
//      fn0CE0_08FC
word16 fn0CE0_0547()
{
	word16 wLoc06_107 = 0x00;
	do
		;
	while ((__inb(0x03DA) & 0x08) == 0x00);
	ci16 wLoc04_108 = 0x01;
	while (true)
	{
		Eq_947 bLoc04_112 = (byte) wLoc04_108;
		if (wLoc04_108 >= 0xC1)
			break;
		__outb(0x03C7, bLoc04_112);
		uint16 ax_33 = (uint16) __inb(969);
		uint16 ax_38 = (uint16) __inb(969);
		uint16 ax_43 = (uint16) __inb(969);
		Eq_947 bLoc08_130 = (byte) (ax_33 & 0x3F);
		Eq_947 bLoc0A_134 = (byte) (ax_38 & 0x3F);
		Eq_947 bLoc0C_137 = (byte) (ax_43 & 0x3F);
		if ((ax_33 & 0x3F) != 0x00)
		{
			wLoc06_107 = 0x01;
			bLoc08_130 = (byte) (int16) ((int32) ((ax_33 & 0x3F) *s 0x62) / 100);
		}
		if ((ax_38 & 0x3F) != 0x00)
		{
			wLoc06_107 = 0x01;
			bLoc0A_134 = (byte) (int16) ((int32) ((ax_38 & 0x3F) *s 0x62) / 100);
		}
		if ((ax_43 & 0x3F) != 0x00)
		{
			wLoc06_107 = 0x01;
			bLoc0C_137 = (byte) (int16) ((int32) ((ax_43 & 0x3F) *s 0x62) / 100);
		}
		__outb(0x03C8, bLoc04_112);
		__outb(969, bLoc08_130);
		__outb(969, bLoc0A_134);
		__outb(969, bLoc0C_137);
		++wLoc04_108;
	}
	return wLoc06_107;
}

// 0CE0:05FB: Register word16 fn0CE0_05FB(Register Eq_2 ds, Register out Eq_9138 bpOut, Register out Eq_2 dsOut)
// Called from:
//      fn0CE0_08FC
word16 fn0CE0_05FB(Eq_2 ds, union Eq_9138 & bpOut, union Eq_2 & dsOut)
{
	struct Eq_9140 Eq_9174::* bp_101 = fp - 2;
	if (*((word32) ds + 0x050D) == 0x00)
	{
		*((word32) ds + 0x00009BEE) = 0x00;
		Eq_2 bx_18;
		Eq_2 cx_19;
		Eq_2 dx_21;
		Eq_2 ax_16 = fn0800_1D38(ds, 0x0243, 0x00, out cx_19, out dx_21, out bx_18, out bp_101, out ds);
		*((word32) ds + 0x050F) = dx_21;
		*((word32) ds + 0x050D) = ax_16;
		if (*((word32) ds + 0x050D) == 0x00)
		{
			word16 dx_596;
			word16 bx_597;
			fn263F_043F(cx_19, dx_21, bx_18, ds, SEQ(ds, 0x0562), out dx_596, out bx_597, out ds);
		}
		(ss->*bp_101).tFFFFFFFE.u0 = 0x00;
		while ((ss->*bp_101).tFFFFFFFE < 0xC1)
		{
			__outb(0x03C7, (ss->*bp_101).tFFFFFFFE);
			(ss->*bp_101).tFFFFFFFA.u2 = (uint16) __inb(969);
			(ss->*bp_101).tFFFFFFF8.u2 = (uint16) __inb(969);
			(ss->*bp_101).tFFFFFFF6.u2 = (uint16) __inb(969);
			Eq_2 es_bx_80 = *((word32) ds + 0x050D);
			struct Eq_9394 * es_84 = SLICE(es_bx_80, selector, 16);
			*((char *) &(es_84->*(word16) es_bx_80).t0000 + (ss->*bp_101).tFFFFFFFE * 0x03) = (union Eq_947 *) (ss->*bp_101).tFFFFFFFA;
			Mem90[es_84:Mem85[ss:bp_101 + -2:word16] *s 0x03 + Mem85[ds:0x050D:word16] + 0x01:byte] = Mem85[ss:bp_101 + -8:byte];
			Mem96[es_84:Mem90[ss:bp_101 + -2:word16] *s 0x03 + Mem90[ds:0x050D:word16] + 0x02:byte] = Mem90[ss:bp_101 + -0x0A:byte];
			(ss->*bp_101).tFFFFFFFE = (word16) (ss->*bp_101).tFFFFFFFE + 1;
		}
	}
	(ss->*bp_101).wFFFFFFFC = 0x00;
	do
		;
	while ((__inb(0x03DA) & 0x08) == 0x00);
	(ss->*bp_101).tFFFFFFFE.u0 = 0x01;
	while ((ss->*bp_101).tFFFFFFFE < 0xC1)
	{
		Eq_947 dx_215;
		__outb(0x03C7, (ss->*bp_101).tFFFFFFFE);
		(ss->*bp_101).tFFFFFFFA.u2 = (uint16) __inb(969);
		(ss->*bp_101).tFFFFFFF8.u2 = (uint16) __inb(969);
		(ss->*bp_101).tFFFFFFF6.u2 = (uint16) __inb(969);
		Eq_2 es_bx_134 = *((word32) ds + 0x050D);
		struct Eq_9257 * es_137 = SLICE(es_bx_134, selector, 16);
		(ss->*bp_101).wFFFFFFEE = (uint16) *((char *) &&(es_137->*(es_137->*(word16) es_bx_134).b0000) + (ss->*bp_101).tFFFFFFFE * 0x03);
		Mem148[ss:bp_101 + -20:word16] = CONVERT(Mem141[es_137:Mem141[ss:bp_101 + -2:word16] *s 0x03 + Mem141[ds:0x050D:word16] + 0x01:byte], byte, uint16);
		Mem155[ss:bp_101 + -22:word16] = CONVERT(Mem148[es_137:Mem148[ss:bp_101 + -2:word16] *s 0x03 + Mem148[ds:0x050D:word16] + 0x02:byte], byte, uint16);
		(ss->*bp_101).tFFFFFFF4 = (uint16) ((word16) ((ss->*bp_101).tFFFFFFFE *s 0x03) + seg28BA->tA0B8 + -1) & 0x3F;
		Eq_9320 es_bx_173 = seg28BA->tA0B8;
		(ss->*bp_101).tFFFFFFF2 = (uint16) *((char *) &&(SLICE(es_bx_173, selector, 16)->*(SLICE(es_bx_173, selector, 16)->*(word16) es_bx_173).b0000) + (ss->*bp_101).tFFFFFFFE * 0x03) & 0x3F;
		(ss->*bp_101).tFFFFFFF0 = (uint16) ((word16) ((ss->*bp_101).tFFFFFFFE *s 0x03) + seg28BA->tA0B8 + 0x01) & 0x3F;
		if ((ss->*bp_101).tFFFFFFFA > (ss->*bp_101).tFFFFFFF4)
		{
			(ss->*bp_101).wFFFFFFFC = 0x01;
			int32 eax_229 = (int32) ((int64) ((int32) *((word32) ds + 0x00009BEE) *s (int32) ((ss->*bp_101).wFFFFFFEE - (ss->*bp_101).tFFFFFFF4)) / 0x32);
			dx_215 = (ss->*bp_101).wFFFFFFEE - (word16) eax_229;
			goto l0CE0_07D3;
		}
		if ((ss->*bp_101).tFFFFFFFA < (ss->*bp_101).tFFFFFFF4)
		{
			(ss->*bp_101).wFFFFFFFC = 0x01;
			int32 eax_212 = (int32) ((int64) ((int32) *((word32) ds + 0x00009BEE) *s (int32) ((ss->*bp_101).tFFFFFFF4 - (ss->*bp_101).wFFFFFFEE)) / 0x32);
			dx_215 = (ss->*bp_101).wFFFFFFEE + (word16) eax_212;
l0CE0_07D3:
			(ss->*bp_101).tFFFFFFFA = dx_215;
		}
		Eq_947 dx_264;
		if ((ss->*bp_101).tFFFFFFF8 > (ss->*bp_101).tFFFFFFF2)
		{
			(ss->*bp_101).wFFFFFFFC = 0x01;
			int32 eax_278 = (int32) ((int64) ((int32) *((word32) ds + 0x00009BEE) *s (int32) ((ss->*bp_101).wFFFFFFEC - (ss->*bp_101).tFFFFFFF2)) / 0x32);
			dx_264 = (ss->*bp_101).wFFFFFFEC - (word16) eax_278;
			goto l0CE0_083A;
		}
		if ((ss->*bp_101).tFFFFFFF8 < (ss->*bp_101).tFFFFFFF2)
		{
			(ss->*bp_101).wFFFFFFFC = 0x01;
			int32 eax_261 = (int32) ((int64) ((int32) *((word32) ds + 0x00009BEE) *s (int32) ((ss->*bp_101).tFFFFFFF2 - (ss->*bp_101).wFFFFFFEC)) / 0x32);
			dx_264 = (ss->*bp_101).wFFFFFFEC + (word16) eax_261;
l0CE0_083A:
			(ss->*bp_101).tFFFFFFF8 = dx_264;
		}
		Eq_947 dx_313;
		if ((ss->*bp_101).tFFFFFFF6 > (ss->*bp_101).tFFFFFFF0)
		{
			(ss->*bp_101).wFFFFFFFC = 0x01;
			int32 eax_327 = (int32) ((int64) ((int32) *((word32) ds + 0x00009BEE) *s (int32) ((ss->*bp_101).wFFFFFFEA - (ss->*bp_101).tFFFFFFF0)) / 0x32);
			dx_313 = (ss->*bp_101).wFFFFFFEA - (word16) eax_327;
			goto l0CE0_08A1;
		}
		if ((ss->*bp_101).tFFFFFFF6 < (ss->*bp_101).tFFFFFFF0)
		{
			(ss->*bp_101).wFFFFFFFC = 0x01;
			int32 eax_310 = (int32) ((int64) ((int32) *((word32) ds + 0x00009BEE) *s (int32) ((ss->*bp_101).tFFFFFFF0 - (ss->*bp_101).wFFFFFFEA)) / 0x32);
			dx_313 = (ss->*bp_101).wFFFFFFEA + (word16) eax_310;
l0CE0_08A1:
			(ss->*bp_101).tFFFFFFF6 = dx_313;
		}
		__outb(0x03C8, (ss->*bp_101).tFFFFFFFE);
		__outb(969, (ss->*bp_101).tFFFFFFFA);
		__outb(969, (ss->*bp_101).tFFFFFFF8);
		Eq_947 al_344 = (ss->*bp_101).tFFFFFFF6;
		__outb(969, al_344);
		if (fn0800_2390(al_344, ds) != 0x00)
		{
			fn0800_20A6(ds);
			break;
		}
		(ss->*bp_101).tFFFFFFFE = (word16) (ss->*bp_101).tFFFFFFFE + 1;
	}
	if ((ss->*bp_101).wFFFFFFFC == 0x00)
	{
		word16 cx_598;
		word16 dx_599;
		word16 bx_600;
		fn0800_1C24(ds, *((word32) ds + 0x050F), out cx_598, out dx_599, out bx_600, out ds);
		((word32) ds + 0x050D)->u0 = 0x00;
	}
	++*((word32) ds + 0x00009BEE);
	bpOut = (ss->*bp_101).t0000;
	dsOut = ds;
	return (ss->*bp_101).wFFFFFFFC;
}

// 0CE0:08FC: Register word32 fn0CE0_08FC(Register Eq_2 ds, Register out Eq_9713 ebxOut, Register out Eq_9714 bpOut, Register out Eq_2 esOut, Register out Eq_2 dsOut)
// Called from:
//      fn1F0F_000F
//      fn226D_00F9
word32 fn0CE0_08FC(Eq_2 ds, union Eq_9713 & ebxOut, union Eq_9714 & bpOut, union Eq_2 & esOut, union Eq_2 & dsOut)
{
	fn0800_03F4(0x0D, SEQ(ds, 0x0511), SEQ(ss, fp - 244));
	struct Eq_9728 Eq_2::* bp_1431 = fp - 2;
	Eq_2 es_1754 = 0x2862;
	if ((seg2862->t0000 & 0x01) == 0x00)
	{
		__cli();
		word32 edx_2022;
		word16 cx_2021;
		struct Eq_9742 * es_2024;
		word32 ebx_2023;
		fn2425_01E8(ds, out cx_2021, out edx_2022, out ebx_2023, out es_2024);
		__sti();
		do
		{
			Eq_2 edx_47 = <invalid>;
			word32 ebx_2026;
			word16 dx_2025;
		} while (((word16) (uint32) fn2331_0167(ds, out dx_2025, out ebx_2026) | (word16) edx_47) != 0x00);
		seg28BA->t302C = 0x00;
		seg2862->t0000 = seg2862->t0000 | 0x20;
		seg28BA->tA0CC = seg28BA->tA882;
		Eq_2 cx_89;
		Eq_2 dx_91;
		word16 bp_2028;
		word16 bx_2027;
		Eq_2 ds_122;
		Eq_2 ax_86 = fn0800_1D38(ds, 16000, 0x00, out cx_89, out dx_91, out bx_2027, out bp_2028, out ds_122);
		seg28BA->tA0E6 = dx_91;
		seg28BA->tA0E4 = ax_86;
		if ((ax_86 | dx_91) == 0x00)
		{
			word16 bx_2030;
			word16 dx_2029;
			fn263F_043F(cx_89, dx_91, 0x28BA, ds_122, SEQ(ds_122, 0x0576), out dx_2029, out bx_2030, out ds_122);
		}
		Eq_2 ds_150;
		struct Eq_9810 Eq_2::* bp_146 = fn0CE0_0007(fn2476_0282(ds_122), out ds_150);
		(ss->*bp_146).tFFFFFF1C = *((word32) ds_150 + 39906);
		word16 ax_164 = *((word32) ds_150 + 39908);
		Eq_2 dx_165 = *((word32) ds_150 + 39906);
		(ss->*bp_146).wFFFFFFFA = ax_164;
		(ss->*bp_146).wFFFFFFF8 = (word16) ((word32) dx_165 + 0x0EC8);
		(ss->*bp_146).wFFFFFFF6 = ax_164;
		(ss->*bp_146).tFFFFFFF4.u1 = (word32) dx_165 + 7568;
		(ss->*bp_146).tFFFFFF20 = (ss->*bp_146).tFFFFFFF4;
		(ss->*bp_146).wFFFFFFF2 = (ss->*bp_146).wFFFFFFF6;
		(ss->*bp_146).tFFFFFFF0.u1 = (word32) dx_165 + 11352;
		(ss->*bp_146).tFFFFFF24 = (ss->*bp_146).tFFFFFFF0;
		(ss->*bp_146).wFFFFFFEE = (ss->*bp_146).wFFFFFFF2;
		(ss->*bp_146).tFFFFFFEC.u1 = (word32) dx_165 + 15136;
		(ss->*bp_146).tFFFFFF28 = (ss->*bp_146).tFFFFFFEC;
		(ss->*bp_146).wFFFFFFEA = (ss->*bp_146).wFFFFFFEE;
		(ss->*bp_146).tFFFFFFE8.u1 = (word32) dx_165 + 0x000049E8;
		(ss->*bp_146).tFFFFFF2C = (ss->*bp_146).tFFFFFFE8;
		(ss->*bp_146).wFFFFFFE6 = (ss->*bp_146).wFFFFFFEA;
		(ss->*bp_146).tFFFFFFE4.u1 = (word32) dx_165 + 22704;
		(ss->*bp_146).tFFFFFF30 = (ss->*bp_146).tFFFFFFE4;
		(ss->*bp_146).wFFFFFFE2 = (ss->*bp_146).wFFFFFFE6;
		(ss->*bp_146).tFFFFFFE0.u1 = (word32) dx_165 + 0x00006778;
		(ss->*bp_146).tFFFFFF34 = (ss->*bp_146).tFFFFFFE0;
		(ss->*bp_146).wFFFFFFDE = (ss->*bp_146).wFFFFFFE2;
		(ss->*bp_146).tFFFFFFDC.u1 = (word32) dx_165 + 30272;
		(ss->*bp_146).tFFFFFF38 = (ss->*bp_146).tFFFFFFDC;
		seg28BA->tA147 = 0x00;
		seg28BA->t9FE3 = 0x00;
		seg28BA->t2F1E = 0x00;
		Eq_2 sp_155 = <invalid>;
		ss->*((word32) sp_155 - 4) = seg28BA->tA882;
		word16 dx_232;
		Eq_2 ds_1077;
		Eq_2 ax_244 = (word16) (uint32) fn1744_000A(ds_150, out dx_232, out bp_1431, out ds_1077);
		(ss->*bp_1431).wFFFFFFFE = dx_232;
		(ss->*bp_1431).tFFFFFFFC = ax_244;
		(ss->*bp_1431).tFFFFFFDA.u0 = 0x00;
		Eq_2 sp_236 = <invalid>;
		struct Eq_9995 Eq_2::* sp_1757 = (word32) sp_236 + 4;
		while ((ss->*bp_1431).tFFFFFFDA < 0x19)
		{
			Eq_10012 bx_255 = bp_1431 - 0xC4 + (ss->*bp_1431).tFFFFFFDA;
			ss->*((word16) bx_255 + 2) = ~0x00;
			ss->*bx_255 = ~0x00;
			SEQ(ss, bp_1431 - 0xC0)[(ss->*bp_1431).tFFFFFFDA] = 0x00;
			(ss->*bp_1431).tFFFFFFDA = (word16) (ss->*bp_1431).tFFFFFFDA + 1;
		}
		(ss->*bp_1431).tFFFFFFDA.u0 = 0x00;
		while (seg28BA->tA18C > (ss->*bp_1431).tFFFFFFDA)
		{
			struct Eq_10065 Eq_2::* sp_1758 = sp_1757 - 4;
			(ss->*sp_1758).dw0000 = 0x00360047;
			(ss->*sp_1758).dwFFFFFFFC = 0x00240001;
			(ss->*sp_1758).dwFFFFFFF8 = 0x00;
			Mem1770[ss:sp_1758 + -0x0A:word16] = SEQ(0x28BA, 0x3057)[Mem1763[ss:bp_1431 + -38:word16] * 0x08];
			Mem1778[ss:sp_1758 + -0x0C:word16] = SEQ(0x28BA, 0x3055)[Mem1770[ss:bp_1431 + -38:word16] * 0x08];
			word16 dx_1784;
			word16 ax_1804 = (word16) (uint32) fn1744_0972(ds_1077, out dx_1784, out bp_1431, out ds_1077);
			word16 bx_1802 = SEQ(0x28BA, 0x3053)[Mem1778[ss:bp_1431 + -38:word16] * 0x08] *s 0x06 + (bp_1431 - 0xC4);
			ss->*((word16) bx_1802 + 2) = dx_1784;
			ss->*bx_1802 = ax_1804;
			word16 bx_1813 = (SEQ(0x28BA, 0x3059)[Mem1805[ss:bp_1431 + -38:word16] * 0x08] << 0x02) + (bp_1431 - 228);
			Eq_10150 dx_1815 = ss->*bx_1813;
			ptr32 es_bx_1824 = SEQ(ds_1077, bp_1431 - 0xC4)[SEQ(0x28BA, 0x3053)[Mem1805[ss:bp_1431 + -38:word16] * 0x08] * 0x06];
			*((word32) es_bx_1824 + 16) = ss->*((word16) bx_1813 + 2);
			*((word32) es_bx_1824 + 0x0E) = dx_1815;
			SEQ(ss, bp_1431 - 0xC0)[SEQ(0x28BA, 0x3053)[Mem1828[ss:bp_1431 + -38:word16] * 0x08] * 0x06] = SEQ(0x28BA, 0x3059)[Mem1828[ss:bp_1431 + -38:word16] * 0x08] + 0x01;
			(ss->*bp_1431).tFFFFFFDA = (word16) (ss->*bp_1431).tFFFFFFDA + 1;
			Eq_2 sp_1787 = <invalid>;
			sp_1757 = (struct Eq_9995 Eq_2::*) ((word32) sp_1787 + 16);
		}
		(ss->*bp_1431).dwFFFFFF66 = 0x00;
		(ss->*bp_1431).tFFFFFFDA.u0 = 0x00;
		while (true)
		{
			struct Eq_9995 Eq_2::* sp_1399 = sp_1757;
			if ((ss->*bp_1431).tFFFFFFDA >= 0x19)
				break;
			Eq_10219 bx_286 = bp_1431 - 0xC4 + (ss->*bp_1431).tFFFFFFDA *s 0x06;
			if ((ss->*bx_286 | ss->*((word16) bx_286 + 2)) != 0x00)
			{
				Eq_10352 bx_295 = bp_1431 - 0xC4 + (ss->*bp_1431).tFFFFFFDA *s 0x06;
				if (ss->*((word16) bx_295 + 2) != ~0x00 || ss->*bx_295 != ~0x00)
				{
					struct Eq_10366 Eq_2::* sp_306 = sp_1757 - 4;
					(ss->*sp_306).t0000 = (ss->*bp_1431).tFFFFFFFC;
					(ss->*sp_306).tFFFFFFFC = SEQ(ss, bp_1431 - 0xC4)[(ss->*bp_1431).tFFFFFFDA];
					fn1744_005B((ss->*sp_306).tFFFFFFFC, (ss->*sp_306).t0000);
				}
			}
			(ss->*bp_1431).tFFFFFFDA = (word16) (ss->*bp_1431).tFFFFFFDA + 1;
		}
		do
		{
			__cli();
			word16 cx_2031;
			struct Eq_10240 * es_2034;
			word32 ebx_2033;
			word32 edx_2032;
			fn2425_01E8(ds_1077, out cx_2031, out edx_2032, out ebx_2033, out es_2034);
			__sti();
			seg28BA->t302E = ds_1077;
			seg28BA->t302C = 1162;
			struct Eq_10256 Eq_2::* sp_351 = sp_1399 - 4;
			(ss->*sp_351).t0000 = seg28BA->tA882;
			fn16CC_0481((ss->*sp_351).t0000);
			(ss->*sp_351).t0000 = seg28BA->tA0CC;
			(ss->*sp_351).tFFFFFFFC = seg28BA->tA0E4;
			fn18D5_11FB((ss->*sp_351).tFFFFFFFC, (ss->*sp_351).t0000, (ss->*sp_351).t0002);
			(ss->*sp_351).t0000 = (ss->*bp_1431).tFFFFFFFC;
			fn1744_044D((ss->*sp_351).t0000);
			(ss->*sp_351).t0000 = seg28BA->tA882;
			fn1312_1037((ss->*sp_351).t0000);
			__cli();
			word16 bx_2037;
			word16 dx_2036;
			word16 cx_2035;
			fn2425_0286(0x28BA, ds_1077, out cx_2035, out dx_2036, out bx_2037, out ds_1077);
			__sti();
			Eq_2 sp_1340 = (char *) &sp_351->t0002 + 2;
			do
			{
				struct Eq_9728 Eq_2::* bp_1153;
				if ((ss->*bp_1431).w0006 != 0x00 && seg28BA->t2F1F != 0x00)
				{
					Eq_10543 bx_436 = bp_1431 - 0xC4 + (seg28BA->t2F1F *s 0x06) / 8;
					if ((ss->*bx_436 | ss->*((word16) bx_436 + 2)) != 0x00)
					{
						Eq_10662 bx_447 = bp_1431 - 0xC4 + (seg28BA->t2F1F *s 0x06) / 8;
						if (ss->*((word16) bx_447 + 2) == ~0x00 && ss->*bx_447 == ~0x00)
							goto l0CE0_0DC1;
						Eq_10763 bx_460 = bp_1431 - 0xC4 + ((seg28BA->t2F1F - 0x05) *s 0x06) / 8;
						if ((ss->*bx_460 | ss->*((word16) bx_460 + 2)) == 0x00)
						{
							struct Eq_10816 Eq_2::* sp_586 = sp_1340 - 4;
							(ss->*sp_586).t0000 = (ss->*bp_1431).tFFFFFFFC;
							(ss->*sp_586).wFFFFFFFE = seg28BA->t2F1F;
							(ss->*sp_586).tFFFFFFFC = ss;
							(ss->*sp_586).tFFFFFFFA = bp_1431 - 0xC4;
							ds_1077 = fn0CE0_0170(ds_1077, (ss->*sp_586).tFFFFFFFA, (ss->*sp_586).wFFFFFFFE, (ss->*sp_586).t0000);
							goto l0CE0_0DBE;
						}
						Eq_10797 bx_473 = bp_1431 - 0xC4 + ((seg28BA->t2F1F - 0x01) *s 0x06) / 8;
						if ((ss->*bx_473 | ss->*((word16) bx_473 + 2)) == 0x00)
						{
							struct Eq_10934 Eq_2::* sp_560 = sp_1340 - 4;
							(ss->*sp_560).t0000 = (ss->*bp_1431).tFFFFFFFC;
							(ss->*sp_560).wFFFFFFFE = seg28BA->t2F1F;
							(ss->*sp_560).tFFFFFFFC = ss;
							(ss->*sp_560).tFFFFFFFA = bp_1431 - 0xC4;
							ds_1077 = fn0CE0_030C(ds_1077, (ss->*sp_560).tFFFFFFFA, (ss->*sp_560).wFFFFFFFE, (ss->*sp_560).t0000);
							goto l0CE0_0DBE;
						}
						Eq_10915 bx_485 = bp_1431 - 0xC4 + ((seg28BA->t2F1F + 0x01) *s 0x06) / 8;
						if ((ss->*bx_485 | ss->*((word16) bx_485 + 2)) == 0x00)
						{
							struct Eq_11048 Eq_2::* sp_534 = sp_1340 - 4;
							(ss->*sp_534).t0000 = (ss->*bp_1431).tFFFFFFFC;
							(ss->*sp_534).wFFFFFFFE = seg28BA->t2F1F;
							(ss->*sp_534).tFFFFFFFC = ss;
							(ss->*sp_534).tFFFFFFFA = bp_1431 - 0xC4;
							ds_1077 = fn0CE0_03D4(ds_1077, (ss->*sp_534).tFFFFFFFA, (ss->*sp_534).wFFFFFFFE, (ss->*sp_534).t0000);
							goto l0CE0_0DBE;
						}
						Eq_11029 bx_497 = bp_1431 - 0xC4 + ((seg28BA->t2F1F + 0x05) *s 0x06) / 8;
						if ((ss->*bx_497 | ss->*((word16) bx_497 + 2)) == 0x00)
						{
							struct Eq_11107 Eq_2::* sp_506 = sp_1340 - 4;
							(ss->*sp_506).t0000 = (ss->*bp_1431).tFFFFFFFC;
							(ss->*sp_506).wFFFFFFFE = seg28BA->t2F1F;
							(ss->*sp_506).tFFFFFFFC = ss;
							(ss->*sp_506).tFFFFFFFA = bp_1431 - 0xC4;
							ds_1077 = fn0CE0_023E(ds_1077, (ss->*sp_506).tFFFFFFFA, (ss->*sp_506).wFFFFFFFE, (ss->*sp_506).t0000);
l0CE0_0DBE:
						}
					}
l0CE0_0DC1:
					seg28BA->t2F1F = 0x00;
					if ((ss->*bp_1431).wFFFFFF64 == 0x01 && ((ss->*bp_1431).wFFFFFF6A == 0x00 && ((ss->*bp_1431).wFFFFFF70 == 0x02 && ((ss->*bp_1431).wFFFFFF82 == 0x03 && ((ss->*bp_1431).wFFFFFF88 == 0x04 && ((ss->*bp_1431).wFFFFFF8E == 0x05 && ((ss->*bp_1431).wFFFFFFA0 == 0x06 && ((ss->*bp_1431).wFFFFFFA6 == 0x07 && (ss->*bp_1431).wFFFFFFAC == 0x08))))))))
					{
						seg28BA->t9FE3 = 0x01;
						__cli();
						word32 ebx_647;
						word16 cx_2066;
						word32 edx_2067;
						struct Eq_11168 * es_2068;
						fn2425_01E8(ds_1077, out cx_2066, out edx_2067, out ebx_647, out es_2068);
						__sti();
						(ss->*bp_1431).wFFFFFFD2 = seg28BA->tA18A;
						struct Eq_11182 Eq_2::* sp_658 = sp_1340 - 2;
						(ss->*sp_658).t0000.u0 = 0x8001;
						(ss->*sp_658).tFFFFFFFE = ss;
						(ss->*sp_658).tFFFFFFFC = bp_1431 - 242;
						word16 cx_2069;
						word16 dx_2070;
						word16 bx_2071;
						seg28BA->tA18A = fn0800_3615(ds_1077, (ss->*sp_658).tFFFFFFFC, (ss->*sp_658).t0000, (ss->*sp_658).t0002, out cx_2069, out dx_2070, out bx_2071);
						seg28BA->tA184 = 0x00;
						(ss->*sp_658).tFFFFFFFE = seg28BA->tAA80;
						(ss->*sp_658).tFFFFFFFA = (ss->*bp_1431).tFFFFFFF8;
						(ss->*sp_658).tFFFFFFF6.u3 = 0x0013007D;
						word16 bx_692;
						byte al_2072;
						fn216E_01DC((ss->*sp_658).tFFFFFFF6, (ss->*sp_658).tFFFFFFF8, (ss->*sp_658).tFFFFFFFA, (ss->*sp_658).tFFFFFFFC, (ss->*sp_658).tFFFFFFFE, (ss->*sp_658).t0000, out al_2072, out bx_692);
						word32 ebx_714 = SEQ(SLICE(ebx_647, word16, 16), bx_692);
						do
							;
						while (seg28BA->tA422 == 0x01);
						(ss->*sp_658).t0000 = ds_1077;
						(ss->*sp_658).tFFFFFFFE.u0 = 0x04AA;
						Eq_2 ds_717 = fn1D10_0E66(ebx_714, ds_1077, (ss->*sp_658).tFFFFFFFE);
						(ss->*sp_658).t0000 = ds_717;
						(ss->*sp_658).tFFFFFFFE.u0 = 0x04AA;
						Eq_2 ds_739 = fn1D10_0F47(ds_717, (ss->*sp_658).tFFFFFFFE);
						(ss->*sp_658).t0000 = ds_739;
						(ss->*sp_658).tFFFFFFFE.u0 = 0x04AA;
						Eq_2 ds_757 = fn1D10_0F47(ds_739, (ss->*sp_658).tFFFFFFFE);
						(ss->*sp_658).t0000 = ds_757;
						(ss->*sp_658).tFFFFFFFE.u0 = 0x04AA;
						Eq_2 ds_1862 = fn1D10_0F47(ds_757, (ss->*sp_658).tFFFFFFFE);
						seg28BA->tA186 = 0xF0;
						do
						{
							if (seg28BA->tA184 < 0x01)
							{
								ss->*((word32) sp_1340 - 2) = ds_1862;
								ss->*((word32) sp_1340 - 4) = 0x04AA;
								ds_1862 = fn1D10_0F47(ds_1862, ss->*((word32) sp_1340 - 4));
							}
						} while (seg28BA->tA186 > 0x00);
						do
						{
							(ss->*bp_1431).wFFFFFFD8 = fn0CE0_0547();
							if (seg28BA->tA184 < 0x01)
							{
								ss->*((word32) sp_1340 - 2) = ds_1862;
								ss->*((word32) sp_1340 - 4) = 0x04AA;
								ds_1862 = fn1D10_0F47(ds_1862, ss->*((word32) sp_1340 - 4));
							}
						} while ((ss->*bp_1431).wFFFFFFD8 != 0x00);
						ss->*((word32) sp_1340 - 2) = ds_1862;
						ss->*((word32) sp_1340 - 4) = 0x04AA;
						Eq_2 ds_868 = fn1D10_0F47(ds_1862, ss->*((word32) sp_1340 - 4));
						ss->*((word32) sp_1340 - 2) = ds_868;
						ss->*((word32) sp_1340 - 4) = 0x04AA;
						Eq_2 ds_886 = fn1D10_0F47(ds_868, ss->*((word32) sp_1340 - 4));
						ss->*((word32) sp_1340 - 2) = ds_886;
						ss->*((word32) sp_1340 - 4) = 0x04AA;
						Eq_2 ds_904 = fn1D10_0F47(ds_886, ss->*((word32) sp_1340 - 4));
						ss->*((word32) sp_1340 - 2) = 0x8001;
						ss->*((word32) sp_1340 - 4) = ds_904;
						ss->*((word32) sp_1340 - 6) = 1415;
						Eq_2 bx_918;
						Eq_2 cx_919;
						Eq_2 dx_920;
						(ss->*bp_1431).tFFFFFFD4 = fn0800_3615(ds_904, ss->*((word32) sp_1340 - 6), ss->*((word32) sp_1340 - 2), ss->*sp_1340, out cx_919, out dx_920, out bx_918);
						if ((ss->*bp_1431).tFFFFFFD4 == ~0x00)
						{
							ss->*((word32) sp_1340 - 2) = ds_904;
							ss->*((word32) sp_1340 - 4) = 1415;
							word16 dx_2078;
							word16 bx_2079;
							word16 di_2080;
							fn263F_03F3(cx_919, dx_920, bx_918, ds_904, out dx_2078, out bx_2079, out di_2080, out ds_904);
						}
						ss->*((word32) sp_1340 - 2) = ds_904;
						ss->*((word32) sp_1340 - 4) = 0x04AA;
						Eq_2 ds_963 = fn1D10_0F47(ds_904, ss->*((word32) sp_1340 - 4));
						ss->*((word32) sp_1340 - 2) = 0xE100;
						ss->*((word32) sp_1340 - 6) = seg28BA->tA882;
						ss->*((word32) sp_1340 - 8) = (ss->*bp_1431).tFFFFFFD4;
						word16 cx_2073;
						word16 dx_2074;
						word16 bx_2075;
						byte al_997 = (byte) fn0800_3C87(ds_963, ss->*((word32) sp_1340 - 8), ss->*((word32) sp_1340 - 6), ss->*((word32) sp_1340 - 2), out cx_2073, out dx_2074, out bx_2075);
						ss->*((word32) sp_1340 - 2) = (ss->*bp_1431).tFFFFFFD4;
						word16 dx_2076;
						word16 bx_2077;
						fn0800_2A93(al_997, ds_963, ss->*((word32) sp_1340 - 2), out dx_2076, out bx_2077);
						ss->*((word32) sp_1340 - 2) = ds_963;
						ss->*((word32) sp_1340 - 4) = 0x04AA;
						Eq_2 ds_1018 = fn1D10_0F47(ds_963, ss->*((word32) sp_1340 - 4));
						ss->*((word32) sp_1340 - 2) = 0x8001;
						ss->*((word32) sp_1340 - 4) = ds_1018;
						ss->*((word32) sp_1340 - 6) = 0x0591;
						Eq_2 bx_1032;
						Eq_2 cx_1033;
						Eq_2 dx_1034;
						(ss->*bp_1431).tFFFFFFD4 = fn0800_3615(ds_1018, ss->*((word32) sp_1340 - 6), ss->*((word32) sp_1340 - 2), ss->*sp_1340, out cx_1033, out dx_1034, out bx_1032);
						if ((ss->*bp_1431).tFFFFFFD4 == ~0x00)
						{
							ss->*((word32) sp_1340 - 2) = ds_1018;
							ss->*((word32) sp_1340 - 4) = 0x0591;
							word16 dx_2087;
							word16 bx_2088;
							word16 di_2089;
							fn263F_03F3(cx_1033, dx_1034, bx_1032, ds_1018, out dx_2087, out bx_2088, out di_2089, out ds_1018);
						}
						ss->*((word32) sp_1340 - 2) = ds_1018;
						ss->*((word32) sp_1340 - 4) = 0x04AA;
						ds_1077 = fn1D10_0F47(ds_1018, ss->*((word32) sp_1340 - 4));
						ss->*((word32) sp_1340 - 2) = 0x0242;
						ss->*((word32) sp_1340 - 6) = seg28BA->tA0B8;
						ss->*((word32) sp_1340 - 8) = (ss->*bp_1431).tFFFFFFD4;
						word16 cx_2081;
						word16 dx_2082;
						word16 bx_2083;
						byte al_1111 = (byte) fn0800_3C87(ds_1077, ss->*((word32) sp_1340 - 8), ss->*((word32) sp_1340 - 6), ss->*((word32) sp_1340 - 2), out cx_2081, out dx_2082, out bx_2083);
						ss->*((word32) sp_1340 - 2) = (ss->*bp_1431).tFFFFFFD4;
						word16 dx_2084;
						word16 bx_2085;
						fn0800_2A93(al_1111, ds_1077, ss->*((word32) sp_1340 - 2), out dx_2084, out bx_2085);
						ss->*((word32) sp_1340 - 4) = 0x00B4012C;
						fn1D10_1A65(ds_1077, ss->*((word32) sp_1340 - 4), ss->*((word32) sp_1340 - 2));
						ss->*((word32) sp_1340 - 4) = seg28BA->tAA80;
						ss->*((word32) sp_1340 - 8) = seg28BA->tA882;
						ss->*((word32) sp_1340 - 0x0C) = 0x000A000A;
						struct Eq_11676 * es_2086;
						fn216E_0000(ss->*((word32) sp_1340 - 0x0C), ss->*((word32) sp_1340 - 0x0A), ss->*((word32) sp_1340 - 8), ss->*((word32) sp_1340 - 6), ss->*((word32) sp_1340 - 4), ss->*((word32) sp_1340 - 2), out es_2086);
						do
						{
							(ss->*bp_1153).wFFFFFFD8 = (word16) (uint32) fn0CE0_05FB(ds_1077, out bp_1153, out ds_1077);
							Eq_2 sp_1160 = <invalid>;
							if (seg28BA->tA184 < 0x01)
							{
								ss->*((word16) sp_1160 - 2) = ds_1077;
								(ss->*((word16) sp_1160 - 4)).u0 = 0x04AA;
								ds_1077 = fn1D10_0F47(ds_1077, ss->*((word16) sp_1160 - 4));
							}
						} while ((ss->*bp_1153).wFFFFFFD8 != 0x00);
						(ss->*bp_1153).tFFFFFFDA.u0 = 0x00;
						while ((ss->*bp_1153).tFFFFFFDA < 0x50)
						{
							do
								;
							while (seg28BA->tA184 >= 0x01);
							ss->*((word32) sp_1160 - 2) = ds_1077;
							(ss->*((word32) sp_1160 - 4)).u0 = 0x04AA;
							ds_1077 = fn1D10_0F47(ds_1077, ss->*((word32) sp_1160 - 4));
							(ss->*bp_1153).tFFFFFFDA = (word16) (ss->*bp_1153).tFFFFFFDA + 1;
						}
						ss->*((word32) sp_1160 - 2) = seg28BA->tA18A;
						word16 dx_2090;
						word16 bx_2091;
						fn0800_2A93(~0x45, ds_1077, ss->*((word32) sp_1160 - 2), out dx_2090, out bx_2091);
						seg28BA->tA35C = 0x01;
						seg28BA->tA18A = (ss->*bp_1153).wFFFFFFD2;
						ss->*((word32) sp_1160 - 2) = ds_1077;
						(ss->*((word32) sp_1160 - 4)).u0 = 0x04EC;
						// Failed to bind call argument.
						// Please report this issue at https://github.com/uxmal/reko
						Eq_2 stackArg4 = <invalid>;
						Eq_11798 ebx_1278;
						word16 dx_2093;
						word16 bp_2094;
						struct Eq_11801 * es_2095;
						struct Eq_11802 * ds_2096;
						fn1D10_02AE(ebx_1278, ds_1077, stackArg4, out dx_2093, out ebx_1278, out bp_2094, out es_2095, out ds_2096);
						do
							;
						while (seg28BA->tA422 == 0x01);
						(ss->*((word32) sp_1160 - 2)).u0 = 0x8001;
						ss->*((word32) sp_1160 - 4) = ds_1077;
						(ss->*((word32) sp_1160 - 6)).u0 = 0x059B;
						word16 cx_2097;
						word16 dx_2098;
						word16 bx_2099;
						seg28BA->tA18A = fn0800_3615(ds_1077, ss->*((word32) sp_1160 - 6), ss->*((word32) sp_1160 - 2), ss->*sp_1160, out cx_2097, out dx_2098, out bx_2099);
						ss->*((word32) sp_1160 - 2) = ds_1077;
						(ss->*((word32) sp_1160 - 4)).u0 = 1227;
						// Failed to bind call argument.
						// Please report this issue at https://github.com/uxmal/reko
						Eq_2 stackArg4 = <invalid>;
						word32 ebx_1320;
						word16 dx_2101;
						word16 bp_2102;
						struct Eq_11864 * es_2103;
						struct Eq_11865 * ds_2104;
						fn1D10_02AE(SEQ(ebx_16_16_2013, bx_1332), ds_1077, stackArg4, out dx_2101, out ebx_1320, out bp_2102, out es_2103, out ds_2104);
						ss->*((word32) sp_1160 - 2) = seg28BA->tA18A;
						word16 bx_1332;
						word16 dx_2105;
						fn0800_2A93(~0x45, ds_1077, ss->*((word32) sp_1160 - 2), out dx_2105, out bx_1332);
						seg28BA->tA18A = (ss->*bp_1153).wFFFFFFD2;
						seg28BA->tA18C = 0xFF;
						fn1D10_1A88(ds_1077);
						seg28BA->tA35C = 0x00;
						word16 ebx_16_16_2013 = SLICE(ebx_1320, word16, 16);
						sp_1340 = sp_1160;
						bp_1431 = bp_1153;
					}
					goto l0CE0_110C;
				}
l0CE0_110C:
			} while ((uint16) seg28BA->t2F1E == 0x00 && (int16) seg28BA->t9FE3 == 0x00);
			__cli();
			word32 ebx_2040;
			word32 edx_2039;
			word16 cx_2038;
			struct Eq_10408 * es_2041;
			fn2425_01E8(ds_1077, out cx_2038, out edx_2039, out ebx_2040, out es_2041);
			__sti();
			struct Eq_10417 Eq_2::* sp_1388 = sp_1340 - 4;
			(ss->*sp_1388).t0000 = seg28BA->tA0E4;
			fn18D5_129B((ss->*sp_1388).t0000, (ss->*sp_1388).t0002);
			seg28BA->t302C = 0x00;
			sp_1399 = (struct Eq_9995 Eq_2::*) ((char *) &sp_1388->t0002 + 2);
			if ((int16) seg28BA->t9FE3 != 0x00)
				seg28BA->tA10C = 0x01;
			else
			{
				(ss->*sp_1388).t0000.u0 = 0x00;
				(ss->*sp_1388).tFFFFFFFE.u0 = 0x01;
				(ss->*sp_1388).tFFFFFFFA.u0 = 0x00;
				(ss->*sp_1388).tFFFFFFF8.u0 = 0x00;
				(ss->*sp_1388).tFFFFFFF6.u1 = 0x01;
				(ss->*sp_1388).tFFFFFFF4.u0 = 0x01;
				(ss->*sp_1388).tFFFFFFF2.u0 = 0x00;
				(ss->*sp_1388).tFFFFFFF0.u0 = 0x01;
				Eq_2 es_1428;
				fn2353_0004(ds_1077, (ss->*sp_1388).tFFFFFFF0, (ss->*sp_1388).tFFFFFFF2, (ss->*sp_1388).tFFFFFFF4, (ss->*sp_1388).tFFFFFFF6, (ss->*sp_1388).tFFFFFFF8, (ss->*sp_1388).tFFFFFFFA, (ss->*sp_1388).tFFFFFFFE, out bp_1431, out es_1428);
				__cli();
				word16 dx_2043;
				word16 cx_2042;
				word16 bx_2044;
				fn2425_0286(es_1428, ds_1077, out cx_2042, out dx_2043, out bx_2044, out ds_1077);
				__sti();
				Eq_2 sp_1433 = <invalid>;
				do
				{
					do
					{
						Eq_2 edx_1458 = <invalid>;
						cui16 dx_1468 = (word16) edx_1458;
						word16 dx_2064;
						word32 ebx_2065;
						cui16 ax_1470 = (word16) (uint32) fn2331_0167(ds_1077, out dx_2064, out ebx_2065);
						seg28BA->tA10A = dx_1468;
						seg28BA->tA108 = ax_1470;
					} while ((ax_1470 | dx_1468) == 0x00);
					byte * es_bx_1478 = seg28BA->tA108;
					Eq_2 es_1479 = SLICE(es_bx_1478, selector, 16);
					uint16 ax_1483 = (uint16) *es_bx_1478;
					if (ax_1483 <= 0x05)
					{
						switch (ax_1483 - 0x02 << 0x01)
						{
						case 0x00:
l0CE0_11E7:
							seg28BA->t2F1E = 0x00;
							break;
						case 0x01:
l0CE0_11BE:
							seg28BA->tA10C = 0x01;
							break;
						case 0x02:
							if ((ss->*bp_1431).w0006 != 0x00)
								goto l0CE0_11E7;
							(ss->*((word32) sp_1433 + 16)).u1 = 0x00;
							(ss->*((word32) sp_1433 + 0x0E)).u0 = 0x04;
							goto l0CE0_11D0;
						case 0x03:
							(ss->*((word32) sp_1433 + 16)).u1 = 0x00;
							(ss->*((word32) sp_1433 + 0x0E)).u0 = 0x05;
l0CE0_11D0:
							fn2331_00BA(es_1479, ds_1077, ss->*((word32) sp_1433 + 0x0E), ss->*((word32) sp_1433 + 16), ss->*((word32) sp_1433 + 18));
							goto l0CE0_11BE;
						}
					}
					sp_1399 = (struct Eq_9995 Eq_2::*) ((word32) sp_1433 + 20);
				} while ((uint16) seg28BA->tA10C == 0x00 && seg28BA->t2F1E != 0x00);
			}
		} while ((uint16) seg28BA->tA10C == 0x00);
		__cli();
		word16 cx_2045;
		struct Eq_10563 * es_2046;
		word32 ebx_1562;
		word32 edx_1563;
		fn2425_01E8(ds_1077, out cx_2045, out edx_1563, out ebx_1562, out es_2046);
		__sti();
		Eq_2 ds_1571 = fn2476_0362(ds_1077);
		struct Eq_10579 Eq_2::* sp_1585 = sp_1399 - 4;
		(ss->*sp_1585).t0000 = seg28BA->tA0E4;
		word16 cx_2047;
		Eq_2 ds_1587;
		word16 dx_2048;
		word16 bx_2049;
		fn0800_1C24(ds_1571, (ss->*sp_1585).t0002, out cx_2047, out dx_2048, out bx_2049, out ds_1587);
		(ss->*sp_1585).t0000 = seg28BA->tA0B8;
		Eq_2 ds_1604;
		word16 bx_2052;
		word16 cx_2050;
		word16 dx_2051;
		fn0800_1C24(ds_1587, (ss->*sp_1585).t0002, out cx_2050, out dx_2051, out bx_2052, out ds_1604);
		(ss->*sp_1585).t0000 = seg28BA->t9FA8;
		word16 bx_2055;
		word16 dx_2054;
		word16 cx_2053;
		Eq_2 ds_1621;
		fn0800_1C24(ds_1604, (ss->*sp_1585).t0002, out cx_2053, out dx_2054, out bx_2055, out ds_1621);
		(ss->*sp_1585).t0000 = *((word32) ds_1621 + 39906);
		word16 bx_2058;
		word16 dx_2057;
		word16 cx_2056;
		Eq_2 ds_1636;
		fn0800_1C24(ds_1621, (ss->*sp_1585).t0002, out cx_2056, out dx_2057, out bx_2058, out ds_1636);
		(ss->*bp_1431).tFFFFFFDA.u0 = 0x00;
		word16 ebx_16_16_1947 = SLICE(ebx_1562, word16, 16);
		word16 edx_16_16_1954 = SLICE(edx_1563, word16, 16);
		while ((ss->*bp_1431).tFFFFFFDA < 0x19)
		{
			Eq_10693 bx_1664 = bp_1431 - 0xC4 + ((ss->*bp_1431).tFFFFFFDA *s 0x06) / 8;
			if ((ss->*bx_1664 | ss->*((word16) bx_1664 + 2)) != 0x00)
			{
				Eq_10858 bx_1673 = bp_1431 - 0xC4 + ((ss->*bp_1431).tFFFFFFDA *s 0x06) / 8;
				if (ss->*((word16) bx_1673 + 2) != ~0x00 || ss->*bx_1673 != ~0x00)
				{
					struct Eq_10872 Eq_2::* sp_1689 = sp_1399 - 4;
					(ss->*sp_1689).t0000 = SEQ(ss, bp_1431 - 0xC4)[(ss->*bp_1431).tFFFFFFDA];
					ds_1636 = fn1744_0A6F(ds_1636, (ss->*sp_1689).t0000);
				}
			}
			(ss->*bp_1431).tFFFFFFDA = (word16) (ss->*bp_1431).tFFFFFFDA + 1;
		}
		struct Eq_10711 Eq_2::* sp_1712 = sp_1399 - 4;
		(ss->*sp_1712).t0000 = (ss->*bp_1431).tFFFFFFFC;
		word16 bx_2061;
		word16 dx_2060;
		word16 cx_2059;
		fn0800_1C24(ds_1636, (ss->*sp_1712).t0002, out cx_2059, out dx_2060, out bx_2061, out ds);
		fn2057_0384(ds);
		word16 bx_2062;
		word16 dx_1738;
		struct Eq_10738 * es_2063;
		fn209F_02A7(ds, out dx_1738, out bx_2062, out es_2063);
		fn1D10_1A16(ds);
		byte dl_1750 = (ss->*bp_1431).bFFFFFFD6;
		seg2862->t0000 = dl_1750;
		es_1754.u0 = 0x28BA;
		ebx = SEQ(ebx_16_16_1947, bx_1744);
		edx = SEQ(edx_16_16_1954, SLICE(dx_1738, byte, 8), dl_1750);
	}
	Eq_9714 bp_1855 = (ss->*bp_1431).a0000[0];
	ebxOut = ebx;
	bpOut = bp_1855;
	esOut = es_1754;
	dsOut = ds;
	return edx;
}

