// ZORTON_16CC.c
// Generated by decompiling ZORTON.EXE
// using Reko decompiler version 0.9.2.3.

#include "ZORTON_16CC.h"

// 16CC:001C: void fn16CC_001C(Stack Eq_2 ptrArg04, Stack Eq_12927 wArg08, Stack (ptr16 Eq_12928) wArg0A)
// Called from:
//      fn1744_044D
void fn16CC_001C(Eq_2 ptrArg04, Eq_12927 wArg08, struct Eq_12928 * wArg0A)
{
	word16 esi_16_16_272 = SLICE(esi, word16, 16);
	struct Eq_12932 Eq_12961::* wArg04_789 = (word16) ptrArg04;
	*((word32) ptrArg04 + 26) |= 0x02;
	word32 edx_48 = *((word32) ptrArg04 + 16)->**((word32) ptrArg04 + 0x0E);
	cu16 ax_57 = *((word32) ptrArg04 + 6);
	*((word32) ptrArg04 + 2) = ax_57;
	cu16 dx_49 = (word16) edx_48;
	struct Eq_12961 * fs_40 = SLICE(ptrArg04, selector, 16);
	struct Eq_12932 Eq_12961::* si_279 = (word16) ptrArg04;
	byte dl_169 = (byte) (dx_49 >> 0x01);
	uint8 cl_55 = (byte) (SEQ(SLICE(edx_48, word16, 16), dx_49 >> 0x01) >> 0x10);
	byte al_74 = (byte) ax_57;
	if (ax_57 < seg16CC->w0010)
		seg16CC->w0010 = (cu16 *) ax_57;
	uint16 bx_67 = (uint16) cl_55 + ax_57;
	if (bx_67 >= seg16CC->w0014)
		seg16CC->w0014 = (uint16 *) bx_67;
	cup16 bx_88 = *((word32) ptrArg04 + 4);
	*ptrArg04 = bx_88;
	ui16 ax_82 = (ax_57 << 0x06) + SEQ(al_74, 0x00);
	if (bx_88 < seg16CC->w000E)
		seg16CC->w000E = (cup16 *) bx_88;
	uint16 cx_102 = ((uint16) dl_169 << 0x01) + bx_88;
	if (cx_102 >= seg16CC->w0012)
		seg16CC->w0012 = (uint16 *) cx_102;
	seg16CC->w000A = (ui16 *) (ax_82 + bx_88);
	if ((*((word32) ptrArg04 + 26) & 0x04) != 0x00)
	{
		uint32 eax_121 = *((word32) ptrArg04 + 18);
		word32 Eq_13064::* ax_122 = (word16) eax_121;
		struct Eq_13064 * ax_125 = (word16) (eax_121 >> 0x10);
		ax_125->*ax_122 = SEQ(SLICE(SEQ(SLICE(eax_121 >> 0x10, word16, 16), 0x00, cl_55) << 0x10, word24, 8), dl_169);
		struct Eq_13079 Eq_13064::* di_140 = ax_122 + 1;
		struct Eq_13036 * ax_154 = wArg0A->*((word16) wArg08 + 0x0E);
		uint8 bl_157 = cl_55;
		byte ch_668 = 0x00;
		uint16 ax_163 = (uint16) (0xA0 - dl_169);
		Eq_13093 si_165 = seg16CC->w000A + wArg0A->*((word16) wArg08 + 0x0C);
		if ((si_165 & 0x01) == 0x00)
		{
			do
			{
				word16 cx_226 = SEQ(ch_668, dl_169);
				while (true)
				{
					ch_668 = SLICE(cx_226, byte, 8);
					if (cx_226 == 0x00)
						break;
					(ax_125->*di_140).t0000 = ax_154->*si_165;
					si_165 = (word16) si_165 + 2;
					++di_140;
					--cx_226;
				}
				si_165 = (word16) si_165 + ax_163 * 0x02;
				--bl_157;
			} while (bl_157 != 0x00);
		}
		else
		{
			--dl_169;
			if (dl_169 == 0x01)
			{
				do
				{
					(ax_125->*di_140).t0000 = ax_154->*si_165;
					++di_140;
					si_165 = (word16) (ax_163 * 0x02) + ((word16) si_165 + 2);
					--bl_157;
				} while (bl_157 != 0x00);
			}
			else
			{
				do
				{
					(ax_125->*di_140).t0000 = ax_154->*si_165;
					Eq_13193 si_179 = (word16) si_165 + 1;
					union Eq_13196 Eq_13064::* di_180 = (char *) &di_140->t0000 + 1;
					word16 cx_183 = SEQ(ch_668, dl_169 - 0x01);
					while (true)
					{
						ch_668 = SLICE(cx_183, byte, 8);
						if (cx_183 == 0x00)
							break;
						ax_125->*di_180 = ax_154->*si_179;
						si_179 = (word16) si_179 + 2;
						di_180 = (union Eq_13196 Eq_13064::*) ((char *) di_180 + 2);
						--cx_183;
					}
					ax_125->*di_180 = ax_154->*si_179;
					di_140 = (struct Eq_13079 Eq_13064::*) ((char *) di_180 + 1);
					si_165 = (word16) (ax_163 * 0x02) + ((word16) si_179 + 1);
					--bl_157;
				} while (bl_157 != 0x00);
			}
		}
		byte bl_253 = wArg0A->*((word16) wArg08 + 16);
		wArg0A->*((word16) wArg08 + ((word16) ((uint16) bl_253 << 0x02) + 18)) = SEQ(SEQ(esi_16_16_272, fs_40), wArg04_789);
		wArg0A->*((word16) wArg08 + 16) = bl_253 + 0x01;
		si_279 = wArg04_789;
	}
	Eq_13029 di_293 = seg16CC->w000A + wArg0A->*((word16) wArg08 + 0x0C);
	struct Eq_13036 * cx_294 = wArg0A->*((word16) wArg08 + 0x0E);
	struct Eq_13040 * cx_296 = (fs_40->*si_279).ptr0010;
	uint8 bl_305 = cl_55;
	union Eq_13045 Eq_13040::* si_306 = (fs_40->*si_279).w000E + 0x04;
	if (((fs_40->*si_279).w001A & 0x20) != 0x00)
	{
		uint16 ax_400 = (uint16) (0xA0 - dl_169);
		byte ch_728 = 0x00;
		if ((di_293 & 0x01) == 0x00)
		{
			do
			{
l16CC_0188:
				word16 cx_541 = SEQ(ch_728, dl_169);
				do
				{
					word16 ax_527 = cx_296->*si_306;
					byte ah_529 = SLICE(ax_527, byte, 8);
					byte al_533 = (byte) ax_527;
					si_306 = (union Eq_13045 Eq_13040::*) ((char *) si_306 + 2);
					if (ah_529 == 0x00)
					{
						if (ah_529 != al_533)
						{
							cx_294->*di_293 = al_533;
							--cx_541;
							di_293 = (word16) di_293 + 2;
							ch_728 = SLICE(cx_541, byte, 8);
							if (cx_541 != 0x00)
								continue;
							di_293 += ax_400 * 0x02;
							--bl_305;
							if (bl_305 == 0x00)
								return;
							goto l16CC_0188;
						}
						else
						{
							--cx_541;
							di_293 = (word16) di_293 + 2;
							ch_728 = SLICE(cx_541, byte, 8);
							if (cx_541 != 0x00)
								continue;
							di_293 += ax_400 * 0x02;
							--bl_305;
							if (bl_305 == 0x00)
								return;
							goto l16CC_0188;
						}
					}
					if (al_533 == 0x00)
					{
						cx_294->*((word16) di_293 + 1) = ah_529;
						--cx_541;
						di_293 = (word16) di_293 + 2;
						ch_728 = SLICE(cx_541, byte, 8);
						if (cx_541 != 0x00)
							continue;
						di_293 += ax_400 * 0x02;
						--bl_305;
						if (bl_305 == 0x00)
							return;
						goto l16CC_0188;
					}
					cx_294->*di_293 = ax_527;
					--cx_541;
					di_293 = (word16) di_293 + 2;
					ch_728 = SLICE(cx_541, byte, 8);
				} while (cx_541 != 0x00);
				di_293 += ax_400 * 0x02;
				--bl_305;
			} while (bl_305 != 0x00);
		}
		else
		{
			byte dl_407 = dl_169 - 0x01;
			Eq_13154 bp_408 = ax_400 * 0x02 + 0x01;
			do
			{
l16CC_01E2:
				byte al_415 = cx_296->*si_306;
				struct Eq_13285 Eq_13040::* si_416 = (char *) si_306 + 1;
				word16 cx_444 = SEQ(ch_728, dl_407);
				if (al_415 != 0x00)
					cx_294->*di_293 = al_415;
				Eq_13236 di_425 = (word16) di_293 + 1;
				do
				{
					word16 ax_430 = (cx_296->*si_416).t0000;
					byte ah_432 = SLICE(ax_430, byte, 8);
					byte al_436 = (byte) ax_430;
					si_416 += 2;
					if (ah_432 == 0x00)
					{
						if (ah_432 != al_436)
						{
							cx_294->*di_425 = al_436;
							--cx_444;
							di_425 = (word16) di_425 + 2;
							ch_728 = SLICE(cx_444, byte, 8);
							if (cx_444 != 0x00)
								continue;
							byte al_446 = (cx_296->*si_416).t0000;
							si_306 = (union Eq_13045 Eq_13040::*) (si_416 + 1);
							if (al_446 != 0x00)
								cx_294->*di_425 = al_446;
							di_293 = di_425 + bp_408;
							--bl_305;
							if (bl_305 == 0x00)
								return;
							goto l16CC_01E2;
						}
						else
						{
							--cx_444;
							di_425 = (word16) di_425 + 2;
							ch_728 = SLICE(cx_444, byte, 8);
							if (cx_444 != 0x00)
								continue;
							byte al_466 = (cx_296->*si_416).t0000;
							si_306 = (union Eq_13045 Eq_13040::*) (si_416 + 1);
							if (al_466 != 0x00)
								cx_294->*di_425 = al_466;
							di_293 = di_425 + bp_408;
							--bl_305;
							if (bl_305 == 0x00)
								return;
							goto l16CC_01E2;
						}
					}
					if (al_436 == 0x00)
					{
						cx_294->*((word16) di_425 + 1) = ah_432;
						--cx_444;
						di_425 = (word16) di_425 + 2;
						ch_728 = SLICE(cx_444, byte, 8);
						if (cx_444 != 0x00)
							continue;
						byte al_507 = (cx_296->*si_416).t0000;
						si_306 = (union Eq_13045 Eq_13040::*) (si_416 + 1);
						if (al_507 != 0x00)
							cx_294->*di_425 = al_507;
						di_293 = di_425 + bp_408;
						--bl_305;
						if (bl_305 == 0x00)
							return;
						goto l16CC_01E2;
					}
					cx_294->*di_425 = ax_430;
					--cx_444;
					di_425 = (word16) di_425 + 2;
					ch_728 = SLICE(cx_444, byte, 8);
				} while (cx_444 != 0x00);
				byte al_488 = (cx_296->*si_416).t0000;
				si_306 = (union Eq_13045 Eq_13040::*) (si_416 + 1);
				if (al_488 != 0x00)
					cx_294->*di_425 = al_488;
				di_293 = di_425 + bp_408;
				--bl_305;
			} while (bl_305 != 0x00);
		}
	}
	else
	{
		uint16 ax_318 = (uint16) (0xA0 - dl_169);
		byte ch_688 = 0x00;
		if ((di_293 & 0x01) == 0x00)
		{
			do
			{
				word16 cx_378 = SEQ(ch_688, dl_169);
				while (true)
				{
					ch_688 = SLICE(cx_378, byte, 8);
					if (cx_378 == 0x00)
						break;
					cx_294->*di_293 = cx_296->*si_306;
					si_306 = (union Eq_13045 Eq_13040::*) ((char *) si_306 + 2);
					di_293 = (word16) di_293 + 2;
					--cx_378;
				}
				di_293 += ax_318 * 0x02;
				--bl_305;
			} while (bl_305 != 0x00);
		}
		else
		{
			byte dl_324 = dl_169 - 0x01;
			if (dl_324 == 0x00)
			{
				do
				{
					cx_294->*di_293 = cx_296->*si_306;
					si_306 = (union Eq_13045 Eq_13040::*) ((char *) si_306 + 2);
					di_293 = (word16) (ax_318 * 0x02) + ((word16) di_293 + 2);
					--bl_305;
				} while (bl_305 != 0x00);
			}
			else
			{
				do
				{
					cx_294->*di_293 = cx_296->*si_306;
					union Eq_13485 Eq_13040::* si_334 = (char *) si_306 + 1;
					Eq_13488 di_335 = (word16) di_293 + 1;
					word16 cx_338 = SEQ(ch_688, dl_324);
					while (true)
					{
						ch_688 = SLICE(cx_338, byte, 8);
						if (cx_338 == 0x00)
							break;
						cx_294->*di_335 = cx_296->*si_334;
						si_334 = (union Eq_13485 Eq_13040::*) ((char *) si_334 + 2);
						di_335 = (word16) di_335 + 2;
						--cx_338;
					}
					cx_294->*di_335 = cx_296->*si_334;
					si_306 = (union Eq_13045 Eq_13040::*) ((char *) si_334 + 1);
					di_293 = (word16) (ax_318 * 0x02) + ((word16) di_335 + 1);
					--bl_305;
				} while (bl_305 != 0x00);
			}
		}
	}
}

// 16CC:02B2: void fn16CC_02B2(Stack Eq_2 ptrArg04)
// Called from:
//      fn1744_044D
void fn16CC_02B2(Eq_2 ptrArg04)
{
	Eq_13541 ecx_16_16_250 = SLICE(ecx, word16, 16);
	Eq_13544 si_38 = (word16) ptrArg04;
	seg16CC->t001A = (union Eq_13544 *) si_38;
	struct Eq_12945 * bx_41 = *((word32) ptrArg04 + 16);
	*((word32) ptrArg04 + 16) = 0x00;
	Eq_13556 es_di_43 = *((word32) ptrArg04 + 0x0C);
	word16 di_111 = (word16) es_di_43;
	seg16CC->w000C = (word16 *) di_111;
	struct Eq_13564 * fs_40 = SLICE(ptrArg04, selector, 16);
	struct Eq_13566 * es_354 = SLICE(es_di_43, selector, 16);
	Eq_13568 bx_290 = bx_41 << 0x02;
	Eq_13571 si_187 = (word16) si_38 + 18;
	do
	{
		ptr32 ds_si_54 = Mem53[fs_40:bx_290 - 0x04 + si_187:segptr32];
		cu16 dx_58 = ds_si_54->w0002;
		struct Eq_13576 * ds_si_59 = ds_si_54->ptr0012;
		cup16 ax_57 = ds_si_54->w0000;
		byte dl_94 = (byte) dx_58;
		struct Eq_13648 * ds_66 = SLICE(ds_si_59, selector, 16);
		word16 si_68 = (word16) ds_si_59;
		if (ax_57 < seg16CC->w000E)
			seg16CC->w000E = (cup16 *) ax_57;
		cup16 cx_71 = (word16) ds_si_59->t0000 + ((word16) ds_si_59->t0000 + ax_57);
		if (cx_71 >= seg16CC->w0012)
			seg16CC->w0012 = (cup16 *) cx_71;
		if (dx_58 < seg16CC->w0010)
			seg16CC->w0010 = (cu16 *) dx_58;
		cup16 cx_88 = (word16) ds_si_59->t0002 + dx_58;
		if (cx_88 >= seg16CC->w0014)
			seg16CC->w0014 = (cup16 *) cx_88;
		Eq_13579 al_123 = ds_si_59->t0000;
		Eq_13610 di_112 = di_111 + ((SEQ(dl_94, 0x00) + (dx_58 << 0x06)) + ax_57);
		struct Eq_13619 Eq_13648::* si_118 = si_68 + 0x04;
		Eq_13599 ah_120 = ds_si_59->t0002;
		uint16 dx_126 = (uint16) (0xA0 - al_123);
		byte ch_361 = 0x00;
		if ((di_112 & 0x01) == 0x00)
		{
			do
			{
				word16 cx_169 = SEQ(ch_361, al_123);
				while (true)
				{
					ch_361 = SLICE(cx_169, byte, 8);
					if (cx_169 == 0x00)
						break;
					es_354->*di_112 = (ds_66->*si_118).t0000;
					si_118 += 2;
					di_112 = (word16) di_112 + 2;
					--cx_169;
				}
				di_112 = (word16) di_112 + dx_126 * 0x02;
				--ah_120;
			} while (ah_120 != 0x00);
		}
		else
		{
			do
			{
				es_354->*di_112 = (ds_66->*si_118).t0000;
				struct Eq_13664 Eq_13648::* si_141 = si_118 + 1;
				Eq_13668 di_142 = (word16) di_112 + 1;
				word16 cx_145 = SEQ(ch_361, al_123 - 0x01);
				while (true)
				{
					ch_361 = SLICE(cx_145, byte, 8);
					if (cx_145 == 0x00)
						break;
					es_354->*di_142 = (ds_66->*si_141).t0000;
					si_141 += 2;
					di_142 = (word16) di_142 + 2;
					--cx_145;
				}
				es_354->*di_142 = (ds_66->*si_141).t0000;
				si_118 = (struct Eq_13619 Eq_13648::*) (si_141 + 1);
				di_112 = (word16) di_142 + 1 + dx_126 * 0x02;
				--ah_120;
			} while (ah_120 != 0x00);
		}
		struct Eq_13698 * ds_di_206 = fs_40->*((word16) (bx_290 - 0x04) + ((word16) si_38 + 18));
		si_187 = (word16) si_38 + 18;
		struct Eq_13705 * ds_207 = SLICE(ds_di_206, selector, 16);
		word16 di_208 = (word16) ds_di_206;
		if ((ds_di_206->w001A & 0x10) != 0x00)
		{
			struct Eq_13698 * eax_214 = ds_di_206->ptr0028;
			struct Eq_13739 Eq_13757::* ax_220 = (word16) eax_214;
			if (eax_214 != null)
			{
				struct Eq_13698 * ecx_219 = ds_di_206->ptr0024;
				((word16) (eax_214 >> 0x10)->*ax_220).ptr0024 = ecx_219;
				ecx_16_16_250.u0 = SLICE(ecx_219, word16, 16);
			}
			struct Eq_13698 * eax_230 = ds_di_206->ptr0024;
			struct Eq_13747 Eq_13778::* ax_236 = (word16) eax_230;
			if (eax_230 != null)
			{
				struct Eq_13698 * ecx_235 = ds_di_206->ptr0028;
				((word16) (eax_230 >> 0x10)->*ax_236).ptr0028 = ecx_235;
				ecx_16_16_250.u0 = SLICE(ecx_235, word16, 16);
			}
			Eq_13541 ecx_263 = SEQ(ecx_16_16_250, ds_207);
			si_187 = seg16CC->t001A;
			struct Eq_13698 * ecx_268 = SEQ(ecx_263, di_208);
			ecx_16_16_250 = ecx_263;
			if (fs_40->*si_187 == ecx_268)
				fs_40->*si_187 = ds_di_206->ptr0024;
			if (fs_40->*((word16) si_187 + 4) == ecx_268)
				fs_40->*((word16) si_187 + 4) = ds_di_206->ptr0028;
		}
		di_111 = (word16) seg16CC->w000C;
		bx_290 -= 0x04;
	} while (bx_290 != 0x00);
}

// 16CC:0481: void fn16CC_0481(Stack Eq_2 ptrArg04)
// Called from:
//      fn0CE0_08FC
void fn16CC_0481(Eq_2 ptrArg04)
{
	struct Eq_13819 * ds_91 = SLICE(ptrArg04, selector, 16);
	struct Eq_13821 Eq_13819::* si_39 = (word16) ptrArg04 + 0x0C8A;
	struct Eq_13825 Eq_12853::* di_43 = &Eq_12853::t0C8A;
	byte bl_44;
	for (bl_44 = 0x8C; bl_44 != 0x00; --bl_44)
	{
		word16 cx_45;
		for (cx_45 = 77; cx_45 != 0x00; --cx_45)
		{
			(0xA000->*di_43).t0000 = (ds_91->*si_39).t0000;
			si_39 = (struct Eq_13821 Eq_13819::*) ((char *) &si_39->t0000 + 4);
			di_43 = (struct Eq_13825 Eq_12853::*) ((char *) &di_43->t0000 + 4);
		}
		(0xA000->*di_43).t0000 = (ds_91->*si_39).t0000;
		++si_39;
		++di_43;
	}
}

// 16CC:04CA: void fn16CC_04CA(Stack segptr32 ptrArg04)
// Called from:
//      fn0CE0_0170
//      fn0CE0_023E
//      fn0CE0_030C
//      fn0CE0_03D4
void fn16CC_04CA(segptr32 ptrArg04)
{
	cui16 ax_41 = seg16CC->w000E;
	cui16 cx_46 = seg16CC->w0010;
	Eq_13865 cx_54 = (cx_46 << 0x06) + SEQ((byte) cx_46, 0x00) + (ax_41 & ~0x03);
	uint16 dx_45 = (seg16CC->w0012 - (ax_41 & ~0x03) >> 0x02) + 0x01;
	struct Eq_13884 * ds_120 = SLICE(ptrArg04, selector, 16);
	Eq_13865 di_109 = cx_54;
	word32 Eq_13884::* si_108 = (word16) cx_54 + (word16) ptrArg04;
	byte bl_115 = (byte) (seg16CC->w0014 - seg16CC->w0010);
	cui16 ax_61 = 0x50 - dx_45;
	do
	{
		uint16 cx_110;
		for (cx_110 = dx_45; cx_110 != 0x00; --cx_110)
		{
			0xA000->*di_109 = ds_120->*si_108;
			++si_108;
			di_109 = (word16) di_109 + 4;
		}
		si_108 += ax_61 << 0x02;
		di_109 = (word16) di_109 + (ax_61 << 0x02);
		--bl_115;
	} while (bl_115 != 0x00);
	seg16CC->w000E = (word16 *) 600;
	seg16CC->w0010 = (word16 *) 600;
	seg16CC->w0012 = (word16 *) 0x00;
	seg16CC->w0014 = (word16 *) 0x00;
}

