// ZORTON_2425.c
// Generated by decompiling ZORTON.EXE
// using Reko decompiler version 0.9.2.3.

#include "ZORTON_2425.h"

// 2425:000A: Register word16 fn2425_000A(Register out (ptr16 Eq_28126) dsOut)
// Called from:
//      main
word16 fn2425_000A(struct Eq_28126 & dsOut)
{
	struct Eq_28127 * ds_115;
	struct Eq_28128 Eq_28132::* bp_22 = fn0800_22C3(0x33, fp - 22, out ds_115);
	(ss->*bp_22).wFFFFFFEC = 0x07;
	(ss->*bp_22).wFFFFFFF0 = 0x00;
	(ss->*bp_22).wFFFFFFF2 = 600;
	Eq_2 sp_30 = <invalid>;
	ss->*((word32) sp_30 + 4) = ss;
	ss->*((word32) sp_30 + 2) = bp_22 - 0x14;
	ss->*sp_30 = 0x33;
	struct Eq_28164 * ds_116;
	struct Eq_28128 Eq_28132::* bp_50 = fn0800_22C3(ss->*sp_30, ss->*((word32) sp_30 + 2), out ds_116);
	(ss->*bp_50).wFFFFFFEC = 0x08;
	(ss->*bp_50).wFFFFFFF0 = 0x00;
	(ss->*bp_50).wFFFFFFF2 = 0xBE;
	Eq_2 sp_58 = <invalid>;
	ss->*((word32) sp_58 + 4) = ss;
	ss->*((word32) sp_58 + 2) = bp_50 - 0x14;
	ss->*sp_58 = 0x33;
	struct Eq_28126 * ds_82;
	struct Eq_28128 Eq_28132::* bp_78 = fn0800_22C3(ss->*sp_58, ss->*((word32) sp_58 + 2), out ds_82);
	seg2863->b0004 = (byte *) 0x00;
	word16 bp_99 = (ss->*bp_78).w0000;
	dsOut = ds_82;
	return bp_99;
}

// 2425:01E8: Register word32 fn2425_01E8(Register Eq_2 ds, Register out ptr16 cxOut, Register out Eq_8540 edxOut, Register out Eq_8541 ebxOut, Register out (ptr16 Eq_47) esOut)
// Called from:
//      fn0CE0_0170
//      fn0CE0_023E
//      fn0CE0_030C
//      fn0CE0_03D4
//      fn0CE0_08FC
//      fn1D10_0FB3
//      fn1D10_1153
//      fn1ED7_000E
//      fn1F0F_000F
//      fn1F0F_0BF7
//      fn226D_00F9
//      fn226D_057F
//      fn226D_0BC6
//      fn23F8_00A0
//      fn2504_094D
word32 fn2425_01E8(Eq_2 ds, ptr16 & cxOut, union Eq_8540 & edxOut, union Eq_8541 & ebxOut, struct Eq_47 & esOut)
{
	if (seg28BA->t30A0 != 0x00)
	{
		Eq_2 v7_11 = seg28BA->tAA80;
		fn216E_03D8(0x00, 0x00, 0x3C, 0x0A, 0x00, v7_11, SLICE(v7_11, word16, 16));
		word16 dx_180;
		word16 bx_181;
		fn0800_2056(ds, out dx_180, out bx_181);
		Eq_2 dx_ax_175 = <invalid>;
		uint64 edx_eax_47 = (uint64) dx_ax_175;
		uint32 eax_50 = (uint32) (edx_eax_47 /u 1000);
		word16 bx_58;
		byte al_182;
		fn0F2B_130A(ds, 0x32, 0x00, (word16) eax_50, out al_182, out cx, out bx_58);
		eax_16_16 = SLICE(eax_50, word16, 16);
		ebx.u0 = (uint32) bx_58;
		edx = SEQ(SLICE((uint32) (edx_eax_47 % 1000), word16, 16), dx_60);
	}
	seg2863->b0004 = (byte *) 0x00;
	word16 edx_16_16_162 = SLICE(edx, word16, 16);
	word16 ebx_16_16_155 = SLICE(ebx, word16, 16);
	if (seg2864->w0088 != 0x00)
	{
		Eq_11683 v17_78 = seg28BA->tAA80;
		struct Eq_28287 * es_183;
		cx = fn216E_0000(seg2863->t0000, seg2863->t0002, 0x88, seg2864, v17_78, SLICE(v17_78, word16, 16), out es_183);
		ebx = SEQ(ebx_16_16_155, bx_98);
		edx = SEQ(edx_16_16_162, dx_100);
	}
	seg2864->w0088 = (word16 *) 0x00;
	cxOut = cx;
	edxOut = edx;
	ebxOut = ebx;
	esOut = seg2864;
	return SEQ(eax_16_16, seg2864);
}

// 2425:0286: Register word32 fn2425_0286(Register Eq_2 es, Register Eq_2 ds, Register out Eq_2 cxOut, Register out ptr16 dxOut, Register out Eq_8657 bxOut, Register out (ptr16 Eq_8658) dsOut)
// Called from:
//      fn0CE0_0170
//      fn0CE0_023E
//      fn0CE0_030C
//      fn0CE0_03D4
//      fn0CE0_08FC
//      fn1D10_1153
//      fn1F0F_0BF7
//      fn226D_00F9
//      fn226D_057F
//      fn226D_0BC6
//      fn23F8_00A0
//      fn2504_094D
//      main
word32 fn2425_0286(Eq_2 es, Eq_2 ds, union Eq_2 & cxOut, ptr16 & dxOut, union Eq_8657 & bxOut, struct Eq_8658 & dsOut)
{
	struct Eq_8658 * ds_28;
	Eq_8657 bx_108;
	ptr16 dx_101;
	Eq_2 cx_100 = fn0800_21F9(es, ds, 0x33, fp - 0x12, fp - 0x12, out dx_101, out bx_108, out ds_28);
	ds_28->tA524 = wLoc0E >> 0x01;
	ds_28->wA526 = wLoc0C;
	if (seg28BA->t302C == 0x00)
	{
		seg2863->b0004 = (byte *) 0x01;
		goto l2425_0353;
	}
	__cli();
	Eq_10469 v10_48 = ds_28->tA524;
	eax_16_16 = SLICE(fn2425_0405(v10_48, SLICE(v10_48, word16, 16), out cx_100, out dx_101, out bx_108), word16, 16);
	__sti();
	if ((ds_28->wA522 & 0x0A) == 0x00 || seg28BA->t3030 == 0x00)
		goto l2425_0353;
	if ((ds_28->wA522 & 0x02) != 0x00)
	{
		struct Eq_28383 * es_bx_72 = seg28BA->t3030;
		bx_108 = (word16) es_bx_72;
		if (es_bx_72->dw0010 != 0x00)
		{
			ds_28->wA522 = 0x00;
			word32 eax_107;
			(seg28BA->t3032->*((word16) bx_108 + 16))();
			eax_16_16 = SLICE(eax_107, word16, 16);
l2425_033A:
			ds_28->wA522 = 0x00;
			ds_28->wA528 = 0x00;
l2425_0353:
			seg2863->b0004 = (byte *) 0x01;
			cxOut = cx_100;
			dxOut = dx_101;
			bxOut = bx_108;
			dsOut = ds_28;
			return SEQ(eax_16_16, 10339);
		}
	}
	if ((ds_28->wA522 & 0x08) != 0x00)
	{
		struct Eq_28408 * es_bx_84 = seg28BA->t3030;
		bx_108 = (word16) es_bx_84;
		if (es_bx_84->dw0014 != 0x00)
		{
			ds_28->wA522 = 0x00;
			word32 eax_97;
			(seg28BA->t3032->*((word16) bx_108 + 20))();
			eax_16_16 = SLICE(eax_97, word16, 16);
		}
	}
	goto l2425_033A;
}

// 2425:0360: Register word16 fn2425_0360(Stack Eq_2 dwArg02, Stack Eq_10469 wArg06, Stack Eq_2 wArg08, Register out Eq_2 dxOut, Register out Eq_28432 bxOut)
// Called from:
//      fn2425_0405
word16 fn2425_0360(Eq_2 dwArg02, Eq_10469 wArg06, Eq_2 wArg08, union Eq_2 & dxOut, union Eq_28432 & bxOut)
{
	if (seg2864->w0088 != 0x00)
	{
		Eq_22614 v9_15 = seg28BA->tAA80;
		fn216E_009C(seg2863->t0000, seg2863->t0002, &Eq_22613::t0088, seg2864, v9_15, SLICE(v9_15, word16, 16));
	}
	seg2864->w0088 = (word16 *) 0x00;
	Eq_22803 v12_49 = seg28BA->tAA80;
	word16 cx_70 = fn216E_0138(wArg06, wArg08, dwArg02, 0x88, seg2864, v12_49, SLICE(v12_49, word16, 16));
	Eq_2 v16_82 = seg28BA->tAA80;
	Eq_28432 bx_95;
	byte al_151;
	fn216E_01DC(wArg06, wArg08, (word16) dwArg02, SLICE(dwArg02, word16, 16), v16_82, SLICE(v16_82, word16, 16), out al_151, out bx_95);
	seg2863->t0000 = (union Eq_10469 *) wArg06;
	seg2863->t0002 = (union Eq_2 *) wArg08;
	dxOut = wArg08;
	bxOut = bx_95;
	return cx_70;
}

// 2425:0405: Register word32 fn2425_0405(Stack Eq_10469 wArg02, Stack Eq_2 wArg04, Register out ptr16 cxOut, Register out Eq_2 dxOut, Register out Eq_28344 bxOut)
// Called from:
//      fn2425_0286
word32 fn2425_0405(Eq_10469 wArg02, Eq_2 wArg04, ptr16 & cxOut, union Eq_2 & dxOut, union Eq_28344 & bxOut)
{
	struct Eq_28480 Eq_28521::* sp_105 = fp - 2;
	word32 eax_187 = SEQ(eax_16_16, 0x28BA);
	if (seg28BA->t302C != 0x00)
	{
		word32 eax_143 = seg28BA->t302C;
		while (true)
		{
			seg28BA->t3030 = eax_143;
			word16 eax_16_16_190 = SLICE(eax_143, word16, 16);
			dx.u0 = 0x28BA;
			if (seg28BA->t3030 == 0x00)
				break;
			union Eq_10469 * es_bx_26 = seg28BA->t3030;
			bx = (word16) es_bx_26;
			if (*es_bx_26 <= wArg02 && (seg28BA->t3032->*((word16) bx + 4) >= wArg02 && (seg28BA->t3032->*((word16) bx + 2) <= wArg04 && seg28BA->t3032->*((word16) bx + 6) >= wArg04)))
			{
				if (seg28BA->t3032->*((word16) bx + 8) != 0x00)
				{
					if (seg28BA->t3030 != 0x00 && seg28BA->t3032->*((word16) bx + 0x0C) != null)
					{
						word32 eax_69;
						word16 dx_70;
						word16 bx_71;
						word16 cx_156;
						(seg28BA->t3032->*((word16) bx + 0x0C))();
						eax_16_16_190 = SLICE(eax_69, word16, 16);
					}
					struct Eq_28588 Eq_28521::* sp_79 = sp_105 - 2;
					(ss->*sp_79).t0000 = wArg04;
					(ss->*sp_79).tFFFFFFFE = wArg02;
					(ss->*sp_79).tFFFFFFFA = seg28BA->t3030 + 0x08 + 0x00;
					cx = fn2425_0360((ss->*sp_79).tFFFFFFFA, (ss->*sp_79).tFFFFFFFE, (ss->*sp_79).t0000, out dx, out bx);
					sp_105 = (struct Eq_28480 Eq_28521::*) ((char *) &sp_79->t0000 + 2);
				}
				break;
			}
			struct Eq_28558 * es_bx_140 = seg28BA->t3030;
			bx = (word16) es_bx_140;
			eax_143 = es_bx_140->dw001C;
		}
		eax_187 = SEQ(eax_16_16_190, 0x28BA);
		if (seg28BA->t3030 == 0x00)
		{
			struct Eq_28518 Eq_28521::* sp_116 = sp_105 - 2;
			(ss->*sp_116).t0000 = wArg04;
			(ss->*sp_116).tFFFFFFFE = wArg02;
			(ss->*sp_116).wFFFFFFFC = 10340;
			(ss->*sp_116).tFFFFFFFA.u0 = 0x00;
			cx = fn2425_0360((ss->*sp_116).tFFFFFFFA, (ss->*sp_116).tFFFFFFFE, (ss->*sp_116).t0000, out dx, out bx);
			eax_187 = SEQ(eax_16_16_190, ax_125);
		}
	}
	cxOut = cx;
	dxOut = dx;
	bxOut = bx;
	return eax_187;
}

