// ZORTON_2476.c
// Generated by decompiling ZORTON.EXE
// using Reko decompiler version 0.9.2.3.

#include "ZORTON_2476.h"

// 2476:000A: void fn2476_000A()
// Called from:
//      fn1F0F_000F
//      fn2476_0104
void fn2476_000A()
{
	Eq_11683 v5_7 = seg28BA->tAA80;
	Eq_11681 v7_13 = seg28BA->tA8A2;
	struct Eq_28646 * es_235;
	fn216E_0000(0x00, 0x00, v7_13, SLICE(v7_13, word16, 16), v5_7, SLICE(v5_7, word16, 16), out es_235);
	Eq_11683 v9_32 = seg28BA->tAA80;
	Eq_11681 v10_37 = seg28BA->tA89E;
	struct Eq_28660 * es_236;
	fn216E_0000(0x00, 0x96, v10_37, SLICE(v10_37, word16, 16), v9_32, SLICE(v9_32, word16, 16), out es_236);
	Eq_11683 v11_56 = seg28BA->tAA80;
	Eq_11681 v12_61 = seg28BA->tA8A6;
	struct Eq_28674 * es_237;
	fn216E_0000(0x00, 0x0A, v12_61, SLICE(v12_61, word16, 16), v11_56, SLICE(v11_56, word16, 16), out es_237);
	Eq_11683 v13_80 = seg28BA->tAA80;
	Eq_11681 v14_85 = seg28BA->tA8AA;
	struct Eq_28688 * es_238;
	fn216E_0000(0xEE, 0x0A, v14_85, SLICE(v14_85, word16, 16), v13_80, SLICE(v13_80, word16, 16), out es_238);
	Eq_2 v15_104 = seg28BA->tAA80;
	Eq_2 v16_109 = seg28BA->tA8B2;
	byte al_239;
	word16 bx_240;
	fn216E_01DC(0xF9, 11, v16_109, SLICE(v16_109, word16, 16), v15_104, SLICE(v15_104, word16, 16), out al_239, out bx_240);
	Eq_2 v17_125 = seg28BA->tAA80;
	Eq_2 v18_130 = seg28BA->tA8B6;
	byte al_241;
	word16 bx_242;
	fn216E_01DC(0xF7, 114, v18_130, SLICE(v18_130, word16, 16), v17_125, SLICE(v17_125, word16, 16), out al_241, out bx_242);
	Eq_11683 v19_146 = seg28BA->tAA80;
	Eq_11681 v20_151 = seg28BA->tA8BA;
	struct Eq_28734 * es_243;
	fn216E_0000(0x0104, 0x5E, v20_151, SLICE(v20_151, word16, 16), v19_146, SLICE(v19_146, word16, 16), out es_243);
}

// 2476:0104: Register Eq_2 fn2476_0104(Register Eq_2 ds)
// Called from:
//      main
Eq_2 fn2476_0104(Eq_2 ds)
{
	*((word32) ds + 0x0000A556) = (word16) 0040:0049;
	Eq_2 ds_31;
	word16 dx_149;
	word16 bx_150;
	fn0800_21F9(0x40, ds, 0x10, fp - 0x12, fp - 0x12, out dx_149, out bx_150, out ds_31);
	struct Eq_28764 * es_bx_56 = seg28BA->tA8AE;
	word16 bx_151;
	fn2476_0407((byte) (uint16) (seg28BA->tA8B0->*(word16) es_bx_56), (uint16) es_bx_56->b0001, 0x00, SEQ(seg28BA->tA8B0, seg28BA->tA8AE + 0x02), out bx_151);
	fn2476_000A();
	Eq_2 v14_94 = seg28BA->tAA80;
	Eq_2 v15_99 = seg28BA->tA8D2;
	byte al_152;
	word16 bx_153;
	fn216E_01DC(292, 115, v15_99, SLICE(v15_99, word16, 16), v14_94, SLICE(v14_94, word16, 16), out al_152, out bx_153);
	seg28BA->t302A = seg28BA->t302A | 0x01;
	return ds_31;
}

// 2476:0282: Register Eq_2 fn2476_0282(Register Eq_2 ds)
// Called from:
//      fn0CE0_08FC
Eq_2 fn2476_0282(Eq_2 ds)
{
	struct Eq_28821 Eq_28864::* bp_16;
	Eq_2 bx_17;
	Eq_2 cx_18;
	Eq_2 dx_20;
	Eq_2 ds_19;
	Eq_2 ax_15 = fn0800_1D38(ds, 11624, 0x00, out cx_18, out dx_20, out bx_17, out bp_16, out ds_19);
	*((word32) ds_19 + 0x0000884E) = dx_20;
	*((word32) ds_19 + 0x0000884C) = ax_15;
	if (*((word32) ds_19 + 0x0000884C) == 0x00)
	{
		word16 dx_250;
		word16 bx_251;
		fn263F_043F(cx_18, dx_20, bx_17, ds_19, SEQ(ds_19, 0x8857), out dx_250, out bx_251, out ds_19);
	}
	Eq_2 v12_56 = seg28BA->tAA80;
	fn216E_03D8(0x0A, 0x0A, 228, 0x8C, 0x00, v12_56, SLICE(v12_56, word16, 16));
	Eq_22803 v13_77 = seg28BA->tAA80;
	Eq_2 v14_81 = *((word32) ds_19 + 0x0000884C);
	fn216E_0138(0xED, 0x0A, bp_16 - 0x04, v14_81, SLICE(v14_81, word16, 16), v13_77, SLICE(v13_77, word16, 16));
	(ss->*bp_16).wFFFFFFFA = 0xEE;
	(ss->*bp_16).tFFFFFFF8.u0 = 0x52;
	while ((ss->*bp_16).tFFFFFFF8 > 0x0A)
	{
		Eq_23607 v16_113 = seg28BA->tAA80;
		fn216E_04C9((ss->*bp_16).wFFFFFFFA, 0x0A, (ss->*bp_16).tFFFFFFF8, 0x8C, 0x00, 0x00, (word32) *((word32) ds_19 + 0x0000884C) + 4, *((word32) ds_19 + 0x0000884E), 0x53, v16_113, SLICE(v16_113, word16, 16));
		++(ss->*bp_16).wFFFFFFFA;
		--(ss->*bp_16).tFFFFFFF8;
		seg28BA->tA184 = 0x01;
		do
			;
		while (seg28BA->tA184 > 0x00);
	}
	return ds_19;
}

// 2476:0362: Register Eq_2 fn2476_0362(Register Eq_2 ds)
// Called from:
//      fn0CE0_08FC
Eq_2 fn2476_0362(Eq_2 ds)
{
	if (*((word32) ds + 0x0000884C) != 0x00)
	{
		ci16 wLoc04_100 = 0x0135;
		Eq_23600 wLoc06_101 = 11;
		while (wLoc04_100 > 0xEC)
		{
			Eq_23607 v12_22 = seg28BA->tAA80;
			fn216E_04C9(wLoc04_100, 0x0A, wLoc06_101, 0x8C, 0x00, 0x00, (word16) ((word32) ds + 0x0000884C)->u0 + 4, *((word32) ds + 0x0000884E), 0x53, v12_22, SLICE(v12_22, word16, 16));
			seg28BA->tA184 = 0x01;
			--wLoc04_100;
			wLoc06_101 = (word16) wLoc06_101 + 1;
			do
				;
			while (seg28BA->tA184 > 0x01);
		}
		word16 cx_155;
		word16 dx_156;
		word16 bx_157;
		fn0800_1C24(ds, *((word32) ds + 0x0000884E), out cx_155, out dx_156, out bx_157, out ds);
		((word32) ds + 0x0000884C)->u1 = 0x00;
	}
	return ds;
}

// 2476:03E6: Register Eq_2 fn2476_03E6(Register Eq_2 es, Register Eq_2 ds, Register out ptr16 dxOut, Register out ptr16 bxOut, Register out (ptr16 Eq_28996) dsOut)
// Called from:
//      fn263F_03F3
//      fn263F_043F
//      fn263F_04B6
//      fn268D_03E2
Eq_2 fn2476_03E6(Eq_2 es, Eq_2 ds, ptr16 & dxOut, ptr16 & bxOut, struct Eq_28996 & dsOut)
{
	ptr16 bx_27;
	struct Eq_28996 * ds_30;
	ptr16 dx_31;
	Eq_2 cx_28 = fn0800_21F9(es, ds, 0x10, fp - 0x12, fp - 0x12, out dx_31, out bx_27, out ds_30);
	dxOut = dx_31;
	bxOut = bx_27;
	dsOut = ds_30;
	return cx_28;
}

// 2476:0407: Register word16 fn2476_0407(Stack Eq_947 bArg04, Stack Eq_2 wArg06, Stack Eq_2 wArg08, Stack Eq_28773 ptrArg0A, Register out ptr16 bxOut)
// Called from:
//      fn2476_0104
//      fn2476_0495
//      main
//      fn268D_03E2
word16 fn2476_0407(Eq_947 bArg04, Eq_2 wArg06, Eq_2 wArg08, Eq_28773 ptrArg0A, ptr16 & bxOut)
{
	__outb(0x03C8, bArg04);
	word16 wArg06_50 = (word16) (wArg06 *s 0x03);
	do
	{
		ptrArg0A_60 = SEQ(wArg0C_59, wArg0A_52 + 0x01);
		__outb(969, (byte) (int16) ((word32) (word16) (wArg08 *s (uint16) (*ptrArg0A)) / 100));
		word16 v17_40 = wArg06_50 - 0x01;
		word16 wArg0A_52 = (word16) ptrArg0A;
		word16 wArg0C_59 = SLICE(ptrArg0A, word16, 16);
		wArg06_50 = v17_40;
		ptrArg0A = ptrArg0A_60;
	} while (v17_40 != 0x00);
	bxOut = 100;
	return 969;
}

// 2476:043B: void fn2476_043B(Stack Eq_947 bArg04, Stack Eq_2 wArg06, Stack Eq_8368 ptrArg08)
// Called from:
//      fn0CE0_0007
//      fn1ED7_000E
void fn2476_043B(Eq_947 bArg04, Eq_2 wArg06, Eq_8368 ptrArg08)
{
	__outb(0x03C8, bArg04);
	word16 wArg06_38 = (word16) (wArg06 *s 0x03);
	do
	{
		ptrArg08_47 = SEQ(wArg0A_46, wArg08_40 + 0x01);
		__outb(969, *ptrArg08);
		word16 v15_28 = wArg06_38 - 0x01;
		word16 wArg08_40 = (word16) ptrArg08;
		word16 wArg0A_46 = SLICE(ptrArg08, word16, 16);
		wArg06_38 = v15_28;
		ptrArg08 = ptrArg08_47;
	} while (v15_28 != 0x00);
}

// 2476:0495: Register word16 fn2476_0495(Register Eq_2 ds, Register out ptr16 bxOut)
// Called from:
//      fn1D10_155B
word16 fn2476_0495(Eq_2 ds, ptr16 & bxOut)
{
	Eq_29078 ax_14;
	if (*((word32) ds + 0x00008856) != 0x00)
		ax_14 = *((word32) ds + 0x00008854) - *((word32) ds + 0x00008855);
	else
		ax_14.u0 = (int16) *((word32) ds + 0x00008855);
	ptr16 bx_64;
	word16 dx_65 = fn2476_0407((byte) (uint16) *((word32) ds + 0x0000A858), (uint16) *((word32) ds + 0x0000A859), (int16) ((int32) (ax_14 *s 100) / (int16) (*((word32) ds + 0x00008854))), SEQ(ds, 0xA558), out bx_64);
	if (*((word32) ds + 0x00008855) > 0x03)
		*((word32) ds + 0x00008855) += ~0x01;
	else
		*((word32) ds + 0x00008855) = 0x00;
	bxOut = bx_64;
	return dx_65;
}

// 2476:0568: Register word16 fn2476_0568(Register Eq_2 ds, Stack (ptr32 Eq_17297) ptrArg04, Stack Eq_915 wArg08)
// Called from:
//      fn1D10_155B
word16 fn2476_0568(Eq_2 ds, struct Eq_17297 * ptrArg04, Eq_915 wArg08)
{
	word16 wArg04_50 = (word16) ptrArg04;
	word16 wArg06_51 = SLICE(ptrArg04, word16, 16);
	*((word32) ds + 0x0000A858) = ptrArg04->t0000;
	*((word32) ds + 0x0000A859) = ptrArg04->b0001;
	return fn0800_46CD(SEQ(ds, 0xA558), SEQ(wArg06_51, wArg04_50 + 0x02), wArg08 - 0x02);
}

// 2476:05D7: Register word16 fn2476_05D7(Register Eq_2 ds)
// Called from:
//      fn1D10_1153
//      fn1D10_155B
word16 fn2476_05D7(Eq_2 ds)
{
	__outb(0x03C8, *((word32) ds + 0x0000A858));
	word16 dx_10 = 0x03C8;
	int16 wLoc04_33;
	for (wLoc04_33 = 0x00; (uint16) *((word32) ds + 0x0000A859) *s 0x03 > wLoc04_33; ++wLoc04_33)
	{
		__outb(969, 0x00);
		dx_10 = 969;
	}
	return dx_10;
}

// 2476:0601: Register word16 fn2476_0601(Register Eq_2 ds, Register out Eq_17233 bxOut)
// Called from:
//      fn1D10_155B
word16 fn2476_0601(Eq_2 ds, union Eq_17233 & bxOut)
{
	__outb(0x03C8, *((word32) ds + 0x0000A858));
	word16 dx_10 = 0x03C8;
	Eq_17233 wLoc04_34 = 0x00;
	while ((uint16) *((word32) ds + 0x0000A859) *s 0x03 > wLoc04_34)
	{
		__outb(969, ds->*((word16) wLoc04_34 + 0x0000A558));
		bx = wLoc04_34;
		dx_10 = 969;
		wLoc04_34 = (word16) wLoc04_34 + 1;
	}
	bxOut = bx;
	return dx_10;
}

// 2476:0630: Register byte fn2476_0630(Register Eq_2 ds, Stack Eq_19524 wArg04, Stack Eq_2 wArg06, Stack Eq_2 dwArg08, Register out Eq_2 cxOut, Register out ptr16 bxOut)
// Called from:
//      fn226D_00F9
//      fn268D_03E2
byte fn2476_0630(Eq_2 ds, Eq_19524 wArg04, Eq_2 wArg06, Eq_2 dwArg08, union Eq_2 & cxOut, ptr16 & bxOut)
{
	word16 cx_304;
	word16 dx_305;
	word16 bx_306;
	Eq_2 ax_19 = fn0800_3615(ds, dwArg08, 0x8001, wLoc10, out cx_304, out dx_305, out bx_306);
	if (ax_19 == ~0x00)
	{
		word16 dx_316;
		word16 bx_317;
		word16 di_318;
		struct Eq_29252 * ds_319;
		fn263F_03F3(cx, dx, bx, ds, out dx_316, out bx_317, out di_318, out ds_319);
		Eq_2 eax_32 = <invalid>;
		eax_16_16 = SLICE(eax_32, word16, 16);
	}
	word16 cx_307;
	word16 dx_308;
	word16 bx_309;
	fn0800_3C87(ds, ax_19, fp - 0x06, 0x02, out cx_307, out dx_308, out bx_309);
	word16 cx_310;
	word16 dx_311;
	word16 bx_312;
	fn0800_3C87(ds, ax_19, fp - 0x08, 0x02, out cx_310, out dx_311, out bx_312);
	Eq_2 wLoc0C_227 = wArg06;
	ci16 wLoc0A_228 = 0x00;
	Eq_2 dwLoc10_233 = SEQ(0xA000, (word16) wArg04.u0 + wArg06 *s 0x0140);
	while (true)
	{
		word16 wLoc10_236 = (word16) dwLoc10_233;
		word16 wLoc0E_259 = SLICE(dwLoc10_233, word16, 16);
		byte al_194 = (byte) wLoc0A_228;
		if (wLoc0A_228 >= wLoc08)
			break;
		if (wArg04 + wLoc06 <=u 0x0140)
		{
			word16 cx_327;
			word16 dx_328;
			word16 bx_329;
			al_194 = (byte) fn0800_3C87(ds, ax_19, dwLoc10_233, wLoc06, out cx_327, out dx_328, out bx_329);
		}
		else
		{
			word16 cx_321;
			word16 dx_322;
			word16 bx_323;
			fn0800_3C87(ds, ax_19, dwLoc10_233, 0x0140 - wArg04, out cx_321, out dx_322, out bx_323);
			word32 eax_138 = CONVERT(wArg04 + wLoc06 - 0x0140, word16, word32);
			eax_16_16 = SLICE(eax_138, word16, 16);
			word16 cx_324;
			word16 dx_325;
			word16 bx_326;
			al_194 = (byte) fn0800_06AB(ds, ax_19, eax_138, 0x01, out cx_324, out dx_325, out bx_326);
		}
		Eq_2 v25_178 = (word32) wLoc0C_227 + 1;
		wLoc0C_227 = v25_178;
		dwLoc10_233 = SEQ(wLoc0E_259, wLoc10_236 + 0x0140);
		if (v25_178 >= 200)
			break;
		++wLoc0A_228;
	}
	ptr16 bx_200;
	word16 dx_320;
	word32 eax_271 = SEQ(eax_16_16, fn0800_2A93(al_194, ds, ax_19, out dx_320, out bx_200));
	cxOut = ax_19;
	bxOut = bx_200;
	return (byte) fn0800_2A93(al_194, ds, ax_19, out dx_320, out bx_200);
}

// 2476:081F: void fn2476_081F()
// Called from:
//      fn268D_03E2
void fn2476_081F()
{
	do
	{
		word16 wLoc06_117 = 0x00;
		do
			;
		while ((__inb(0x03DA) & 0x08) != 0x00);
		do
			;
		while ((__inb(0x03DA) & 0x08) == 0x00);
		ci16 wLoc04_118 = 0x00;
		while (true)
		{
			Eq_947 bLoc04_122 = (byte) wLoc04_118;
			if (wLoc04_118 >= 0x0100)
				break;
			__outb(0x03C7, bLoc04_122);
			uint16 ax_43 = (uint16) __inb(969);
			uint16 ax_48 = (uint16) __inb(969);
			uint16 ax_53 = (uint16) __inb(969);
			Eq_947 bLoc08_140 = (byte) (ax_43 & 0x3F);
			Eq_947 bLoc0A_144 = (byte) (ax_48 & 0x3F);
			Eq_947 bLoc0C_147 = (byte) (ax_53 & 0x3F);
			if ((ax_43 & 0x3F) != 0x00)
			{
				wLoc06_117 = 0x01;
				bLoc08_140 = (byte) (int16) ((int32) ((ax_43 & 0x3F) *s 0x5A) / 100);
			}
			if ((ax_48 & 0x3F) != 0x00)
			{
				wLoc06_117 = 0x01;
				bLoc0A_144 = (byte) (int16) ((int32) ((ax_48 & 0x3F) *s 0x5A) / 100);
			}
			if ((ax_53 & 0x3F) != 0x00)
			{
				wLoc06_117 = 0x01;
				bLoc0C_147 = (byte) (int16) ((int32) ((ax_53 & 0x3F) *s 0x5A) / 100);
			}
			__outb(0x03C8, bLoc04_122);
			__outb(969, bLoc08_140);
			__outb(969, bLoc0A_144);
			__outb(969, bLoc0C_147);
			++wLoc04_118;
		}
	} while (wLoc06_117 != 0x00);
}

