// ZORTON_0E31.c
// Generated by decompiling ZORTON.EXE
// using Reko decompiler version 0.9.2.3.

#include "ZORTON_0E31.h"

// 0E31:0002: void fn0E31_0002(Register Eq_947 al, Register Eq_2 ds, Stack Eq_2 dwArg04, Stack word16 wArg08, Stack int16 wArg0A, Stack Eq_2 wArg0C, Stack cup16 wArg0E)
// Called from:
//      fn226D_00F9
void fn0E31_0002(Eq_947 al, Eq_2 ds, Eq_2 dwArg04, word16 wArg08, int16 wArg0A, Eq_2 wArg0C, cup16 wArg0E)
{
	fn0800_0894(al, ds, dwArg04);
	Eq_2 bx_28;
	Eq_2 cx_29;
	Eq_2 dx_30;
	Eq_2 ax_31 = fn0800_3615(ds, dwArg04, 0x8100, 0x0180, out cx_29, out dx_30, out bx_28);
	if (ax_31 == ~0x00)
	{
		word16 di_226;
		word16 dx_224;
		word16 bx_225;
		fn263F_03F3(cx_29, dx_30, bx_28, ds, out dx_224, out bx_225, out di_226, out ds);
	}
	fn0800_4655(ds, ax_31, fp + 0x0C, 0x02);
	fn0800_4655(ds, ax_31, fp + 0x0E, 0x02);
	struct Eq_12346 Eq_12333::* sp_106 = fp - 0x12;
	cup16 wLoc0A_191 = 0x00;
	Eq_2 dwLoc08_195 = SEQ(0xA000, wArg0A *s 0x0140 + wArg08);
	while (true)
	{
		word16 wLoc08_197 = (word16) dwLoc08_195;
		word16 wLoc06_207 = SLICE(dwLoc08_195, word16, 16);
		byte al_151 = (byte) wLoc0A_191;
		if (wLoc0A_191 >= wArg0E)
			break;
		struct Eq_12373 Eq_12333::* sp_122 = sp_106 - 2;
		(ss->*sp_122).t0000 = wArg0C;
		(ss->*sp_122).tFFFFFFFC = dwLoc08_195;
		(ss->*sp_122).tFFFFFFFA = ax_31;
		fn0800_4655(ds, (ss->*sp_122).tFFFFFFFA, (ss->*sp_122).tFFFFFFFC, (ss->*sp_122).t0000);
		sp_106 = sp_122 - 0x02;
		++wLoc0A_191;
		dwLoc08_195 = SEQ(wLoc06_207, wLoc08_197 + 0x0140);
	}
	struct Eq_12403 Eq_12333::* sp_149 = sp_106 - 2;
	(ss->*sp_149).t0000 = ax_31;
	word16 dx_227;
	word16 bx_228;
	fn0800_2A93(al_151, ds, (ss->*sp_149).t0000, out dx_227, out bx_228);
}

