// ZORTON_226D.c
// Generated by decompiling ZORTON.EXE
// using Reko decompiler version 0.9.2.3.

#include "ZORTON_226D.h"

// 226D:00F9: Register byte fn226D_00F9(Register Eq_2 ds, Register out ptr16 cxOut, Register out Eq_15330 edxOut, Register out Eq_15331 ebxOut, Register out Eq_15332 bpOut, Register out (ptr16 Eq_15333) dsOut)
// Called from:
//      fn1D10_02AE
//      fn1ED7_000E
//      fn1F0F_000F
//      fn1F0F_057A
//      fn1F0F_0BF7
byte fn226D_00F9(Eq_2 ds, ptr16 & cxOut, union Eq_15330 & edxOut, union Eq_15331 & ebxOut, union Eq_15332 & bpOut, struct Eq_15333 & dsOut)
{
	fn0800_03F4(0x43, SEQ(ds, 33854), SEQ(ss, fp - 0x60));
	__cli();
	word32 ebx_32;
	word32 edx_33;
	word16 cx_853;
	struct Eq_25646 * es_854;
	fn2425_01E8(ds, out cx_853, out edx_33, out ebx_32, out es_854);
	__sti();
	struct Eq_25655 Eq_2::* bp_127 = fp - 2;
	word16 ebx_16_16_821 = SLICE(ebx_32, word16, 16);
	word16 edx_16_16_831 = SLICE(edx_33, word16, 16);
	if (seg28BA->t8586 != *((word32) ds + 33794))
	{
		Eq_23607 v11_45 = seg28BA->tAA80;
		fn216E_04C9(292, 115, 0x1B, 0x23, 0x36, 0x69, seg28BA->tA8AA + 0x04, seg28BA->tA8AC, 0x52, v11_45, SLICE(v11_45, word16, 16));
	}
	Eq_10469 ptrLoc12_815[];
	word32 dwLoc0E_724;
	struct Eq_25669 * ptrLoc1C_810;
	Eq_2 es_104;
	if ((seg28BA->t8586 & 0x02) != 0x00)
	{
		Eq_2 v15_415 = seg28BA->tAA80;
		Eq_2 v16_420 = seg28BA->tA8D2;
		byte al_855;
		word16 bx_856;
		fn216E_01DC(292, 115, v16_420, SLICE(v16_420, word16, 16), v15_415, SLICE(v15_415, word16, 16), out al_855, out bx_856);
		dwLoc0E_724 = seg28BA->tA8EA;
		seg28BA->t8712 = 0x28BA;
		seg28BA->t8710 = 43334;
		*((word32) ds + 0x0000A443) = seg28BA->tA952;
		seg28BA->tA88A = seg28BA->tA892;
		ptrLoc1C_810 = &seg28BA->t3034;
		ptrLoc12_815 = SEQ(ds, 0x8404);
	}
	else if ((seg28BA->t8586 & 0x04) != 0x00)
	{
		Eq_2 v19_376 = seg28BA->tAA80;
		Eq_2 v20_381 = seg28BA->tA8DE;
		word16 bx_858;
		byte al_857;
		fn216E_01DC(0x0125, 0x78, v20_381, SLICE(v20_381, word16, 16), v19_376, SLICE(v19_376, word16, 16), out al_857, out bx_858);
		dwLoc0E_724 = seg28BA->tA8EE;
		seg28BA->t8712 = 0x28BA;
		seg28BA->t8710 = 43342;
		seg28BA->tA88A = seg28BA->tA89A;
		ptrLoc1C_810 = &seg28BA->t3046;
		ptrLoc12_815 = SEQ(ds, 33844);
	}
	else
	{
		if ((seg28BA->t8586 & 0x08) == 0x00)
		{
			es_104.u0 = 0x28BA;
			if ((seg28BA->t8586 & 0x0100) != 0x00)
			{
				es_104.u0 = 0x2862;
				if ((seg2862->t0000 & 0x20) != 0x00)
				{
					es_104.u0 = 0x28BA;
					if (seg28BA->tA18C != 0xFF)
					{
						seg28BA->tA18C != 0x08;
						Eq_2 bx_128;
						Eq_2 cx_129;
						Eq_2 dx_131;
						Eq_2 ds_130;
						Eq_2 ax_126 = fn0800_1D38(ds, 0x0300, 0x00, out cx_129, out dx_131, out bx_128, out bp_127, out ds_130);
						(ss->*bp_127).tFFFFFFFA = dx_131;
						(ss->*bp_127).tFFFFFFF8 = ax_126;
						if ((ax_126 | dx_131) == 0x00)
						{
							word16 dx_866;
							word16 bx_867;
							fn263F_043F(cx_129, dx_131, bx_128, ds_130, SEQ(ds_130, 34030), out dx_866, out bx_867, out ds_130);
						}
						__outb(0x03C7, 0x00);
						(ss->*bp_127).wFFFFFFFC = 0x00;
						Eq_947 al_167 = 0x00;
						while ((ss->*bp_127).wFFFFFFFC < 0x0100)
						{
							Eq_947 al_177 = __inb(969);
							Eq_2 es_bx_180 = (ss->*bp_127).tFFFFFFF8;
							struct Eq_26033 * es_183 = SLICE(es_bx_180, selector, 16);
							*((char *) &(es_183->*(word16) es_bx_180).t0000 + (ss->*bp_127).wFFFFFFFC * 0x03) = (union Eq_947 *) al_177;
							(word32) (ss->*bp_127).tFFFFFFF8 + (ss->*bp_127).wFFFFFFFC *s 0x03 + 0x01 = __inb(969);
							al_167 = __inb(969);
							(word32) (ss->*bp_127).tFFFFFFF8 + (ss->*bp_127).wFFFFFFFC *s 0x03 + 0x02 = al_167;
							++(ss->*bp_127).wFFFFFFFC;
						}
						fn0E31_0002(al_167, ds_130, SEQ(ds_130, 34039), 0x0A, 0x0A, 228, 0x8C);
						word32 ebx_238;
						word16 bp_868;
						struct Eq_26092 * es_869;
						struct Eq_26093 * ds_870;
						edx_16_16_831 = SLICE(fn0CE0_08FC(ds_130, out ebx_238, out bp_868, out es_869, out ds_870), word16, 16);
						Eq_2 sp_234 = <invalid>;
						ss->*((word32) sp_234 - 2) = seg28BA->tAA80;
						(ss->*((word32) sp_234 - 6)).u1 = 0x8C;
						(ss->*((word32) sp_234 - 0x0A)).u1 = 0x00E4000A;
						(ss->*((word32) sp_234 - 0x0C)).u0 = 0x0A;
						fn216E_03D8(ss->*((word32) sp_234 - 0x0C), ss->*((word32) sp_234 - 0x0A), ss->*((word32) sp_234 - 8), ss->*((word32) sp_234 - 6), ss->*((word32) sp_234 - 4), ss->*((word32) sp_234 - 2), ss->*sp_234);
						__outb(0x03C8, 0x00);
						(ss->*bp_127).wFFFFFFFC = 0x00;
						ebx_16_16_821 = SLICE(ebx_238, word16, 16);
						while ((ss->*bp_127).wFFFFFFFC < 0x0300)
						{
							Eq_2 es_bx_270 = (ss->*bp_127).tFFFFFFF8;
							__outb(969, SLICE(es_bx_270, selector, 16)->*((char *) ((word16) es_bx_270) + (ss->*bp_127).wFFFFFFFC));
							++(ss->*bp_127).wFFFFFFFC;
						}
						ss->*sp_234 = ds_130;
						(ss->*((word32) sp_234 - 2)).u0 = 34039;
						(ss->*((word32) sp_234 - 6)).u1 = 0x000A000A;
						word16 cx_871;
						word16 bx_872;
						Eq_947 al_304 = (byte) (uint32) fn2476_0630(ds_130, ss->*((word32) sp_234 - 6), ss->*((word32) sp_234 - 4), ss->*((word32) sp_234 - 2), out cx_871, out bx_872);
						ss->*sp_234 = ds_130;
						(ss->*((word32) sp_234 - 2)).u0 = 34039;
						fn0800_0894(al_304, ds_130, ss->*((word32) sp_234 - 2));
						ss->*((word32) sp_234 - 2) = (ss->*bp_127).tFFFFFFF8;
						word16 cx_873;
						word16 dx_874;
						word16 bx_875;
						fn0800_1C24(ds_130, ss->*sp_234, out cx_873, out dx_874, out bx_875, out ds);
						seg28BA->t8586 = 0x01;
						es_104.u0 = 0x28BA;
					}
				}
			}
			goto l226D_056A;
		}
		Eq_2 v24_333 = seg28BA->tAA80;
		Eq_2 v25_338 = seg28BA->tA8E2;
		byte al_861;
		word16 bx_862;
		fn216E_01DC(0x0128, 115, v25_338, SLICE(v25_338, word16, 16), v24_333, SLICE(v24_333, word16, 16), out al_861, out bx_862);
		dwLoc0E_724 = seg28BA->tA8E6;
		seg28BA->t8712 = 0x28BA;
		seg28BA->t8710 = 43338;
		*((word32) ds + 0x0000A443) = seg28BA->tA956;
		seg28BA->tA88A = seg28BA->tA896;
		ptrLoc1C_810 = &seg28BA->t303D;
		ptrLoc12_815 = SEQ(ds, 33820);
	}
	int16 wLoc14_755 = 0x00;
	while (true)
	{
		Eq_2 wLoc1A_770 = SLICE(ptrLoc1C_810, word16, 16);
		if ((int16) ptrLoc1C_810->b0000 <= wLoc14_755)
			break;
		Eq_2 v26_471 = seg28BA->tAA80;
		struct Eq_25785 * es_485 = SLICE(ptrLoc12_815, selector, 16);
		byte al_859;
		word16 bx_860;
		fn216E_01DC(ptrLoc12_815[wLoc14_755], *((char *) &(es_485->*(word16) ptrLoc12_815).t0000 + ((wLoc14_755 << 0x01) + 0x01) * 0x02), (word16) dwLoc0E_724, SLICE(dwLoc0E_724, word16, 16), v26_471, SLICE(v26_471, word16, 16), out al_859, out bx_860);
		++wLoc14_755;
	}
	if (seg28BA->t8586 == *((word32) ds + 33794))
	{
		es_104 = wLoc1A_770;
		if (ptrLoc1C_810->w0002 == *((word32) ds + 33852))
			goto l226D_056A;
	}
	Eq_23607 v31_524 = seg28BA->tAA80;
	fn216E_04C9(292, 141, 0x1B, 0x09, 0x36, 131, seg28BA->tA8AA + 0x04, seg28BA->tA8AC, 0x52, v31_524, SLICE(v31_524, word16, 16));
	int16 ax_562 = ptrLoc1C_810->w0002;
	*((word32) ds + 33852) = ax_562;
	int16 wLoc14_789 = ax_562;
	word16 wLoc18_790 = 0x0138;
	do
	{
		word16 dx_863;
		fn0800_350E(SEQ(ss, fp - 0x5C), SEQ(seg28BA->tA900, (int16) ((int32) wLoc14_789 % 0x0A) *s 0x3F + seg28BA->tA8FE + 0x04), 0x3F, out dx_863);
		Eq_2 v37_618 = seg28BA->tAA80;
		byte al_864;
		word16 bx_865;
		fn216E_01DC(wLoc18_790 + 0x00, 141, fp - 0x60, ss, v37_618, SLICE(v37_618, word16, 16), out al_864, out bx_865);
		int16 ax_584 = (int16) ((int32) wLoc14_789 / 0x0A);
		wLoc14_789 = ax_584;
		es_104.u0 = 0x28BA;
		wLoc18_790 -= 0x08;
	} while (ax_584 != 0x00);
l226D_056A:
	__cli();
	word16 bx_649;
	ptr16 cx_650;
	struct Eq_15333 * ds_652;
	word16 dx_653;
	word16 eax_16_16_819 = SLICE(fn2425_0286(es_104, ds, out cx_650, out dx_653, out bx_649, out ds_652), word16, 16);
	__sti();
	word16 ax_666 = seg28BA->t8586;
	ds_652->w8402 = ax_666;
	Eq_15332 bp_670 = (ss->*bp_127).t0000;
	cxOut = cx_650;
	edxOut = SEQ(edx_16_16_831, dx_653);
	ebxOut = SEQ(ebx_16_16_821, bx_649);
	bpOut = bp_670;
	dsOut = ds_652;
	return (byte) SEQ(eax_16_16_819, ax_666);
}

// 226D:057F: Register Eq_2 fn226D_057F(Register Eq_2 ds)
// Called from:
//      fn1ED7_000E
//      fn1F0F_000F
//      fn1F0F_0BF7
Eq_2 fn226D_057F(Eq_2 ds)
{
	fn0800_03F4(0x43, SEQ(ds, 0x8481), SEQ(ss, fp - 0x4E));
	__cli();
	word16 cx_209;
	word32 edx_210;
	word32 ebx_211;
	struct Eq_26262 * es_212;
	fn2425_01E8(ds, out cx_209, out edx_210, out ebx_211, out es_212);
	__sti();
	Eq_11683 v9_40 = seg28BA->tAA80;
	Eq_11681 v10_45 = seg28BA->tA8BA;
	struct Eq_26277 * es_213;
	fn216E_0000(0x0104, 0x5E, v10_45, SLICE(v10_45, word16, 16), v9_40, SLICE(v9_40, word16, 16), out es_213);
	uint32 dwLoc0A_182 = seg28BA->tA17E;
	byte bLoc03_183 = 0x25;
	do
	{
		word16 dx_214;
		fn0800_350E(SEQ(ss, fp - 0x4A), SEQ(seg28BA->tA900, seg28BA->tA8FE + ((word16) ((uint32) ((uint64) dwLoc0A_182 % 0x0A)) *s 0x3F + 0x04)), 0x3F, out dx_214);
		Eq_2 v22_119 = seg28BA->tAA80;
		byte al_215;
		word16 bx_216;
		fn216E_01DC((int16) bLoc03_183 + 0x0104, 100, fp - 0x4E, ss, v22_119, SLICE(v22_119, word16, 16), out al_215, out bx_216);
		uint32 eax_84 = (uint32) ((uint64) dwLoc0A_182 /u 0x0A);
		dwLoc0A_182 = eax_84;
		bLoc03_183 += ~0x07;
	} while (eax_84 != 0x00);
	__cli();
	Eq_2 ds_152;
	word16 cx_217;
	word16 dx_218;
	word16 bx_219;
	fn2425_0286(0x28BA, ds, out cx_217, out dx_218, out bx_219, out ds_152);
	__sti();
	return ds_152;
}

// 226D:0656: Register Eq_2 fn226D_0656(Register Eq_2 ds, Stack Eq_2 bArg04)
// Called from:
//      fn1ED7_000E
//      fn1F0F_000F
//      fn1F0F_0BF7
Eq_2 fn226D_0656(Eq_2 ds, Eq_2 bArg04)
{
	seg28BA->tA93A + 0x02 = (segptr32) 0x01;
	if ((int16) bArg04 != 0x00)
	{
		if (bArg04 >= 0x00)
		{
			if (seg28BA->tA182 >= 0x15)
			{
				if (seg28BA->tA182 == 0x15 && bArg04 >= 0x05)
				{
					if (seg28BA->tA183 != 0x00)
						fn209F_08D2(ds, SEQ(ds, 0x8522), 0x01);
					Eq_23607 v38_716 = seg28BA->tAA80;
					fn216E_04C9(0x0101, 0xA3, 0x33, 0x23, 0x0101, 0x0D, seg28BA->tA89E + 0x04, seg28BA->tA8A0, 0x0140, v38_716, SLICE(v38_716, word16, 16));
					Eq_2 v40_752 = seg28BA->tAA80;
					Eq_2 v41_757 = seg28BA->tA8BE;
					word16 bx_1170;
					byte al_1169;
					fn216E_01DC(0x0101, 0xA3, v41_757, SLICE(v41_757, word16, 16), v40_752, SLICE(v40_752, word16, 16), out al_1169, out bx_1170);
					seg28BA->tA182 = 0x19;
				}
			}
			else
			{
				while (seg28BA->tA182 < 0x15)
				{
					--bArg04;
					if (bArg04 == 0x00)
						return 0x28BA;
					if (seg28BA->tA183 != 0x00)
						fn209F_08D2(ds, SEQ(ds, 34073), 0x01);
					fn226D_0C2F(SEQ(CONVERT(SEQ(ds, 33988)[CONVERT(Mem637[28BA:A182:byte], byte, int16) * 2], byte, int16) + (CONVERT(SEQ(ds, 33989)[CONVERT(Mem650[28BA:A182:byte], byte, int16) * 2], byte, int16) + 0xA3) *s 0x0140 + 0x0102, 0xA000), ~0x09);
					seg28BA->tA184 = 0x03;
					do
						;
					while (seg28BA->tA184 > 0x00);
					seg28BA->tA182 = seg28BA->tA182 + 0x01;
				}
			}
		}
		else if (seg28BA->tA182 != 0x19)
		{
			int16 wLoc04_956 = (int16) seg28BA->tA182 - 0x01;
			while ((int16) seg28BA->tA182 + ~0x05 < wLoc04_956 && wLoc04_956 >= 0x00)
			{
				if (seg28BA->tA183 != 0x00)
					fn209F_08D2(ds, SEQ(ds, 0x850E), 0x01);
				Eq_2 v36_531 = seg28BA->tAA80;
				Eq_2 v37_538 = seg28BA->tA93A;
				byte al_1167;
				word16 bx_1168;
				fn216E_01DC(CONVERT(SEQ(ds, 33988)[wLoc04_956 * 0x02], byte, int16) + 0x0101, CONVERT(SEQ(ds, 33989)[wLoc04_956 * 0x02], byte, int16) + 0xA3, v37_538, SLICE(v37_538, word16, 16), v36_531, SLICE(v36_531, word16, 16), out al_1167, out bx_1168);
				if (seg28BA->tA183 != 0x00)
					fn209F_08D2(ds, SEQ(ds, 0x850E), 0x01);
				--wLoc04_956;
			}
			seg28BA->tA182 = seg28BA->tA182 + ~0x04;
			if (seg28BA->tA182 < 0x00)
				seg28BA->tA182 = 0x00;
		}
		else
		{
			if (seg28BA->tA183 != 0x00)
				fn209F_08D2(ds, SEQ(ds, 0x8504), 0x00);
			Eq_23607 v20_219 = seg28BA->tAA80;
			fn216E_04C9(0x0101, 0xA3, 0x33, 0x23, 0x0101, 0x0D, seg28BA->tA89E + 0x04, seg28BA->tA8A0, 0x0140, v20_219, SLICE(v20_219, word16, 16));
			Eq_2 v22_255 = seg28BA->tAA80;
			Eq_2 v23_260 = seg28BA->tA8C2;
			word16 bx_1160;
			byte al_1159;
			fn216E_01DC(0x0107, 0xA5, v23_260, SLICE(v23_260, word16, 16), v22_255, SLICE(v22_255, word16, 16), out al_1159, out bx_1160);
			seg28BA->tA184 = 0x04;
			do
				;
			while (seg28BA->tA184 > 0x00);
			Eq_23607 v24_284 = seg28BA->tAA80;
			fn216E_04C9(0x0101, 0xA3, 0x33, 0x23, 0x0101, 0x0D, seg28BA->tA89E + 0x04, seg28BA->tA8A0, 0x0140, v24_284, SLICE(v24_284, word16, 16));
			Eq_2 v26_320 = seg28BA->tAA80;
			Eq_2 v27_325 = seg28BA->tA8C6;
			byte al_1161;
			word16 bx_1162;
			fn216E_01DC(0x0107, 166, v27_325, SLICE(v27_325, word16, 16), v26_320, SLICE(v26_320, word16, 16), out al_1161, out bx_1162);
			seg28BA->tA184 = 0x04;
			do
				;
			while (seg28BA->tA184 > 0x00);
			Eq_23607 v28_349 = seg28BA->tAA80;
			fn216E_04C9(0x0101, 0xA3, 0x33, 0x23, 0x0101, 0x0D, seg28BA->tA89E + 0x04, seg28BA->tA8A0, 0x0140, v28_349, SLICE(v28_349, word16, 16));
			Eq_2 v30_385 = seg28BA->tAA80;
			Eq_2 v31_390 = seg28BA->tA8CA;
			word16 bx_1164;
			byte al_1163;
			fn216E_01DC(0x0107, 0xAA, v31_390, SLICE(v31_390, word16, 16), v30_385, SLICE(v30_385, word16, 16), out al_1163, out bx_1164);
			seg28BA->tA184 = 0x04;
			do
				;
			while (seg28BA->tA184 > 0x00);
			Eq_23607 v32_414 = seg28BA->tAA80;
			fn216E_04C9(0x0101, 0xA3, 0x33, 0x23, 0x0101, 0x0D, seg28BA->tA89E + 0x04, seg28BA->tA8A0, 0x0140, v32_414, SLICE(v32_414, word16, 16));
			Eq_2 v34_450 = seg28BA->tAA80;
			Eq_2 v35_455 = seg28BA->tA8CE;
			byte al_1165;
			word16 bx_1166;
			fn216E_01DC(0x0107, 0xAD, v35_455, SLICE(v35_455, word16, 16), v34_450, SLICE(v34_450, word16, 16), out al_1165, out bx_1166);
			seg28BA->tA182 = 0x15;
		}
	}
	else if (seg28BA->tA182 == 0x19)
	{
		Eq_23607 v14_135 = seg28BA->tAA80;
		fn216E_04C9(0x0101, 0xA3, 0x33, 0x23, 0x0101, 0x0D, seg28BA->tA89E + 0x04, seg28BA->tA8A0, 0x0140, v14_135, SLICE(v14_135, word16, 16));
		Eq_2 v16_169 = seg28BA->tAA80;
		Eq_2 v17_174 = seg28BA->tA8BE;
		byte al_1157;
		word16 bx_1158;
		fn216E_01DC(0x0101, 0xA3, v17_174, SLICE(v17_174, word16, 16), v16_169, SLICE(v16_169, word16, 16), out al_1157, out bx_1158);
	}
	else
	{
		Eq_23607 v44_28 = seg28BA->tAA80;
		fn216E_04C9(0x0101, 0xA3, 0x33, 0x23, 0x0101, 0x0D, seg28BA->tA89E + 0x04, seg28BA->tA8A0, 0x0140, v44_28, SLICE(v44_28, word16, 16));
		Eq_2 v46_62 = seg28BA->tAA80;
		Eq_2 v47_67 = seg28BA->tA8CE;
		byte al_1155;
		word16 bx_1156;
		fn216E_01DC(0x0107, 0xAD, v47_67, SLICE(v47_67, word16, 16), v46_62, SLICE(v46_62, word16, 16), out al_1155, out bx_1156);
		int16 wLoc04_820 = 0x14;
		while ((int16) seg28BA->tA182 - 0x01 < wLoc04_820 && wLoc04_820 >= 0x00)
		{
			Eq_2 v50_96 = seg28BA->tAA80;
			Eq_2 v51_102 = seg28BA->tA93A;
			word16 bx_1172;
			byte al_1171;
			fn216E_01DC(CONVERT(SEQ(ds, 33988)[wLoc04_820 * 0x02], byte, int16) + 0x0101, CONVERT(SEQ(ds, 33989)[wLoc04_820 * 0x02], byte, int16) + 0xA3, v51_102, SLICE(v51_102, word16, 16), v50_96, SLICE(v50_96, word16, 16), out al_1171, out bx_1172);
			--wLoc04_820;
		}
	}
	return 0x28BA;
}

// 226D:0BC6: Register word32 fn226D_0BC6(Register Eq_2 ds, Stack Eq_2 dwArg04, Stack Eq_17501 bArg08, Register out ptr16 cxOut, Register out Eq_17503 edxOut, Register out Eq_17504 ebxOut, Register out Eq_2 dsOut)
// Called from:
//      fn1D10_155B
word32 fn226D_0BC6(Eq_2 ds, Eq_2 dwArg04, Eq_17501 bArg08, ptr16 & cxOut, union Eq_17503 & edxOut, union Eq_17504 & ebxOut, union Eq_2 & dsOut)
{
	word16 ebx_16_16_122 = SLICE(ebx, word16, 16);
	if (dwArg04 != 0x00)
	{
		ebx = SEQ(ebx_16_16_122, (word16) dwArg04);
		if (*((word32) dwArg04 + 0x0C) != 0x00)
		{
			__cli();
			word32 ebx_21;
			word32 edx_22;
			word16 cx_151;
			struct Eq_26874 * es_152;
			fn2425_01E8(ds, out cx_151, out edx_22, out ebx_21, out es_152);
			__sti();
			word16 ebx_16_16_125 = SLICE(ebx_21, word16, 16);
			word16 edx_16_16_130 = SLICE(edx_22, word16, 16);
			Eq_2 es_28 = SLICE(dwArg04, selector, 16);
			Eq_2 eax_30 = *((word32) dwArg04 + 0x0C);
			while (eax_30 != 0x00)
			{
				fn216E_0584(*((word32) eax_30 + 4), *eax_30, *((word32) eax_30 + 6) - *((word32) eax_30 + 4), *((word32) eax_30 + 2) - *eax_30, (byte) wArg08);
				es_28 = SLICE(eax_30, selector, 16);
				eax_30 = *((word32) eax_30 + 8);
			}
			__cli();
			word16 bx_75;
			word16 dx_79;
			eax = fn2425_0286(es_28, ds, out cx, out dx_79, out bx_75, out ds);
			__sti();
			ebx = SEQ(ebx_16_16_125, bx_75);
			edx = SEQ(edx_16_16_130, dx_79);
		}
	}
	cxOut = cx;
	edxOut = edx;
	ebxOut = ebx;
	dsOut = ds;
	return eax;
}

// 226D:0C2F: void fn226D_0C2F(Stack (ptr32 byte) dwArg04, Stack byte bArg08)
// Called from:
//      fn226D_0656
void fn226D_0C2F(byte * dwArg04, byte bArg08)
{
	*dwArg04 = bArg08;
}

