// ZORTON_1744.c
// Generated by decompiling ZORTON.EXE
// using Reko decompiler version 0.9.2.3.

#include "ZORTON_1744.h"

// 1744:000A: Register Eq_13936 fn1744_000A(Register Eq_2 ds, Register out ptr16 dxOut, Register out Eq_9976 bpOut, Register out (ptr16 Eq_9977) dsOut)
// Called from:
//      fn0CE0_08FC
Eq_13936 fn1744_000A(Eq_2 ds, ptr16 & dxOut, union Eq_9976 & bpOut, struct Eq_9977 & dsOut)
{
	struct Eq_13937 Eq_13950::* bp_14;
	struct Eq_9977 * ds_17;
	ptr16 dx_18;
	struct Eq_13940 * es_78;
	Eq_13936 ax_13 = fn0800_07B4(ds, 0x52, out dx_18, out bp_14, out es_78, out ds_17);
	(ss->*bp_14).ptrFFFFFFFE = dx_18;
	(ss->*bp_14).tFFFFFFFC = ax_13;
	if ((ss->*bp_14).tFFFFFFFC != 0x00)
	{
		Eq_13936 es_bx_32 = (ss->*bp_14).tFFFFFFFC;
		*((word32) es_bx_32 + 4) = 0x00;
		*es_bx_32 = 0x00;
		*((word32) es_bx_32 + 8) = 0x00;
		((word32) es_bx_32 + 16)->u0 = 0x00;
		word32 eax_42 = (ss->*bp_14).dw0006;
		*((word32) es_bx_32 + 0x0C) = eax_42;
		*((word32) es_bx_32 + 8) = 0x00;
	}
	Eq_9976 bp_51 = (ss->*bp_14).t0000;
	dxOut = (ss->*bp_14).ptrFFFFFFFE;
	bpOut = bp_51;
	dsOut = ds_17;
	return (ss->*bp_14).tFFFFFFFC;
}

// 1744:005B: void fn1744_005B(Stack Eq_2 ptrArg04, Stack Eq_2 ptrArg08)
// Called from:
//      fn0CE0_08FC
void fn1744_005B(Eq_2 ptrArg04, Eq_2 ptrArg08)
{
	if (*ptrArg08 == 0x00)
	{
		*ptrArg08 = ptrArg04;
		while (*((word32) ptrArg04 + 36) != 0x00)
			ptrArg04 = *((word32) ptrArg04 + 36);
		*((word32) ptrArg08 + 4) = ptrArg04;
	}
	else
	{
		Eq_2 dwLoc06_147 = *ptrArg08;
		byte bLoc07_148 = 0x00;
		do
		{
			word16 wArg06_156 = SLICE(ptrArg04, word16, 16);
			Eq_2 wArg04_157 = (word16) ptrArg04;
			if (*((word32) dwLoc06_147 + 8) > *((word32) ptrArg04 + 8))
			{
				*((word32) ptrArg04 + 40) = *((word32) dwLoc06_147 + 40);
				*((word32) ptrArg04 + 36) = dwLoc06_147;
				if (*((word32) dwLoc06_147 + 40) == 0x00)
					*ptrArg08 = ptrArg04;
				else
				{
					Eq_2 es_bx_86 = *((word32) dwLoc06_147 + 40);
					*((word32) es_bx_86 + 38) = wArg06_156;
					*((word32) es_bx_86 + 36) = wArg04_157;
				}
				*((word32) dwLoc06_147 + 40) = ptrArg04;
				goto l1744_015F;
			}
			if (*((word32) dwLoc06_147 + 36) != 0x00)
				dwLoc06_147 = *((word32) dwLoc06_147 + 36);
			else
			{
				*((word32) ptrArg04 + 40) = dwLoc06_147;
				*((word32) dwLoc06_147 + 36) = ptrArg04;
				while (*((word32) ptrArg04 + 36) != 0x00)
					ptrArg04 = *((word32) ptrArg04 + 36);
				*((word32) ptrArg08 + 4) = ptrArg04;
l1744_015F:
				bLoc07_148 = 0x01;
			}
		} while ((uint16) bLoc07_148 == 0x00);
	}
}

// 1744:044D: void fn1744_044D(Stack Eq_2 ptrArg04)
// Called from:
//      fn0CE0_0170
//      fn0CE0_023E
//      fn0CE0_030C
//      fn0CE0_03D4
//      fn0CE0_08FC
void fn1744_044D(Eq_2 ptrArg04)
{
	if (*((word32) ptrArg04 + 16) != 0x00)
		fn16CC_02B2(ptrArg04);
	Eq_2 eax_137 = *ptrArg04;
	while (eax_137 != 0x00)
	{
		if ((*((word32) eax_137 + 26) & 0x18) == 0x00)
		{
			if (*((word32) eax_137 + 48) != 0x00)
			{
				Eq_2 eax_53 = *((word32) eax_137 + 48);
				while (eax_53 != 0x00)
				{
					fn16CC_001C(eax_53, (word16) ptrArg04, SLICE(ptrArg04, word16, 16));
					eax_53 = *((word32) eax_53 + 36);
				}
			}
			fn16CC_001C(eax_137, (word16) ptrArg04, SLICE(ptrArg04, word16, 16));
			if (*((word32) eax_137 + 44) != 0x00)
			{
				Eq_2 eax_104 = *((word32) eax_137 + 48);
				while (eax_104 != 0x00)
				{
					fn16CC_001C(eax_104, (word16) ptrArg04, SLICE(ptrArg04, word16, 16));
					eax_104 = *((word32) eax_104 + 36);
				}
			}
		}
		eax_137 = *((word32) eax_137 + 36);
	}
}

// 1744:0972: Register word16 fn1744_0972(Register Eq_2 ds, Register out Eq_2 dxOut, Register out Eq_10108 bpOut, Register out Eq_2 dsOut)
// Called from:
//      fn0CE0_08FC
word16 fn1744_0972(Eq_2 ds, union Eq_2 & dxOut, union Eq_10108 & bpOut, union Eq_2 & dsOut)
{
	uint32 eax_183;
	Eq_2 dx_141;
	Eq_2 dx_18;
	word16 bx_213;
	word16 cx_212;
	struct Eq_14169 Eq_14181::* bp_107;
	Eq_2 ds_17;
	Eq_2 ax_13 = fn0800_1D38(ds, 0x38, 0x00, out cx_212, out dx_18, out bx_213, out bp_107, out ds_17);
	(ss->*bp_107).tFFFFFFFE = dx_18;
	(ss->*bp_107).tFFFFFFFC = ax_13;
	if ((ss->*bp_107).tFFFFFFFC == 0x00)
	{
		dx_141.u0 = 0x00;
		eax_183 = SEQ(eax_16_16, 0x00);
	}
	else
	{
		if ((ss->*bp_107).t0012 != 0x00 && (ss->*bp_107).t0014 != 0x00)
		{
			int32 eax_45 = (int32) ((word16) ((ss->*bp_107).t0014 *s (ss->*bp_107).t0012) + 0x04);
			word16 dx_53;
			word16 bx_215;
			word16 cx_214;
			Eq_2 ax_48 = fn0800_1D38(ds_17, (word16) eax_45, SLICE(eax_45, word16, 16), out cx_214, out dx_53, out bx_215, out bp_107, out ds_17);
			Eq_2 es_bx_60 = (ss->*bp_107).tFFFFFFFC;
			*((word32) es_bx_60 + 20) = dx_53;
			*((word32) es_bx_60 + 18) = ax_48;
			if (*((word32) es_bx_60 + 18) == 0x00)
			{
				Eq_2 ds_72;
				Eq_2 dx_73;
				Eq_2 bx_75;
				Eq_2 cx_77;
				fn0800_1C24(ds_17, (ss->*bp_107).tFFFFFFFE, out cx_77, out dx_73, out bx_75, out ds_72);
				word16 bx_217;
				word16 dx_216;
				fn263F_043F(cx_77, dx_73, bx_75, ds_72, SEQ(ds_72, 0x23B7), out dx_216, out bx_217, out ds_17);
			}
		}
		else
			((word32) (ss->*bp_107).tFFFFFFFC + 18)->u0 = 0x00;
		Eq_2 es_bx_109 = (ss->*bp_107).tFFFFFFFC;
		((word32) es_bx_109 + 2)->u0 = 0x00;
		*es_bx_109 = 0x00;
		*((word32) es_bx_109 + 4) = (ss->*bp_107).w0006;
		*((word32) es_bx_109 + 6) = (ss->*bp_107).t0008;
		*((word32) es_bx_109 + 8) = (ss->*bp_107).t000A;
		*((word32) es_bx_109 + 0x0A) = (ss->*bp_107).w000C;
		*((word32) es_bx_109 + 0x0C) = (ss->*bp_107).w000E;
		*((word32) es_bx_109 + 0x0E) = 0x00;
		*((word32) es_bx_109 + 22) = 0x00;
		*((word32) es_bx_109 + 26) = (ss->*bp_107).w0010;
		*((word32) es_bx_109 + 28) = (ss->*bp_107).t0012;
		*((word32) es_bx_109 + 30) = (ss->*bp_107).t0014;
		*((word32) es_bx_109 + 40) = 0x00;
		*((word32) es_bx_109 + 36) = 0x00;
		*((word32) es_bx_109 + 48) = 0x00;
		*((word32) es_bx_109 + 44) = 0x00;
		dx_141 = (ss->*bp_107).tFFFFFFFE;
		eax_183 = (uint32) (ss->*bp_107).tFFFFFFFC;
	}
	Eq_10108 bp_151 = (ss->*bp_107).t0000;
	dxOut = dx_141;
	bpOut = bp_151;
	dsOut = ds_17;
	return (word16) eax_183;
}

// 1744:0A6F: Register Eq_2 fn1744_0A6F(Register Eq_2 ds, Stack Eq_2 dwArg04)
// Called from:
//      fn0CE0_08FC
Eq_2 fn1744_0A6F(Eq_2 ds, Eq_2 dwArg04)
{
	if (dwArg04 != 0x00)
	{
		if (*((word32) dwArg04 + 18) != 0x00)
		{
			word16 cx_93;
			word16 dx_94;
			word16 bx_95;
			fn0800_1C24(ds, *((word32) dwArg04 + 20), out cx_93, out dx_94, out bx_95, out ds);
		}
		word16 cx_90;
		word16 dx_91;
		word16 bx_92;
		fn0800_1C24(ds, SLICE(dwArg04, word16, 16), out cx_90, out dx_91, out bx_92, out ds);
	}
	return ds;
}

