// ZORTON_1197.c
// Generated by decompiling ZORTON.EXE
// using Reko decompiler version 0.9.2.3.

#include "ZORTON_1197.h"

// 1197:09AC: void fn1197_09AC(Register uint16 ax, Register Eq_2 ds)
// Called from:
//      fn268D_0282
void fn1197_09AC(uint16 ax, Eq_2 ds)
{
	fn0800_10B1(ds, null);
	fn0800_082E(ds, ax);
}

