// ZORTON_1D10.c
// Generated by decompiling ZORTON.EXE
// using Reko decompiler version 0.9.2.3.

#include "ZORTON_1D10.h"

// 1D10:02AE: Register word16 fn1D10_02AE(Register Eq_11798 ebx, Register Eq_2 ds, Stack Eq_2 dwArg04, Register out Eq_2 dxOut, Register out Eq_11798 ebxOut, Register out Eq_11810 bpOut, Register out (ptr16 Eq_11811) esOut, Register out Eq_2 dsOut)
// Called from:
//      fn0CE0_08FC
//      fn1ED7_000E
//      fn1F0F_000F
//      fn1F0F_0BF7
word16 fn1D10_02AE(Eq_11798 ebx, Eq_2 ds, Eq_2 dwArg04, union Eq_2 & dxOut, union Eq_11798 & ebxOut, union Eq_11810 & bpOut, struct Eq_11811 & esOut, union Eq_2 & dsOut)
{
	word16 ebx_16_16 = SLICE(ebx, word16, 16);
	word32 eax_1022;
	((word32) ds + 31898)->u0 = 0x00;
	((word32) ds + 0x00007C98)->u0 = 0x00;
	Eq_11810 bp_254 = fp - 2;
	Eq_11798 ebx_1035 = ebx;
	if (dwArg04 == 0x00)
		eax_1022 = SEQ(eax_16_16, 0x00);
	else
	{
		fn1D10_1A16(ds);
		Eq_2 ax_26 = *((word32) dwArg04 + 4);
		seg28BA->tA41A = ax_26;
		seg28BA->tA175 = (word32) ax_26;
		seg28BA->tA179 = dwArg04;
		seg28BA->tA172 = 0x00;
		seg28BA->t8854 = 0x00;
		fn1ED0_0009(ds, dwArg04, out ds);
		word16 edx_16_16_263 = SLICE(dwArg04, word16, 16);
		do
		{
			ds_1122 = ds;
			cui16 dx_67;
			word16 cx_1107;
			word16 bx_1108;
		} while (((word16) (uint32) fn2331_0118(ds_1122, out cx_1107, out dx_67, out bx_1108, out ds) | dx_67) != 0x00);
		word16 dx_1109;
		struct Eq_14656 * es_1111;
		word16 bx_1110;
		Eq_2 cx_755 = fn209F_02A7(ds, out dx_1109, out bx_1110, out es_1111);
		*((word32) ds + 0x0000A38A) = *((word32) dwArg04 + 6);
		*((word32) ds + 41868) = *((word32) dwArg04 + 4);
		seg28BA->tA184 = 0x00;
		while (seg28BA->tA183 != 0x00)
		{
			struct Eq_14697 * es_bx_108 = seg28BA->tA423;
			Eq_2 bx_110 = (word16) es_bx_108;
			Eq_14691 ebx_751 = SEQ(ebx_16_16, bx_110);
			if (es_bx_108->w000C >= 882 || (word32) (*((word32) ds + 0x0000A38A)) <= seg28BA->tA175)
				break;
			int32 eax_728 = (word32) seg28BA->tA41A;
			word16 eax_16_16_754 = SLICE(eax_728, word16, 16);
			Eq_14721 edx_753 = SEQ(edx_16_16_263, 0x28BA);
			if (eax_728 >= seg28BA->tA175)
			{
				word32 ebx_757;
				fn1D10_155B(eax_16_16_754, edx_753, ebx_751, ds, dwArg04, seg28BA->tA18A, SEQ(ds, 0x7C98), SEQ(ds, 31898), out cx_755, out edx_753, out ebx_757, out ds);
				bx_110 = (word16) ebx_757;
				ebx_16_16 = SLICE(ebx_757, word16, 16);
			}
			Eq_2 dx_814 = (word16) edx_753;
			edx_16_16_263 = SLICE(edx_753, word16, 16);
			if (*((word32) ds + 0x00007C98) != 0x00)
			{
				word16 dx_1114;
				word16 bx_1115;
				*((word32) ds + 0x00007C98) = (word16) fn209F_0516(ds, seg28BA->tA18A, *((word32) ds + 0x00007C98), out cx_755, out dx_1114, out bx_1115);
			}
			else if (*((word32) ds + 31898) != 0x00)
			{
				word16 dx_1116;
				word16 bx_1117;
				*((word32) ds + 31898) = fn1D10_12D4(cx_755, dx_814, bx_110, ds, seg28BA->tA18A, *((word32) ds + 31898), out cx_755, out dx_1116, out bx_1117);
			}
			else
			{
				word32 ebx_795;
				word32 edx_796;
				fn1D10_1368(cx_755, edx_753, ds, seg28BA->tA18A, SEQ(ds, 0x7C98), SEQ(ds, 31898), out cx_755, out edx_796, out ebx_795);
				ebx_16_16 = SLICE(ebx_795, word16, 16);
				edx_16_16_263 = SLICE(edx_796, word16, 16);
			}
		}
		word16 bx_122;
		Eq_2 cx_123;
		fn209F_049A(ds, out cx_123, out bx_122);
		Eq_14691 ebx_260 = SEQ(ebx_16_16, bx_122);
		if (seg28BA->tA173 != 0x00)
		{
			word16 bx_143;
			word16 dx_1112;
			fn209F_06D8(ds, seg28BA->tA88A, out cx_123, out dx_1112, out bx_143);
			seg28BA->tA173 = 0x00;
			ebx_260 = SEQ(ebx_16_16, bx_143);
		}
		word16 ebx_16_16_881 = SLICE(ebx_260, word16, 16);
		if (seg28BA->tA174 != 0x00)
		{
			word16 bx_170;
			word16 dx_1113;
			fn209F_06D8(ds, seg28BA->tA88E, out cx_123, out dx_1113, out bx_170);
			seg28BA->tA174 = 0x00;
			ebx_260 = SEQ(ebx_16_16_881, bx_170);
		}
		seg28BA->t8277 = 0x00;
		Eq_2 sp_233 = fp - 0x0A;
		Eq_947 al_188 = ~0x45;
		while (true)
		{
			Eq_2 bx_325 = (word16) ebx_260;
			word16 ebx_16_16_388 = SLICE(ebx_260, word16, 16);
			if (fn0800_2390(al_188, ds) != 0x00)
				fn0800_20A6(ds);
			if ((uint16) seg28BA->tA183 == 0x00 && seg28BA->tA184 < 0x01)
				seg28BA->tA41A = seg28BA->tA41A + 0x02;
			int32 eax_226 = (word32) seg28BA->tA41A;
			word16 eax_16_16_1026 = SLICE(eax_226, word16, 16);
			Eq_14721 edx_264 = SEQ(edx_16_16_263, 0x28BA);
			if (eax_226 > seg28BA->tA175)
			{
				struct Eq_14919 Eq_14628::* sp_234 = sp_233 - 2;
				(ss->*sp_234).t0000 = ds;
				(ss->*sp_234).tFFFFFFFE.u0 = 31898;
				(ss->*sp_234).tFFFFFFFC = ds;
				(ss->*sp_234).tFFFFFFFA.u0 = 0x7C98;
				(ss->*sp_234).tFFFFFFF8 = seg28BA->tA18A;
				(ss->*sp_234).tFFFFFFF4 = ss->*((word16) bp_254 + 6);
				bx_325 = (word16) ebx_268;
				ebx_16_16_388 = SLICE(ebx_268, word16, 16);
				word32 ebx_268;
				eax_16_16_1026 = SLICE(fn1D10_155B(eax_16_16_1026, edx_264, ebx_260, ds, (ss->*sp_234).tFFFFFFF4, (ss->*sp_234).tFFFFFFF8, (ss->*sp_234).tFFFFFFFA, (ss->*sp_234).tFFFFFFFE, out cx_123, out edx_264, out ebx_268, out ds), word16, 16);
			}
			Eq_14691 ebx_1101;
			Eq_2 cx_306;
			Eq_14721 edx_309;
			Eq_2 dx_328 = (word16) edx_264;
			word16 edx_16_16_394 = SLICE(edx_264, word16, 16);
			if (*((word32) ds + 0x00007C98) != 0x00)
			{
				struct Eq_14975 Eq_14628::* sp_342 = sp_233 - 2;
				(ss->*sp_342).t0000 = *((word32) ds + 0x00007C98);
				(ss->*sp_342).tFFFFFFFE = seg28BA->tA18A;
				word16 bx_349;
				word16 dx_351;
				word32 eax_352 = fn209F_0516(ds, (ss->*sp_342).tFFFFFFFE, (ss->*sp_342).t0000, out cx_306, out dx_351, out bx_349);
				*((word32) ds + 0x00007C98) = (word16) eax_352;
				eax_16_16_1026 = SLICE(eax_352, word16, 16);
				ebx_1101 = SEQ(ebx_16_16_388, bx_349);
				edx_309 = SEQ(edx_16_16_394, dx_351);
			}
			else if (*((word32) ds + 31898) != 0x00)
			{
				struct Eq_15111 Eq_14628::* sp_318 = sp_233 - 2;
				(ss->*sp_318).t0000 = *((word32) ds + 31898);
				(ss->*sp_318).tFFFFFFFE = seg28BA->tA18A;
				word16 bx_330;
				word16 dx_332;
				*((word32) ds + 31898) = fn1D10_12D4(cx_123, dx_328, bx_325, ds, (ss->*sp_318).tFFFFFFFE, (ss->*sp_318).t0000, out cx_306, out dx_332, out bx_330);
				ebx_1101 = SEQ(ebx_16_16_388, bx_330);
				edx_309 = SEQ(edx_16_16_394, dx_332);
			}
			else
			{
				struct Eq_15074 Eq_14628::* sp_287 = sp_233 - 2;
				(ss->*sp_287).t0000 = ds;
				(ss->*sp_287).tFFFFFFFE.u0 = 31898;
				(ss->*sp_287).tFFFFFFFC = ds;
				(ss->*sp_287).tFFFFFFFA.u0 = 0x7C98;
				(ss->*sp_287).tFFFFFFF8 = seg28BA->tA18A;
				eax_16_16_1026 = SLICE(fn1D10_1368(cx_123, edx_264, ds, (ss->*sp_287).tFFFFFFF8, (ss->*sp_287).tFFFFFFFA, (ss->*sp_287).tFFFFFFFE, out cx_306, out edx_309, out ebx_1101), word16, 16);
			}
			edx_16_16_263 = SLICE(edx_309, word16, 16);
			Eq_2 dx_424 = (word16) edx_309;
			if (*((word32) ds + 0x0000A38A) <= *((word32) ds + 41868))
			{
				struct Eq_15024 Eq_14628::* sp_368 = sp_233 - 2;
				(ss->*sp_368).t0000 = ds;
				(ss->*sp_368).tFFFFFFFE.u0 = 31898;
				(ss->*sp_368).tFFFFFFFC = ds;
				(ss->*sp_368).tFFFFFFFA.u0 = 0x7C98;
				(ss->*sp_368).tFFFFFFF8 = seg28BA->tA18A;
				(ss->*sp_368).tFFFFFFF4 = ss->*((word16) bp_254 + 6);
				edx_16_16_263 = SLICE(edx_405, word16, 16);
				dx_424 = (word16) edx_405;
				word32 edx_405;
				eax_16_16_1026 = SLICE(fn1D10_155B(eax_16_16_1026, edx_309, ebx_1101, ds, (ss->*sp_368).tFFFFFFF4, (ss->*sp_368).tFFFFFFF8, (ss->*sp_368).tFFFFFFFA, (ss->*sp_368).tFFFFFFFE, out cx_306, out edx_405, out ebx_1101, out ds), word16, 16);
			}
			word16 ebx_16_16_885 = SLICE(ebx_1101, word16, 16);
			Eq_14691 ebx_610 = ebx_1101;
			if (seg28BA->tA41A >= *((word32) ds + 0x0000A38A))
				break;
			int32 eax_423 = (word32) *((word32) ds + 0x0000A38A);
			eax_16_16_1026 = SLICE(eax_423, word16, 16);
			dx_424.u0 = 0x28BA;
			ebx_610 = ebx_1101;
			if (eax_423 <= seg28BA->tA175)
				break;
			if (seg28BA->tA422 != 0x01)
				fn2057_0453(ds);
			word16 bx_441;
			word16 dx_444;
			Eq_15188 ax_456 = (word16) (uint32) fn2331_0118(ds, out cx_123, out dx_444, out bx_441, out ds);
			ss->*((word16) bp_254 - 4) = dx_444;
			ss->*((word16) bp_254 - 6) = ax_456;
			al_188.u0 = ~0x45;
			ebx_260 = SEQ(ebx_16_16_885, bx_441);
			if (seg28BA->tA179 != 0x00)
			{
				struct Eq_15259 * es_bx_463 = seg28BA->tA179;
				ebx_260 = SEQ(ebx_16_16_885, (word16) es_bx_463);
				if (es_bx_463->ptr001D == seg1F0F && (es_bx_463->w001B == 0x0B00 && ss->*((word16) bp_254 - 2) == 0x00))
				{
					if (seg28BA->tA172 != 0x00)
					{
						al_188.u0 = ~0x45;
						if (seg28BA->t3032 == 0x28BA && seg28BA->t3030 == 0x8708)
						{
							bp_254 = fn2353_075C(ds, out ds);
							word16 bp_1119;
							word32 edx_522;
							struct Eq_15325 * ds_1120;
							al_188 = (byte) (uint32) fn226D_00F9(ds, out cx_123, out edx_522, out ebx_260, out bp_1119, out ds_1120);
							ss->*((word16) bp_254 - 2) = 0x01;
							sp_233.u0 = <invalid>;
							edx_16_16_263 = SLICE(edx_522, word16, 16);
						}
					}
					else
					{
						byte * es_bx_478 = seg28BA->t304F;
						struct Eq_15285 Eq_15287::* bx_480 = (word16) es_bx_478;
						struct Eq_15287 * es_485 = seg28BA->t3051;
						(es_485->*bx_480).w0002 += (int16) *es_bx_478;
						(seg28BA->t3051->*bx_480).b0000 = 0x00;
						al_188.u0 = ~0x45;
						ebx_260 = SEQ(ebx_16_16_885, bx_480);
					}
				}
			}
			word16 ebx_16_16_892 = SLICE(ebx_260, word16, 16);
			if (ss->*((word16) bp_254 - 6) != 0x00)
			{
				Eq_15188 es_bx_533 = ss->*((word16) bp_254 - 6);
				ss->*((word16) bp_254 - 8) = (uint16) *es_bx_533;
				struct Eq_11811 * es_534 = SLICE(es_bx_533, selector, 16);
				cx_123.u0 = 0x08;
				struct Eq_15487 Eq_25::* bx_541 = Eq_25::a09A2;
				do
				{
					uint16 ax_544 = (seg1D10->*bx_541).w0000;
					al_188 = (byte) ax_544;
					if (ax_544 == ss->*((word16) bp_254 - 8))
					{
						word32 eax_553;
						Eq_11798 ebx_555;
						word16 cx_556;
						bx_541[8]();
						dxOut.u0 = <invalid>;
						ebxOut = ebx_555;
						bpOut = bp_254;
						esOut = es_534;
						dsOut = ds;
						word16 bx_1095 = (word16) ebx_555;
						return (word16) eax_553;
					}
					++bx_541;
					--cx_123;
					ebx_260 = SEQ(ebx_16_16_892, bx_541);
				} while (cx_123 != 0x00);
			}
		}
		while (true)
		{
			word16 ebx_16_16_1039 = SLICE(ebx_610, word16, 16);
			if (seg28BA->tA422 != 0x01 || seg28BA->tA41A >= *((word32) ds + 0x0000A38A))
				break;
			while (true)
			{
				Eq_2 bx_666 = (word16) ebx_610;
				word16 ebx_16_16_922 = SLICE(ebx_610, word16, 16);
				if (seg28BA->t8854 == 0x00)
					break;
				if (*((word32) ds + 0x00007C98) != 0x00)
				{
					struct Eq_15221 Eq_14628::* sp_681 = sp_233 - 2;
					(ss->*sp_681).t0000 = *((word32) ds + 0x00007C98);
					(ss->*sp_681).tFFFFFFFE = seg28BA->tA18A;
					word16 bx_688;
					word32 eax_691 = fn209F_0516(ds, (ss->*sp_681).tFFFFFFFE, (ss->*sp_681).t0000, out cx_306, out dx_424, out bx_688);
					*((word32) ds + 0x00007C98) = (word16) eax_691;
					eax_16_16_1026 = SLICE(eax_691, word16, 16);
					ebx_610 = SEQ(ebx_16_16_922, bx_688);
				}
				else if (*((word32) ds + 31898) != 0x00)
				{
					struct Eq_15358 Eq_14628::* sp_659 = sp_233 - 2;
					(ss->*sp_659).t0000 = *((word32) ds + 31898);
					(ss->*sp_659).tFFFFFFFE = seg28BA->tA18A;
					word16 bx_669;
					*((word32) ds + 31898) = fn1D10_12D4(cx_306, dx_424, bx_666, ds, (ss->*sp_659).tFFFFFFFE, (ss->*sp_659).t0000, out cx_306, out dx_424, out bx_669);
					ebx_610 = SEQ(ebx_16_16_922, bx_669);
				}
				else
				{
					int32 eax_586 = (word32) seg28BA->tA41A;
					word16 eax_16_16_613 = SLICE(eax_586, word16, 16);
					Eq_14721 edx_612 = SEQ(edx_16_16_263, 0x28BA);
					if (eax_586 > seg28BA->tA175)
					{
						struct Eq_15426 Eq_14628::* sp_592 = sp_233 - 2;
						(ss->*sp_592).t0000 = ds;
						(ss->*sp_592).tFFFFFFFE.u0 = 31898;
						(ss->*sp_592).tFFFFFFFC = ds;
						(ss->*sp_592).tFFFFFFFA.u0 = 0x7C98;
						(ss->*sp_592).tFFFFFFF8 = seg28BA->tA18A;
						(ss->*sp_592).tFFFFFFF4 = ss->*((word16) bp_254 + 6);
						word32 ebx_1121;
						fn1D10_155B(eax_16_16_613, edx_612, ebx_610, ds, (ss->*sp_592).tFFFFFFF4, (ss->*sp_592).tFFFFFFF8, (ss->*sp_592).tFFFFFFFA, (ss->*sp_592).tFFFFFFFE, out cx_306, out edx_612, out ebx_1121, out ds);
					}
					struct Eq_15386 Eq_14628::* sp_629 = sp_233 - 2;
					(ss->*sp_629).t0000 = ds;
					(ss->*sp_629).tFFFFFFFE.u0 = 31898;
					(ss->*sp_629).tFFFFFFFC = ds;
					(ss->*sp_629).tFFFFFFFA.u0 = 0x7C98;
					(ss->*sp_629).tFFFFFFF8 = seg28BA->tA18A;
					edx_16_16_263 = SLICE(edx_650, word16, 16);
					dx_424 = (word16) edx_650;
					word32 edx_650;
					eax_16_16_1026 = SLICE(fn1D10_1368(cx_306, edx_612, ds, (ss->*sp_629).tFFFFFFF8, (ss->*sp_629).tFFFFFFFA, (ss->*sp_629).tFFFFFFFE, out cx_306, out edx_650, out ebx_610), word16, 16);
				}
			}
		}
		fn2057_0384(ds);
		word16 dx_1118;
		word16 bx_712;
		fn209F_02A7(ds, out dx_1118, out bx_712, out es);
		ebx_1035 = SEQ(ebx_16_16_1039, bx_712);
		eax_1022 = SEQ(eax_16_16_1026, ss->*((word16) bp_254 + 6));
	}
	Eq_11810 bp_856 = ss->*bp_254;
	dxOut.u0 = <invalid>;
	ebxOut = ebx_1035;
	bpOut = bp_856;
	esOut = es;
	dsOut = ds;
	return (word16) eax_1022;
}

// 1D10:09C2: Register word16 fn1D10_09C2(Register Eq_2 ds, Stack Eq_2 ptrArg04, Register out Eq_15523 ebxOut)
// Called from:
//      fn1D10_0F47
word16 fn1D10_09C2(Eq_2 ds, Eq_2 ptrArg04, union Eq_15523 & ebxOut)
{
	struct Eq_15524 * eax_12 = seg28BA->tA423;
	if (*((word32) ds + 41822) != null)
	{
		if (*((word32) ds + 0x00007C88) == 0x00)
		{
			struct Eq_15528 * es_bx_19 = *((word32) ds + 41822);
			*((word32) ds + 0x00007C80) = (int32) es_bx_19->w0000;
			*((word32) ds + 0x00007C84) = es_bx_19->t0002;
			word16 dx_1031;
			Eq_15554 ax_36 = fn2057_041E(ds, out dx_1031) - eax_12->w000F;
			Eq_15554 wLoc14_665 = ax_36;
			if (ax_36 < 0x00 || eax_12->t0002 <= ax_36)
				wLoc14_665.u0 = 0x00;
			Eq_15532 dx_67;
			word16 ax_65;
			word16 dx_54 = Mem48[eax_12 + 0x04:word16] + wLoc14_665;
			*((word32) ds + 0x0000A368) = eax_12->w0006;
			*((word32) ds + 0x0000A366) = dx_54;
			if (eax_12->t0008 > wLoc14_665)
			{
				ax_65 = eax_12->w0006;
				dx_67 = Mem58[eax_12 + 0x04:word16] + Mem58[eax_12 + 0x08:word16];
			}
			else
			{
				ax_65 = eax_12->w0006;
				dx_67 = Mem58[eax_12 + 0x04:word16] + Mem58[eax_12 + 0x02:word16];
			}
			*((word32) ds + 0x0000A36C) = ax_65;
			*((word32) ds + 0x0000A36A) = dx_67;
			while (*((word32) ds + 0x0000A366) != *((word32) ds + 0x0000A36A) && *((word32) ds + 0x00007C80) != 0x00)
			{
				int32 dx_ax_110 = (int32) (((uint16) **((word32) ds + 0x0000A366) & 0xFF) - 0x80 + (((uint16) (*(*((word32) ds + 0x00007C84))) & 0xFF) - 0x80));
				**((word32) ds + 0x0000A366) = (byte) (((word16) dx_ax_110 - SLICE(dx_ax_110, word16, 16) >> 0x01) + 0x80);
				*((word32) ds + 0x0000A366) = (word32) *((word32) ds + 0x0000A366) + 1;
				((word32) ds + 0x00007C84)->u0 = (word16) ((word32) ds + 0x00007C84)->u0 + 1;
				--*((word32) ds + 0x00007C80);
			}
			*((word32) ds + 0x00007C88) = *((word32) ds + 0x0000A366);
		}
		*((word32) ds + 0x0000A366) = *((word32) ds + 0x00007C88);
		while (*((word32) ds + 0x0000A366) != *((word32) ds + 0x0000A36A) && *((word32) ds + 0x00007C80) != 0x00)
		{
			int32 dx_ax_171 = (int32) (((uint16) **((word32) ds + 0x0000A366) & 0xFF) - 0x80 + (((uint16) (*(*((word32) ds + 0x00007C84))) & 0xFF) - 0x80));
			**((word32) ds + 0x0000A366) = (byte) (((word16) dx_ax_171 - SLICE(dx_ax_171, word16, 16) >> 0x01) + 0x80);
			*((word32) ds + 0x0000A366) = (word32) *((word32) ds + 0x0000A366) + 1;
			((word32) ds + 0x00007C84)->u0 = (word16) ((word32) ds + 0x00007C84)->u0 + 1;
			--*((word32) ds + 0x00007C80);
		}
		if (*((word32) ds + 0x00007C80) == 0x00)
		{
			*((word32) ds + 41822) = null;
			((word32) ds + 0x00007C88)->u0 = 0x00;
		}
		else
		{
			if (Mem140[eax_12 + 0x04:word16] + Mem140[eax_12 + 0x02:word16] <=u Mem140[ds:0xA366:word16])
				*((word32) ds + 0x0000A366) = eax_12->t0004;
			Eq_15532 dx_223;
			word16 ax_221;
			if (Mem209[eax_12 + 0x04:word16] + Mem209[eax_12 + 0x08:word16] >u Mem209[ds:0xA366:word16])
			{
				ax_221 = eax_12->w0006;
				dx_223 = Mem209[eax_12 + 0x04:word16] + Mem209[eax_12 + 0x08:word16];
			}
			else
			{
				ax_221 = eax_12->w0006;
				dx_223 = Mem209[eax_12 + 0x04:word16] + Mem209[eax_12 + 0x02:word16];
			}
			*((word32) ds + 0x0000A36C) = ax_221;
			*((word32) ds + 0x0000A36A) = dx_223;
			*((word32) ds + 0x00007C88) = *((word32) ds + 0x0000A366);
		}
	}
	if (*((word32) ds + 0x0000A362) != null)
	{
		if (*((word32) ds + 0x00007C94) == 0x00)
		{
			struct Eq_15536 * es_bx_244 = *((word32) ds + 0x0000A362);
			*((word32) ds + 0x00007C8C) = (int32) es_bx_244->w0000;
			*((word32) ds + 31888) = es_bx_244->t0002;
			word16 dx_1032;
			Eq_15554 ax_265 = fn2057_041E(ds, out dx_1032) - eax_12->w000F;
			Eq_15554 wLoc14_695 = ax_265;
			if (ax_265 < 0x00 || eax_12->t0002 <= ax_265)
				wLoc14_695.u0 = 0x00;
			Eq_15532 dx_296;
			word16 ax_294;
			word16 dx_283 = Mem277[eax_12 + 0x04:word16] + wLoc14_695;
			*((word32) ds + 41840) = eax_12->w0006;
			*((word32) ds + 41838) = dx_283;
			if (eax_12->t0008 > wLoc14_695)
			{
				ax_294 = eax_12->w0006;
				dx_296 = Mem287[eax_12 + 0x04:word16] + Mem287[eax_12 + 0x08:word16];
			}
			else
			{
				ax_294 = eax_12->w0006;
				dx_296 = Mem287[eax_12 + 0x04:word16] + Mem287[eax_12 + 0x02:word16];
			}
			*((word32) ds + 41844) = ax_294;
			*((word32) ds + 41842) = dx_296;
			while (*((word32) ds + 41838) != *((word32) ds + 41842) && *((word32) ds + 0x00007C8C) != 0x00)
			{
				int32 dx_ax_339 = (int32) (((uint16) **((word32) ds + 41838) & 0xFF) - 0x80 + (((uint16) (*(*((word32) ds + 31888))) & 0xFF) - 0x80));
				**((word32) ds + 41838) = (byte) (((word16) dx_ax_339 - SLICE(dx_ax_339, word16, 16) >> 0x01) + 0x80);
				*((word32) ds + 41838) = (word32) *((word32) ds + 41838) + 1;
				((word32) ds + 31888)->u0 = (word16) ((word32) ds + 31888)->u0 + 1;
				--*((word32) ds + 0x00007C8C);
			}
			*((word32) ds + 0x00007C94) = *((word32) ds + 41838);
		}
		*((word32) ds + 41838) = *((word32) ds + 0x00007C94);
		while (*((word32) ds + 41838) != *((word32) ds + 41842) && *((word32) ds + 0x00007C8C) != 0x00)
		{
			int32 dx_ax_400 = (int32) (((uint16) **((word32) ds + 41838) & 0xFF) - 0x80 + (((uint16) (*(*((word32) ds + 31888))) & 0xFF) - 0x80));
			**((word32) ds + 41838) = (byte) (((word16) dx_ax_400 - SLICE(dx_ax_400, word16, 16) >> 0x01) + 0x80);
			*((word32) ds + 41838) = (word32) *((word32) ds + 41838) + 1;
			((word32) ds + 31888)->u0 = (word16) ((word32) ds + 31888)->u0 + 1;
			--*((word32) ds + 0x00007C8C);
		}
		if (*((word32) ds + 0x00007C8C) == 0x00)
		{
			*((word32) ds + 0x0000A362) = null;
			((word32) ds + 0x00007C94)->u0 = 0x00;
		}
		else
		{
			if (Mem369[eax_12 + 0x04:word16] + Mem369[eax_12 + 0x02:word16] <=u Mem369[ds:41838:word16])
				*((word32) ds + 41838) = eax_12->t0004;
			Eq_15532 dx_452;
			word16 ax_450;
			if (Mem438[eax_12 + 0x04:word16] + Mem438[eax_12 + 0x08:word16] >u Mem438[ds:41838:word16])
			{
				ax_450 = eax_12->w0006;
				dx_452 = Mem438[eax_12 + 0x04:word16] + Mem438[eax_12 + 0x08:word16];
			}
			else
			{
				ax_450 = eax_12->w0006;
				dx_452 = Mem438[eax_12 + 0x04:word16] + Mem438[eax_12 + 0x02:word16];
			}
			*((word32) ds + 41844) = ax_450;
			*((word32) ds + 41842) = dx_452;
			*((word32) ds + 0x00007C94) = *((word32) ds + 41838);
		}
	}
	word16 eax_16_16_896;
	if (*((word32) ds + 41814) == 0x00)
	{
		word32 ebx_528;
		word32 edx_1037;
		word16 cx_1036;
		fn1D10_0FB3(ds, fp - 0x0A, out cx_1036, out edx_1037, out ebx_528, out ds);
		word16 cx_1038;
		word16 dx_1039;
		word16 bx_1040;
		word32 eax_552 = fn209F_0516(ds, seg28BA->tA18A, wLoc0A, out cx_1038, out dx_1039, out bx_1040);
		*((word32) ds + 41814) = (word16) eax_552;
		seg28BA->tA41A = wLoc06;
		ebx_16_16 = SLICE(ebx_528, word16, 16);
		eax_16_16_896 = SLICE(eax_552, word16, 16);
	}
	else
	{
		word16 cx_1033;
		word16 dx_1034;
		word16 bx_1035;
		word32 eax_506 = fn209F_0516(ds, seg28BA->tA18A, *((word32) ds + 41814), out cx_1033, out dx_1034, out bx_1035);
		*((word32) ds + 41814) = (word16) eax_506;
		seg28BA->tA184 = 0x0C;
		eax_16_16_896 = SLICE(eax_506, word16, 16);
	}
	if (*((word32) ds + 41814) == 0x00)
		seg28BA->tA184 = 0x00;
	word32 eax_894;
	Eq_15523 ebx_902 = SEQ(ebx_16_16, (word16) ptrArg04);
	if (*((word32) ptrArg04 + 6) <= seg28BA->tA41A)
	{
		word16 cx_1041;
		word16 dx_1042;
		word16 bx_1043;
		fn0800_06AB(ds, seg28BA->tA18A, 0x00, 0x00, out cx_1041, out dx_1042, out bx_1043);
		fn2057_0384(ds);
		word16 bx_632;
		struct Eq_15886 * es_1045;
		word16 dx_1044;
		fn209F_02A7(ds, out dx_1044, out bx_632, out es_1045);
		eax_894 = SEQ(eax_16_16_896, 0x00);
		ebx_902 = SEQ(ebx_16_16, bx_632);
	}
	else
	{
		if (seg28BA->tA422 != 0x01)
		{
			word16 bx_593;
			word16 cx_1046;
			fn209F_049A(ds, out cx_1046, out bx_593);
			ebx_902 = SEQ(ebx_16_16, bx_593);
		}
		eax_894 = SEQ(eax_16_16_896, 0x01);
	}
	ebxOut = ebx_902;
	return (word16) eax_894;
}

// 1D10:0E66: Register Eq_2 fn1D10_0E66(Register word32 ebx, Register Eq_2 ds, Stack Eq_2 dwArg04)
// Called from:
//      fn0CE0_08FC
//      fn1D10_0F47
Eq_2 fn1D10_0E66(word32 ebx, Eq_2 ds, Eq_2 dwArg04)
{
	word16 ebx_16_16 = SLICE(ebx, word16, 16);
	if ((uint16) seg28BA->tA183 != 0x00)
	{
		seg28BA->tA179 = dwArg04;
		((word32) ds + 41814)->u0 = 0x00;
		seg28BA->tA172 = 0x00;
		seg28BA->t8854 = 0x00;
		word16 eax_16_16_116 = SLICE(fn1ED0_0009(ds, dwArg04, out ds), word16, 16);
		word16 bx_52;
		word16 dx_54;
		struct Eq_16226 * es_255;
		fn209F_02A7(ds, out dx_54, out bx_52, out es_255);
		word16 edx_16_16_167 = SLICE(dwArg04, word16, 16);
		Eq_14691 ebx_114 = SEQ(ebx_16_16, bx_52);
		Eq_14721 edx_115 = SEQ(edx_16_16_167, dx_54);
		if (seg28BA->tA173 != 0x00)
		{
			word16 bx_68;
			word16 dx_70;
			word16 cx_256;
			eax_16_16_116 = SLICE(fn209F_06D8(ds, seg28BA->tA88A, out cx_256, out dx_70, out bx_68), word16, 16);
			seg28BA->tA173 = 0x00;
			ebx_114 = SEQ(ebx_16_16, bx_68);
			edx_115 = SEQ(edx_16_16_167, dx_70);
		}
		seg28BA->tA184 = 0x00;
		while (seg28BA->tA184 > 0x01 && *((word32) ds + 41814) == 0x00)
		{
			word16 cx_257;
			eax_16_16_116 = SLICE(fn1D10_155B(eax_16_16_116, edx_115, ebx_114, ds, dwArg04, seg28BA->tA18A, fp - 0x06, fp - 0x04, out cx_257, out edx_115, out ebx_114, out ds), word16, 16);
		}
		if (seg28BA->tA422 != 0x01)
		{
			word16 bx_259;
			word16 cx_258;
			fn209F_049A(ds, out cx_258, out bx_259);
		}
		*((word32) ds + 0x0000A35A) = 0x00;
	}
	return ds;
}

// 1D10:0F47: Register Eq_2 fn1D10_0F47(Register Eq_2 ds, Stack Eq_2 dwArg04)
// Called from:
//      fn0CE0_08FC
Eq_2 fn1D10_0F47(Eq_2 ds, Eq_2 dwArg04)
{
	if ((uint16) seg28BA->tA183 == 0x00 || *((word32) ds + 0x0000A35A) != 0x00)
		return ds;
	word32 ebx_27;
	if ((word16) (uint32) fn1D10_09C2(ds, dwArg04, out ebx_27) != 0x00)
		return ds;
	if (*((word32) ds + 41816) == 0x00)
	{
		*((word32) ds + 0x0000A35A) = 0x01;
		return ds;
	}
	else
	{
		ds = fn1D10_0E66(ebx_27, ds, dwArg04);
		word32 ebx_162;
		fn1D10_09C2(ds, dwArg04, out ebx_162);
		word32 ebx_163;
		fn1D10_09C2(ds, dwArg04, out ebx_163);
		return ds;
	}
}

// 1D10:0FB3: Register word32 fn1D10_0FB3(Register Eq_2 ds, Stack Eq_2 dwArg04, Register out Eq_2 cxOut, Register out Eq_15644 edxOut, Register out Eq_15645 ebxOut, Register out Eq_2 dsOut)
// Called from:
//      fn1D10_09C2
//      fn1D10_1368
word32 fn1D10_0FB3(Eq_2 ds, Eq_2 dwArg04, union Eq_2 & cxOut, union Eq_15644 & edxOut, union Eq_15645 & ebxOut, union Eq_2 & dsOut)
{
	fn0800_1109(ds, seg28BA->tA18A);
	Eq_2 dx_ax_515 = <invalid>;
	word16 wLoc12_316 = 0x0A;
	Eq_2 dwLoc0E_322 = (word32) dx_ax_515 + 8;
	do
	{
		word16 wLoc10_345;
		Eq_2 es_161;
		word16 dx_54;
		word16 bx_523;
		Eq_2 cx_167;
		int32 eax_62 = (int32) fn0800_3C87(ds, seg28BA->tA18A, dwArg04, 0x08, out cx_167, out dx_54, out bx_523);
		word16 eax_16_16_429 = SLICE(eax_62, word16, 16);
		Eq_915 ax_165 = (word16) eax_62;
		Eq_15644 edx_457 = SEQ(edx_16_16, dx_54);
		if (eax_62 != ~0x00 && eax_62 == 0x08)
		{
			es_161 = SLICE(dwArg04, selector, 16);
			if (*((word32) dwArg04 + 6) == 0xC060)
				goto l1D10_1097;
		}
		Eq_2 v17_76 = seg28BA->tA18A;
		word16 dx_84;
		Eq_915 ax_82 = fn0800_2AD9(ds, v17_76, out dx_84);
		es_161.u0 = 0x28BA;
		cx_167 = v17_76;
		ax_165 = ax_82;
		edx_457 = SEQ(edx_16_16, dx_84);
		if (ax_82 == 0x00)
		{
			word16 bx_522;
			word16 cx_520;
			word16 dx_521;
			fn0800_06AB(ds, seg28BA->tA18A, dwLoc0E_322, 0x00, out cx_520, out dx_521, out bx_522);
			ci16 wLoc14_335;
			for (wLoc14_335 = 0x00; wLoc14_335 < 10000; ++wLoc14_335)
			{
				word16 cx_524;
				word16 dx_525;
				word16 bx_526;
				fn0800_3C87(ds, seg28BA->tA18A, fp - 0x0114, 0x0100, out cx_524, out dx_525, out bx_526);
				dwLoc0E_322 = (word32) dwLoc0E_322 + 0x0100;
			}
			wLoc10_345 = 0x00;
			es_161.u0 = 0x28BA;
			word16 dx_168;
			word16 bx_527;
			ax_165 = fn0800_06AB(ds, seg28BA->tA18A, dx_ax_515, 0x00, out cx_167, out dx_168, out bx_527);
			edx_457 = SEQ(edx_16_16, dx_168);
		}
		else
		{
l1D10_1097:
			wLoc10_345 = 0x01;
		}
		edx_16_16 = SLICE(edx_457, word16, 16);
		word32 eax_423 = SEQ(eax_16_16_429, ax_165);
		if (wLoc10_345 != 0x00)
			break;
		--wLoc12_316;
		eax_423 = SEQ(eax_16_16_429, wLoc12_316);
	} while (wLoc12_316 != 0x00);
	word16 eax_16_16_437 = SLICE(eax_423, word16, 16);
	if (eax_62 == ~0x00)
	{
		word16 dx_213;
		struct Eq_16459 * es_528;
		cx_167 = fn263F_04B6(es_161, ds, out dx_213, out es_528, out ds);
		eax_423 = SEQ(eax_16_16_437, ax_208);
		edx_457 = SEQ(edx_16_16, dx_213);
	}
	word16 edx_16_16_472 = SLICE(edx_457, word16, 16);
	word16 eax_16_16_439 = SLICE(eax_423, word16, 16);
	if (eax_62 != 0x08)
	{
		Eq_2 v27_231 = seg28BA->tA18A;
		word16 dx_238;
		Eq_915 ax_236 = fn0800_2AD9(ds, v27_231, out dx_238);
		cx_167 = v27_231;
		eax_423 = SEQ(eax_16_16_439, ax_236);
		edx_457 = SEQ(edx_16_16_472, dx_238);
		if (ax_236 == 0x00)
		{
			word16 dx_259;
			struct Eq_16496 * es_529;
			cx_167 = fn263F_04B6(0x28BA, ds, out dx_259, out es_529, out ds);
			eax_423 = SEQ(eax_16_16_439, ax_254);
			edx_457 = SEQ(edx_16_16_472, dx_259);
		}
	}
	Eq_15645 ebx_444 = SEQ(ebx_16_16, (word16) dwArg04);
	if (*((word32) dwArg04 + 6) != 0xC060)
	{
		Eq_2 es_280;
		word32 ebx_282;
		word32 edx_283;
		word16 cx_530;
		word16 eax_16_16_442 = SLICE(fn2425_01E8(ds, out cx_530, out edx_283, out ebx_282, out es_280), word16, 16);
		word16 dx_298;
		struct Eq_16518 * es_531;
		cx_167 = fn263F_04B6(es_280, ds, out dx_298, out es_531, out ds);
		eax_423 = SEQ(eax_16_16_442, ax_293);
		ebx_444 = SEQ(SLICE(ebx_282, word16, 16), bx_294);
		edx_457 = SEQ(SLICE(edx_283, word16, 16), dx_298);
	}
	cxOut = cx_167;
	edxOut = edx_457;
	ebxOut = ebx_444;
	dsOut = ds;
	return eax_423;
}

// 1D10:1153: Register word16 fn1D10_1153(Register word16 eax_16_16, Register word16 ebx_16_16, Register Eq_2 ds, Stack byte bArg04, Stack byte bArg06, Stack cup16 wArg08, Stack uint16 wArg0A, Register out Eq_16539 edxOut, Register out Eq_16540 ebxOut, Register out Eq_2 dsOut)
// Called from:
//      fn1D10_155B
word16 fn1D10_1153(word16 eax_16_16, word16 ebx_16_16, Eq_2 ds, byte bArg04, byte bArg06, cup16 wArg08, uint16 wArg0A, union Eq_16539 & edxOut, union Eq_16540 & ebxOut, union Eq_2 & dsOut)
{
	Eq_2 dx_ax_476 = <invalid>;
	Eq_2 es_147 = 0x28BA;
	word16 cx_123 = fn0800_0528(seg28BA->tA882, 0x00, seg28BA->tA884, wArg08);
	Eq_16539 edx_35 = SEQ(edx_16_16, SLICE(dx_ax_476, word16, 16));
	if (*((word32) ds + 0x0000A35C) == 0x00)
	{
		__cli();
		word32 ebx_34;
		eax_16_16 = SLICE(fn2425_01E8(ds, out cx_123, out edx_35, out ebx_34, out es_147), word16, 16);
		__sti();
		ebx_16_16 = SLICE(ebx_34, word16, 16);
	}
	word16 edx_16_16_428 = SLICE(edx_35, word16, 16);
	if (bArg06 != 0x00)
		edx_35 = SEQ(edx_16_16_428, fn2476_05D7(ds));
	Eq_16578 ax_56 = (int16) bArg04;
	word16 edx_16_16_431 = SLICE(edx_35, word16, 16);
	Eq_16540 ebx_405 = SEQ(ebx_16_16, ax_56 - 0x03);
	if (ax_56 > 11)
		goto l1D10_12A1;
	ui16 bx_61 = ax_56 - 0x03 << 0x01;
	word24 ebx_24_8_92 = SEQ(ebx_16_16, SLICE(bx_61, byte, 8));
	ebx_405 = SEQ(ebx_16_16, bx_61);
	switch (bx_61)
	{
	case 0x00:
		cx_123 = fn21CC_04BE(dx_ax_476);
		break;
	case 0x01:
		if (*((word32) ds + 41846) != 0x00)
		{
			Eq_16658 v17_218 = seg28BA->tAA80;
			fn1D10_1A8F(*((word32) ds + 41848), *((word32) ds + 0x0000A37A), *((word32) ds + 0x0000A37C), *((word32) ds + 41854), dx_ax_476, v17_218, SLICE(v17_218, word16, 16));
			ebx_405 = SEQ(ebx_16_16, bx_236);
			edx_35 = SEQ(edx_16_16_431, dx_237);
			goto l1D10_1277;
		}
		cx_123 = fn21CC_045A(dx_ax_476);
		ebx_405 = SEQ(ebx_16_16, bx_208);
		edx_35 = SEQ(edx_16_16_431, dx_210);
		break;
	case 0x02:
		if (*((word32) ds + 41846) != 0x00)
		{
			cx_123 = fn0E11_0004(*((word32) ds + 41848), *((word32) ds + 0x0000A37A), dx_ax_476, seg28BA->tAA80);
			ebx_405 = SEQ(ebx_16_16, bx_194);
			edx_35 = SEQ(edx_16_16_431, dx_196);
			goto l1D10_1277;
		}
		es_147.u0 = 0x28BA;
		if (seg28BA->tAA7E >= 0x03)
		{
			cx_123 = fn21CC_08A2(dx_ax_476);
			ebx_405 = SEQ(ebx_16_16, bx_166);
			edx_35 = SEQ(edx_16_16_431, dx_167);
		}
		else
		{
			cx_123 = fn21CC_0052(dx_ax_476);
			ebx_405 = SEQ(ebx_16_16, bx_154);
			edx_35 = SEQ(edx_16_16_431, dx_156);
		}
		break;
	case 0x03:
		cx_123 = fn21CC_03CC(eax_16_16, dx_ax_476);
		ebx_405 = SEQ(ebx_16_16, bx_136);
		edx_35 = SEQ(edx_16_16_431, dx_138);
		break;
	case 0x04:
	case 0x05:
	case 0x06:
	case 0x07:
l1D10_12A1:
		word16 edx_16_16_441 = SLICE(edx_35, word16, 16);
		word16 ebx_16_16_419 = SLICE(ebx_405, word16, 16);
		if (*((word32) ds + 0x0000A35C) == 0x00)
		{
			__cli();
			word16 bx_275;
			word16 dx_279;
			fn2425_0286(es_147, ds, out cx_123, out dx_279, out bx_275, out ds);
			__sti();
			ebx_405 = SEQ(ebx_16_16_419, bx_275);
			edx_35 = SEQ(edx_16_16_441, dx_279);
		}
		if (wArg0A != 0x00)
			seg28BA->tA184 = seg28BA->tA184 + 0x05;
		edxOut = edx_35;
		ebxOut = ebx_405;
		dsOut = ds;
		return cx_123;
	case 0x08:
		if (*((word32) ds + 41846) != 0x00)
		{
			cx_123 = fn0E11_00DB(*((word32) ds + 41848), *((word32) ds + 0x0000A37A), *((word32) ds + 0x0000A37C), *((word32) ds + 41854), dx_ax_476, seg28BA->tAA80);
			ebx_405 = SEQ(ebx_16_16, bx_122);
			edx_35 = SEQ(edx_16_16_431, dx_124);
l1D10_1277:
			es_147.u0 = 0x28BA;
			goto l1D10_12A1;
		}
		es_147.u0 = 0x28BA;
		if (seg28BA->tAA7E >= 0x03)
			cx_123 = fn21CC_06C8(ebx_24_8_92, dx_ax_476, out edx_35, out ebx_405);
		else
		{
			cx_123 = fn21CC_05CB(dx_ax_476);
			ebx_405 = SEQ(ebx_16_16, bh_76, bl_77);
			edx_35 = SEQ(edx_16_16_431, dx_79);
		}
		break;
	}
	goto l1D10_12A1;
}

// 1D10:12D4: Register cup16 fn1D10_12D4(Register Eq_2 cx, Register Eq_2 dx, Register Eq_2 bx, Register Eq_2 ds, Stack Eq_2 wArg04, Stack Eq_915 wArg06, Register out Eq_2 cxOut, Register out Eq_2 dxOut, Register out Eq_2 bxOut)
// Called from:
//      fn1D10_02AE
//      fn1D10_1368
//      fn1D10_155B
cup16 fn1D10_12D4(Eq_2 cx, Eq_2 dx, Eq_2 bx, Eq_2 ds, Eq_2 wArg04, Eq_915 wArg06, union Eq_2 & cxOut, union Eq_2 & dxOut, union Eq_2 & bxOut)
{
	Eq_915 wLoc04_120;
	if (wArg06 < 30000)
		wLoc04_120 = wArg06;
	else
		wLoc04_120.u0 = 30000;
	if (*((word32) ds + 0x00007CA0) != 0x00)
		*((word32) ds + 0x00007CA0) = 0x00;
	else
		wLoc04_120 = fn0800_3C87(ds, wArg04, SEQ(seg28BA->tA884, seg28BA->tA882 + *((word32) ds + 41810)), wLoc04_120, out cx, out dx, out bx);
	if (wLoc04_120 == ~0x00)
	{
		word16 di_193;
		cx = fn263F_03F3(cx, dx, bx, ds, out dx, out bx, out di_193, out ds);
	}
	*((word32) ds + 41810) = (word16) wLoc04_120.u0 + *((word32) ds + 41810);
	*((word32) ds + 41812) = (word16) wLoc04_120.u0 + *((word32) ds + 41812);
	cup16 v15_96 = wArg06 - wLoc04_120;
	if (v15_96 == 0x00)
	{
		int16 bx_102 = *((word32) ds + 0x0000A34E);
		SEQ(ds, 41606)[bx_102 * 0x0A] = 0x01;
		++*((word32) ds + 0x0000A34E);
		bx = bx_102 *s 0x0A;
		if (*((word32) ds + 0x0000A34E) == 0x14)
			*((word32) ds + 0x0000A34E) = 0x00;
	}
	cxOut = cx;
	dxOut = dx;
	bxOut = bx;
	return v15_96;
}

// 1D10:1368: Register word32 fn1D10_1368(Register Eq_2 cx, Register Eq_14721 dx, Register Eq_2 ds, Stack Eq_2 wArg04, Stack Eq_14767 ptrArg06, Stack Eq_14768 ptrArg0A, Register out Eq_2 cxOut, Register out Eq_14850 edxOut, Register out Eq_14851 ebxOut)
// Called from:
//      fn1D10_02AE
//      fn1D10_155B
word32 fn1D10_1368(Eq_2 cx, Eq_14721 dx, Eq_2 ds, Eq_2 wArg04, Eq_14767 ptrArg06, Eq_14768 ptrArg0A, union Eq_2 & cxOut, union Eq_14850 & edxOut, union Eq_14851 & ebxOut)
{
	Eq_2 wArg0A_342 = (word16) es_bx_530;
	word16 eax_16_16_416 = SLICE(eax, word16, 16);
	Eq_915 wLoc06_297 = 0x00;
	Eq_14851 ebx_433 = SEQ(ebx_16_16, (word16) es_bx_530);
	Eq_14850 edx_456 = edx;
	if (*es_bx_530 != 0x00)
	{
l1D10_1558:
		cxOut = cx;
		edxOut = edx_456;
		ebxOut = ebx_433;
		return eax;
	}
	ebx_433 = SEQ(ebx_16_16, (word16) es_bx_530);
	edx_456 = edx;
	if (*es_bx_530 != 0x00)
		goto l1D10_1558;
	if (seg28BA->tA184 < ~0x04)
		seg28BA->tA184 = ~0x04;
	if (*((word32) ds + 0x0000A388) == 0x00)
	{
		word32 ebx_44;
		eax_16_16_416 = SLICE(fn1D10_0FB3(ds, SEQ(ds, 0xA380), out cx, out edx, out ebx_44, out ds), word16, 16);
		ebx_16_16 = SLICE(ebx_44, word16, 16);
	}
	else
		*((word32) ds + 0x0000A388) = 0x00;
	word32 eax_531;
	Eq_915 ax_59 = *((word32) ds + 0x0000A380);
	byte al_64 = *((word32) ds + 0x0000A383);
	word16 edx_16_16_460 = SLICE(edx, word16, 16);
	Eq_2 dx_246 = (word16) edx;
	Eq_915 wLoc04_303 = ax_59;
	uint16 ax_66 = (uint16) al_64;
	eax = SEQ(eax_16_16_416, 0x00, al_64);
	if (ax_66 == 0x07)
	{
		if (ax_59 > 441)
			wLoc04_303.u0 = 441;
		word16 dx_86;
		word16 bx_536;
		eax_531 = fn209F_0516(ds, wArg04, wLoc04_303, out cx, out dx_86, out bx_536);
		edx_456 = SEQ(edx_16_16_460, dx_86);
		goto l1D10_13EE;
	}
	if (ax_66 == 0x09)
	{
		Eq_2 eax_100 = (word32) ax_59;
		word16 bx_107;
		word16 dx_109;
		eax = SEQ(SLICE(eax_100, word16, 16), fn0800_06AB(ds, wArg04, eax_100, 0x01, out cx, out dx_109, out bx_107));
		ebx_433 = SEQ(ebx_16_16, bx_107);
		edx_456 = SEQ(edx_16_16_460, dx_109);
		goto l1D10_1558;
	}
	int16 bx_116 = *((word32) ds + 0x0000A34E);
	ebx_433 = SEQ(ebx_16_16, bx_116 *s 0x0A);
	edx_456 = edx;
	if (SEQ(ds, 41606)[bx_116 * 0x0A] != 0x00)
	{
		*((word32) ds + 0x0000A388) = 0x01;
		goto l1D10_1558;
	}
	if (*((word32) ds + 41810) > *((word32) ds + 41808))
	{
		Eq_915 ax_124 = 65000 - *((word32) ds + 41810);
		wLoc06_297 = ax_124;
		if (ax_124 < ax_59)
			*((word32) ds + 41810) = 0x00;
	}
	if (*((word32) ds + 41810) < *((word32) ds + 41808))
	{
		cup16 ax_146;
		int16 bx_134 = *((word32) ds + 41804);
		ebx_433 = SEQ(ebx_16_16, bx_134 *s 0x0A);
		if (SEQ(ds, 41606)[bx_134 * 0x0A] != 0x00)
			ax_146 = *((word32) ds + 41808);
		else
		{
			Eq_915 ax_139 = 65000 - *((word32) ds + 41810);
			wLoc06_297 = ax_139;
			if (ax_139 >= ax_59)
				goto l1D10_147B;
			*((word32) ds + 41810) = 0x00;
			ax_146 = 65000;
		}
		wLoc06_297 = ax_146 - *((word32) ds + 41810);
	}
l1D10_147B:
	word16 ebx_16_16_448 = SLICE(ebx_433, word16, 16);
	if (*((word32) ds + 41810) == *((word32) ds + 41808))
	{
		int16 bx_161 = *((word32) ds + 41804);
		ebx_433 = SEQ(ebx_16_16_448, bx_161 *s 0x0A);
		if (SEQ(ds, 41606)[bx_161 * 0x0A] != 0x00)
			wLoc06_297.u0 = 0x00;
		else
			wLoc06_297 = 65000 - *((word32) ds + 41810);
	}
	ebx_16_16 = SLICE(ebx_433, word16, 16);
	eax = SEQ(eax_16_16_416, wLoc06_297);
	edx_456 = edx;
	if (wLoc06_297 < ax_59)
	{
		*((word32) ds + 0x0000A388) = 0x01;
		goto l1D10_1558;
	}
	*((word32) ds + 0x00007CA0) = 0x00;
	if (ax_59 == 0x00)
	{
		edx_456 = edx;
		if (wLoc06_297 == 0x00)
		{
			if (*((word32) ds + 0x0000A388) == 0x01)
				eax = SEQ(eax_16_16_416, 0x01);
			else
				eax = SEQ(eax_16_16_416, 0x00);
			goto l1D10_1558;
		}
		*((word32) ds + 0x00007CA0) = 0x01;
		wLoc04_303.u0 = 0x01;
	}
	*es_bx_530 = (union Eq_915 *) wLoc04_303;
	SEQ(ds, 41604)[Mem193[ds:0xA34E:word16] * 0x0A] = Mem193[ds:41810:word16];
	SEQ(ds, 41606)[Mem198[ds:0xA34E:word16] * 0x0A] = 0x00;
	SEQ(ds, 0xA287)[Mem201[ds:0xA34E:word16] * 0x0A] = Mem201[ds:0xA383:byte];
	SEQ(ds, 0xA288)[Mem205[ds:0xA34E:word16] * 0x0A] = Mem205[es_bx_530 + 0x00:word16];
	SEQ(ds, 0xA28A)[Mem210[ds:0xA34E:word16] * 0x0A] = Mem210[ds:0xA384:word16];
	SEQ(ds, 41612)[Mem214[ds:0xA34E:word16] * 0x0A] = CONVERT(Mem214[ds:41858:byte], byte, uint16);
	edx_456 = SEQ(edx_16_16_460, dx_254);
	word16 dx_254;
	word16 bx_537;
	eax_531 = SEQ(eax_16_16_416, fn1D10_12D4(cx, dx_246, wArg0A_342, ds, wArg04, *es_bx_530, out cx, out dx_254, out bx_537));
l1D10_13EE:
	*es_bx_530 = (union Eq_915 *) (word16) eax_531;
	eax = eax_531;
	ebx_433 = SEQ(ebx_16_16, (word16) es_bx_530);
	goto l1D10_1558;
}

// 1D10:155B: Register word32 fn1D10_155B(Register word16 eax_16_16, Register Eq_14721 edx, Register Eq_14691 ebx, Register Eq_2 ds, Stack Eq_2 ptrArg02, Stack Eq_2 wArg06, Stack Eq_14767 dwArg08, Stack Eq_14768 dwArg0C, Register out Eq_2 cxOut, Register out Eq_14721 edxOut, Register out Eq_14691 ebxOut, Register out Eq_2 dsOut)
// Called from:
//      fn1D10_02AE
//      fn1D10_0E66
word32 fn1D10_155B(word16 eax_16_16, Eq_14721 edx, Eq_14691 ebx, Eq_2 ds, Eq_2 ptrArg02, Eq_2 wArg06, Eq_14767 dwArg08, Eq_14768 dwArg0C, union Eq_2 & cxOut, union Eq_14721 & edxOut, union Eq_14691 & ebxOut, union Eq_2 & dsOut)
{
	word16 edx_16_16 = SLICE(edx, word16, 16);
	word16 ebx_16_16 = SLICE(ebx, word16, 16);
	if (seg28BA->tA184 < ~0x04)
		seg28BA->tA184 = ~0x04;
	Eq_14721 edx_260;
	Eq_14691 ebx_891;
	word32 eax_628;
	if (seg28BA->t8854 != 0x00)
	{
		if (seg28BA->t8855 != 0x00)
		{
			word16 bx_657;
			word16 dx_658 = fn2476_0495(ds, out bx_657);
			seg28BA->tA184 = seg28BA->tA184 + 0x05;
			seg28BA->tA175 = seg28BA->tA175 + 0x02;
			eax_628 = SEQ(eax_16_16, 0x28BA);
			ebx_891 = SEQ(ebx_16_16, bx_657);
			edx_260 = SEQ(edx_16_16, dx_658);
		}
		else
		{
			ebx_891 = ebx;
			if (seg28BA->t8856 != 0x00)
			{
				ebx_891 = SEQ(ebx_16_16, bx_647);
				word16 bx_647;
				edx_260 = SEQ(edx_16_16, fn2476_0601(ds, out bx_647));
			}
			else
				edx_260 = SEQ(edx_16_16, fn2476_05D7(ds));
			seg28BA->t8854 = 0x00;
			eax_628 = SEQ(eax_16_16, 0x28BA);
		}
	}
	else
	{
		int16 bx_23 = *((word32) ds + 41804);
		eax_628 = SEQ(eax_16_16, 0x28BA);
		ebx_891 = SEQ(ebx_16_16, bx_23 *s 0x0A);
		edx_260 = edx;
		if (SEQ(ds, 41606)[bx_23 * 0x0A] == 0x00)
			goto l1D10_19F6;
		int16 bx_45 = *((word32) ds + 41804);
		word16 ax_39 = SEQ(ds, 0xA288)[Mem36[ds:41804:word16] * 0x0A];
		word16 ax_43 = SEQ(ds, 0xA28A)[Mem40[ds:41804:word16] * 0x0A];
		word16 ax_47 = SEQ(ds, 41612)[bx_45 * 0x0A];
		byte al_29 = SEQ(ds, 0xA287)[Mem18[ds:41804:word16] * 0x0A];
		word16 ax_35 = SEQ(ds, 41604)[Mem32[ds:41804:word16] * 0x0A];
		Eq_915 wLoc08_689 = ax_39;
		Eq_2 wLoc0A_690 = ax_43;
		byte bLoc0C_694 = (byte) ax_47;
		if (ax_43 > *((word32) ds + 0x0000A38A))
		{
			ebx_891 = SEQ(ebx_16_16, bx_45 *s 0x0A);
			if (*((word32) ds + 0x0000A38A) > *((word32) ds + 41868))
			{
				eax_628 = (word32) ax_43;
				seg28BA->tA175 = eax_628;
				edx_260 = SEQ(edx_16_16, 0x28BA);
				goto l1D10_19F6;
			}
		}
		Eq_17241 ax_59 = (int16) al_29;
		if (ax_59 > 0x0E)
			goto l1D10_1921;
		switch (ax_59 << 0x01)
		{
		case 0x00:
		case 0x09:
l1D10_1945:
			seg28BA->tA175 = (word32) wLoc0A_690;
			if ((word32) *((word32) ptrArg02 + 8) <= seg28BA->tA175)
				seg28BA->tA172 = 0x01;
			int32 eax_555 = (word32) *((word32) ptrArg02 + 0x0A);
			word16 eax_16_16_886 = SLICE(eax_555, word16, 16);
			edx_260 = SEQ(edx_16_16, 0x28BA);
			if (eax_555 <= seg28BA->tA175)
				seg28BA->tA172 = 0x00;
			if (ptrArg02 != 0x00 && (seg28BA->t3093 != 0x00 && seg28BA->tA172 != 0x00))
			{
				word32 ebx_591;
				eax_16_16_886 = SLICE(fn226D_0BC6(ds, ptrArg02, 0xED, out cx, out edx_260, out ebx_591, out ds), word16, 16);
				ebx_16_16 = SLICE(ebx_591, word16, 16);
			}
			SEQ(ds, 41606)[Mem606[ds:41804:word16] * 0x0A] = 0x00;
			*((word32) ds + 41812) -= wLoc08_689;
			++*((word32) ds + 41804);
			if (*((word32) ds + 41804) == 0x14)
				*((word32) ds + 41804) = 0x00;
			int16 bx_623 = *((word32) ds + 41804);
			word16 ax_626 = SEQ(ds, 41604)[bx_623 * 0x0A];
			*((word32) ds + 41808) = ax_626;
			eax_628 = SEQ(eax_16_16_886, ax_626);
			ebx_891 = SEQ(ebx_16_16, bx_623 *s 0x0A);
			break;
		case 0x01:
		case 0x03:
		case 0x04:
		case 0x05:
		case 0x06:
		case 0x07:
		case 0x08:
		case 0x0A:
		case 11:
l1D10_1921:
			word32 ebx_505;
			word32 edx_506;
			cx = fn1D10_1153(eax_16_16, ebx_16_16, ds, al_29, *((word32) ds + 0x00007CA4), ax_35, ax_47, out edx_506, out ebx_505, out ds);
			ebx_16_16 = SLICE(ebx_505, word16, 16);
			edx_16_16 = SLICE(edx_506, word16, 16);
			if (*((word32) ds + 0x00007CA4) == 0x00)
				goto l1D10_1945;
			*((word32) ds + 0x00007CA4) = 0x00;
			goto l1D10_185B;
		case 0x02:
			*((word32) ds + 0x00007CA4) = 0x00;
			cx = fn2476_0568(ds, SEQ(seg28BA->tA884, seg28BA->tA882 + ax_35), ax_39);
			struct Eq_17306 * es_bx_189 = seg28BA->tA558;
			byte bLoc04_705 = 0x01;
			edx_260 = SEQ(edx_16_16, 0x28BA);
			if (SEQ(seg28BA->tA55A, (word16) es_bx_189)[(uint16) es_bx_189->b0001].w0000 == *((word32) ds + 0x00007CA2))
				bLoc04_705 = 0x00;
			else
			{
				struct Eq_17402 * es_bx_205 = seg28BA->tA558;
				*((word32) ds + 0x00007CA2) = SEQ(seg28BA->tA55A, (word16) es_bx_205)[(uint16) es_bx_205->b0001].w0000;
				edx_260 = SEQ(edx_16_16, 0x28BA);
			}
			SEQ(ds, 41606)[Mem221[ds:41804:word16] * 0x0A] = 0x00;
			*((word32) ds + 41812) -= ax_39;
			++*((word32) ds + 41804);
			if (*((word32) ds + 41804) == 0x14)
				*((word32) ds + 41804) = 0x00;
			Mem241[ds:0xA350:word16] = SEQ(ds, 41604)[Mem237[ds:41804:word16] * 0x0A];
			if (SEQ(ds, 41606)[Mem241[ds:41804:word16] * 0x0A] == 0x00)
			{
				ebx_16_16 = SLICE(ebx_270, word16, 16);
				word32 ebx_270;
				word32 edx_271;
				eax_16_16 = SLICE(fn1D10_1368(cx, edx_260, ds, wArg06, dwArg08, dwArg0C, out cx, out edx_271, out ebx_270), word16, 16);
				Eq_2 dx_300 = (word16) edx_271;
				word16 edx_16_16_926 = SLICE(edx_271, word16, 16);
				while (*dwArg08 != 0x00)
				{
					word16 bx_1014;
					word32 eax_301 = fn209F_0516(ds, wArg06, *dwArg08, out cx, out dx_300, out bx_1014);
					*dwArg08 = (word16) eax_301;
					eax_16_16 = SLICE(eax_301, word16, 16);
				}
				while (true)
				{
					edx_260 = SEQ(edx_16_16_926, dx_300);
					if (*dwArg0C == 0x00)
						break;
					word16 bx_1015;
					*dwArg0C = fn1D10_12D4(cx, dx_300, (word16) dwArg0C, ds, wArg06, *dwArg0C, out cx, out dx_300, out bx_1015);
				}
			}
			int16 bx_370 = *((word32) ds + 41804);
			word16 ax_368 = SEQ(ds, 0xA28A)[Mem365[ds:41804:word16] * 0x0A];
			word16 ax_372 = SEQ(ds, 41612)[bx_370 * 0x0A];
			edx_16_16 = SLICE(edx_260, word16, 16);
			byte al_354 = SEQ(ds, 0xA287)[Mem351[ds:41804:word16] * 0x0A];
			word16 ax_360 = SEQ(ds, 41604)[Mem357[ds:41804:word16] * 0x0A];
			wLoc08_689 = SEQ(ds, 0xA288)[Mem361[ds:41804:word16] * 0x0A];
			wLoc0A_690 = ax_368;
			eax_628 = SEQ(eax_16_16, ax_372);
			ebx_891 = SEQ(ebx_16_16, bx_370 *s 0x0A);
			if (al_354 != 0x07)
			{
				int16 ax_377 = (int16) al_354;
				if (ax_377 != 0x00)
				{
					if (ax_377 != 0x09)
					{
						word32 ebx_426;
						word32 edx_427;
						cx = fn1D10_1153(eax_16_16, ebx_16_16, ds, al_354, bLoc04_705, ax_360, ax_372, out edx_427, out ebx_426, out ds);
						*((word32) ds + 0x00007CA4) = 0x00;
						ebx_16_16 = SLICE(ebx_426, word16, 16);
						edx_16_16 = SLICE(edx_427, word16, 16);
					}
				}
				else
				{
					seg28BA->tA175 = (word32) ax_368;
					*((word32) ds + 0x00007CA4) = 0x01;
				}
				seg28BA->tA175 = (word32) ax_368;
				if ((word32) *((word32) ptrArg02 + 8) <= seg28BA->tA175)
					seg28BA->tA172 = 0x01;
				if ((word32) *((word32) ptrArg02 + 0x0A) <= seg28BA->tA175)
					seg28BA->tA172 = 0x00;
				if ((int16) *((word32) ds + 0x00007CA4) != 0x00)
					goto l1D10_1945;
l1D10_185B:
				word16 bx_1011;
				fn2476_0601(ds, out bx_1011);
				goto l1D10_1945;
			}
			break;
		case 0x0C:
			fn2476_05D7(ds);
			*((word32) ds + 0x00007CA2) = 0x00;
			seg28BA->tA184 = seg28BA->tA184 + 0x05;
			goto l1D10_1945;
		case 0x0D:
			cx = fn2476_0568(ds, SEQ(seg28BA->tA884, seg28BA->tA882 + ax_35), ax_39);
			seg28BA->t8854 = bLoc0C_694;
			seg28BA->t8855 = bLoc0C_694;
			seg28BA->t8855 = seg28BA->t8855 + ~0x01;
			seg28BA->t8856 = 0x01;
			word16 bx_1012;
			fn2476_0495(ds, out bx_1012);
			seg28BA->tA184 = seg28BA->tA184 - 0x02;
			goto l1D10_1945;
		case 0x0E:
			seg28BA->t8854 = bLoc0C_694;
			seg28BA->t8855 = bLoc0C_694;
			seg28BA->t8856 = 0x00;
			seg28BA->t8855 = seg28BA->t8855 + ~0x01;
			word16 bx_1013;
			fn2476_0495(ds, out bx_1013);
			*((word32) ds + 0x00007CA2) = 0x00;
			goto l1D10_1945;
		}
	}
l1D10_19F6:
	cxOut = cx;
	edxOut = edx_260;
	ebxOut = ebx_891;
	dsOut = ds;
	return eax_628;
}

// 1D10:1A16: void fn1D10_1A16(Register Eq_2 ds)
// Called from:
//      fn0CE0_08FC
//      fn1D10_02AE
void fn1D10_1A16(Eq_2 ds)
{
	int16 wLoc04_43;
	for (wLoc04_43 = 0x00; wLoc04_43 < 0x14; ++wLoc04_43)
	{
		SEQ(ds, 41604)[wLoc04_43 * 0x0A] = 0x00;
		SEQ(ds, 41606)[wLoc04_43 * 0x0A] = 0x00;
	}
	*((word32) ds + 0x0000A34E) = 0x00;
	*((word32) ds + 41804) = 0x00;
	*((word32) ds + 41810) = 0x00;
	*((word32) ds + 41808) = 0x00;
	*((word32) ds + 41812) = 0x00;
	*((word32) ds + 0x0000A388) = 0x00;
	((word32) ds + 31898)->u0 = 0x00;
}

// 1D10:1A65: void fn1D10_1A65(Register Eq_2 ds, Stack word16 wArg04, Stack word16 wArg06)
// Called from:
//      fn0CE0_08FC
void fn1D10_1A65(Eq_2 ds, word16 wArg04, word16 wArg06)
{
	*((word32) ds + 41846) = 0x01;
	*((word32) ds + 41848) = 0x0A;
	*((word32) ds + 0x0000A37A) = 0x0A;
	*((word32) ds + 0x0000A37C) = wArg04;
	*((word32) ds + 41854) = wArg06;
}

// 1D10:1A88: void fn1D10_1A88(Register Eq_2 ds)
// Called from:
//      fn0CE0_08FC
void fn1D10_1A88(Eq_2 ds)
{
	*((word32) ds + 41846) = 0x00;
}

// 1D10:1A8F: void fn1D10_1A8F(Stack word16 wArg04, Stack cui16 wArg06, Stack wchar_t wArg08, Stack wchar_t wArg0A, Stack Eq_2 dwArg0C, Stack Eq_16658 wArg10, Stack word16 wArg12)
// Called from:
//      fn1D10_1153
void fn1D10_1A8F(word16 wArg04, cui16 wArg06, wchar_t wArg08, wchar_t wArg0A, Eq_2 dwArg0C, Eq_16658 wArg10, word16 wArg12)
{
	Eq_2 dwLoc12_159 = dwArg0C;
	wchar_t wLoc06_160 = 0x00;
	Eq_722 dwLoc0E_164 = SEQ(wArg12, (word16) wArg10.u0 + (word16) ((int32) wArg06 *s 0x0140) + wArg04);
	while (true)
	{
		word16 wLoc0C_202 = SLICE(dwLoc0E_164, word16, 16);
		word16 wLoc0E_208 = (word16) dwLoc0E_164;
		if (wLoc06_160 >= wArg0A)
			break;
		Eq_722 dwLoc0A_165 = dwLoc0E_164;
		wchar_t wLoc04_166 = 0x00;
		while (true)
		{
			word16 wLoc0A_185 = (word16) dwLoc0A_165;
			word16 wLoc08_217 = SLICE(dwLoc0A_165, word16, 16);
			word16 wLoc12_175 = (word16) dwLoc12_159;
			word16 wLoc10_178 = SLICE(dwLoc12_159, word16, 16);
			if (wLoc04_166 >= wArg08)
				break;
			Eq_17769 ax_137;
			Eq_2 al_50 = *dwLoc12_159;
			Eq_2 dwLoc12_179 = SEQ(wLoc10_178, wLoc12_175 + 0x01);
			if ((al_50 & 0x80) != 0x00)
			{
				word16 dx_252;
				struct Eq_17802 * es_253;
				fn0800_3556(dwLoc0A_165, (byte) (uint16) *dwLoc12_179, ((uint16) al_50 & 0x7F) + 0x01, out dx_252, out es_253);
				ax_137 = (uint16) al_50 & 0x7F;
				dwLoc12_159 = SEQ(wLoc10_178, wLoc12_175 + 0x02);
				dwLoc0A_165 = SEQ(wLoc08_217, wLoc0A_185 + (((uint16) al_50 & 0x7F) + 0x01));
			}
			else
			{
				word16 dx_251;
				fn0800_350E(dwLoc0A_165, dwLoc12_179, (uint16) al_50 + 0x01, out dx_251);
				ax_137.u1 = (uint16) al_50;
				dwLoc12_159 = SEQ(wLoc10_178, wLoc12_175 + 0x01 + ((uint16) al_50 + 0x01));
				dwLoc0A_165 = SEQ(wLoc08_217, wLoc0A_185 + ((uint16) al_50 + 0x01));
			}
			wLoc04_166 += (word16) ax_137.u1 + 1;
		}
		++wLoc06_160;
		dwLoc0E_164 = SEQ(wLoc0C_202, wLoc0E_208 + 0x0140);
	}
}

