// ZORTON_21CC.c
// Generated by decompiling ZORTON.EXE
// using Reko decompiler version 0.9.2.3.

#include "ZORTON_21CC.h"

// 21CC:0052: Register word16 fn21CC_0052(Stack Eq_2 ptrArg04)
// Called from:
//      fn1D10_1153
word16 fn21CC_0052(Eq_2 ptrArg04)
{
	byte cl_26 = *ptrArg04;
	byte ch_28 = *((word32) ptrArg04 + 1);
	byte bLoc04_500 = 0x0A;
	struct Eq_23844 * ds_24 = SLICE(ptrArg04, selector, 16);
	word16 si_25 = (word16) ptrArg04;
	if ((cl_26 | ch_28) != 0x00)
		ch_28 = SLICE((uint16) fn21CC_0156(0x0A, 228, 0x8C, (int16) cl_26, (int16) ch_28, 0xA0000000), byte, 8);
	byte cl_95 = *((word32) ptrArg04 + 2);
	byte cl_274 = cl_95;
	word16 cx_467 = SEQ(ch_28, cl_95);
	if (cl_95 != 0x00)
	{
		struct Eq_23877 Eq_23844::* si_100 = si_25 + 0x04;
		do
		{
			byte v20_111 = bLoc04_500 + (ds_24->*si_100).t0000;
			struct Eq_23996 Eq_23844::* si_106 = si_100 + 1;
			uint16 wLoc04_503 = (uint16) v20_111;
			byte dh_107 = (ds_24->*si_106).b0000;
			si_100 = (struct Eq_23877 Eq_23844::*) (si_106 + 1);
			Eq_23915 di_133 = (wLoc04_503 << 0x08) + (wLoc04_503 << 0x06) + 0x0A;
			dh_251 = dh_107;
			do
			{
				byte dh_251;
				si_100 = (struct Eq_23877 Eq_23844::*) &si_100->b0001;
				word16 cx_167 = SEQ((ds_24->*si_100).t0000, cl_274);
				di_159 = di_133;
				do
				{
					byte ch_234;
					Eq_23915 di_159;
					struct Eq_23897 Eq_23844::* si_154 = &si_100->b0001;
					byte ch_208 = SLICE(cx_167, byte, 8);
					byte bh_155 = (ds_24->*si_154).b0000;
					si_100 = (struct Eq_23877 Eq_23844::*) &si_154->b0001;
					di_159 = (word16) di_159 + (uint16) (ds_24->*si_100).t0000;
					if ((bh_155 & 0x80) != 0x00)
					{
						cu16 cx_211 = (SEQ(ch_208, bh_155) & 0x7F) + 0x01;
						byte al_213 = (ds_24->*si_154).b0001;
						si_100 = (struct Eq_23877 Eq_23844::*) (&si_154->b0001 + 1);
						uint16 cx_216 = cx_211 >> 0x01;
						word16 ax_331 = SEQ(al_213, al_213);
						if (cx_211 >> 0x01 < 0x00)
						{
							0xA000->*di_159 = al_213;
							di_159 = (word16) di_159 + 1;
							ax_331 = SEQ(al_213, al_213);
						}
						if (cx_211 >> 0x01 != 0x00)
						{
							for (; cx_216 != 0x00; --cx_216)
							{
								0xA000->*di_159 = ax_331;
								di_159 = (word16) di_159 + 2;
							}
						}
						ch_234 = SLICE(cx_167, byte, 8);
						cl_274 = (byte) cx_167;
					}
					else
					{
						uint16 cx_175 = (uint16) bh_155 + 0x01 >> 0x01;
						if (cx_175 < 0x00)
						{
							0xA000->*di_159 = (ds_24->*si_154).b0001;
							si_100 = (struct Eq_23877 Eq_23844::*) (&si_154->b0001 + 1);
							di_159 = (word16) di_159 + 1;
						}
						if (cx_175 != 0x00)
						{
							for (; cx_175 != 0x00; --cx_175)
							{
								0xA000->*di_159 = (ds_24->*si_100).t0000;
								++si_100;
								di_159 = (word16) di_159 + 2;
							}
						}
						ch_234 = SLICE(cx_167, byte, 8);
						cl_274 = (byte) cx_167;
					}
					byte ch_237 = ch_234 - 0x01;
					cx_167 = SEQ(ch_237, cl_274);
				} while (ch_237 != 0x00);
				di_133 = (word16) di_133.u0 + 320;
				--dh_251;
			} while (dh_251 != 0x00);
			--cl_274;
			bLoc04_500 = v20_111 + dh_107;
			cx_467 = SEQ(ch_237, cl_274);
		} while (cl_274 != 0x00);
	}
	return cx_467;
}

// 21CC:0156: Register byte fn21CC_0156(Stack cui16 wArg04, Stack word16 wArg08, Stack cui16 wArg0A, Stack int16 wArg0C, Stack int16 wArg0E, Stack Eq_23867 ptrArg10)
// Called from:
//      fn21CC_0052
byte fn21CC_0156(cui16 wArg04, word16 wArg08, cui16 wArg0A, int16 wArg0C, int16 wArg0E, Eq_23867 ptrArg10)
{
	ci8 bArg0C = (byte) wArg0C;
	ci8 bArg0E = (byte) wArg0E;
	word16 cx_178;
	struct Eq_24035 * ds_22 = SLICE(ptrArg10, selector, 16);
	Eq_24037 bx_45 = (wArg04 << 0x06) + (wArg04 << 0x08) + wArg04 + (word16) ptrArg10;
	if (bArg0C >= 0x00)
	{
		ui16 si_197 = (word16) bx_45.u0 + wArg08;
		Eq_24056 di_199 = si_197 - 0x01;
		ui16 si_200 = si_197 - 0x01 - wArg0C;
		if (bArg0E >= 0x00)
		{
			ui16 ax_282 = (wArg0A - 0x01 << 0x08) + (wArg0A - 0x01 << 0x06);
			Eq_24122 si_302 = si_200 + ax_282 - ((wArg0E << 0x08) + (wArg0E << 0x06));
			Eq_24130 di_320 = si_197 - 0x01 + ax_282 + ((wArg0E << 0x08) + (wArg0E << 0x06));
			cui16 dx_322 = wArg0A - wArg0E;
			word16 cx_324 = wArg08 - wArg0C;
			do
			{
				word16 cx_329 = cx_324;
				si_369 = si_302;
				di_372 = di_320;
				while (true)
				{
					Eq_24130 di_372;
					Eq_24122 si_369;
					if (cx_329 == 0x00)
						break;
					ds_22->*di_372 = ds_22->*si_369;
					--si_369;
					--di_372;
					--cx_329;
				}
				cx_178 = cx_324;
				si_302 -= 0x0140;
				di_320 -= 0x0140;
				--dx_322;
			} while (dx_322 != 0x00);
		}
		else
		{
			cui16 ax_204 = -wArg0E;
			Eq_24102 si_221 = si_200 + ((ax_204 << 0x08) + (ax_204 << 0x06));
			cui16 dx_223 = wArg0A + wArg0E;
			word16 cx_225 = wArg08 - wArg0C;
			do
			{
				word16 cx_230 = cx_225;
				si_257 = si_221;
				di_260 = di_199;
				while (true)
				{
					Eq_24056 di_260;
					Eq_24102 si_257;
					if (cx_230 == 0x00)
						break;
					ds_22->*di_260 = ds_22->*si_257;
					--si_257;
					--di_260;
					--cx_230;
				}
				cx_178 = cx_225;
				si_221 = (word16) si_221.u0 + 320;
				di_199 = (word16) di_199.u0 + 320;
				--dx_223;
			} while (dx_223 != 0x00);
		}
	}
	else
	{
		Eq_24037 di_102 = bx_45;
		ui16 si_52 = (word16) bx_45.u0 + -wArg0C;
		if (bArg0E >= 0x00)
		{
			ui16 ax_132 = (wArg0A - 0x01 << 0x08) + (wArg0A - 0x01 << 0x04);
			Eq_24086 di_134 = (word16) bx_45.u0 + ax_132;
			Eq_24088 si_152 = si_52 + ax_132 - ((wArg0E << 0x08) + (wArg0E << 0x06));
			cui16 dx_154 = wArg0A - wArg0E;
			word16 cx_156 = wArg08 + wArg0C;
			do
			{
				word16 cx_161 = cx_156;
				si_188 = si_152;
				di_191 = di_134;
				while (true)
				{
					Eq_24086 di_191;
					Eq_24088 si_188;
					if (cx_161 == 0x00)
						break;
					ds_22->*di_191 = ds_22->*si_188;
					si_188 = (word16) si_188 + 1;
					di_191 = (word16) di_191 + 1;
					--cx_161;
				}
				cx_178 = cx_156;
				si_152 -= 0x0140;
				di_134 -= 0x0140;
				--dx_154;
			} while (dx_154 != 0x00);
		}
		else
		{
			cui16 ax_56 = -wArg0E;
			Eq_24066 si_101 = si_52 + ((ax_56 << 0x08) + (ax_56 << 0x06));
			word16 dx_105 = wArg0A + wArg0E;
			word16 cx_77 = wArg08 + wArg0C;
			do
			{
				word16 cx_116 = cx_77;
				si_109 = si_101;
				di_112 = di_102;
				while (true)
				{
					Eq_24037 di_112;
					Eq_24066 si_109;
					if (cx_116 == 0x00)
						break;
					ds_22->*di_112 = ds_22->*si_109;
					si_109 = (word16) si_109 + 1;
					di_112 = (word16) di_112 + 1;
					--cx_116;
				}
				cx_178 = cx_77;
				si_101 = (word16) si_101.u0 + 320;
				di_102 = (word16) di_102.u0 + 320;
				--dx_105;
			} while (dx_105 != 0x00);
		}
	}
	return SLICE(cx_178, byte, 8);
}

// 21CC:037E: Register Eq_24244 fn21CC_037E(Sequence Eq_24245 ds_si, Register Eq_24244 eax, Register (memptr (ptr16 Eq_12853) Eq_24246) di, Register (ptr16 Eq_12853) es)
// Called from:
//      fn21CC_03CC
Eq_24244 fn21CC_037E(Eq_24245 ds_si, Eq_24244 eax, struct Eq_24246 Eq_12853::* di, struct Eq_12853 * es)
{
	uint16 dx_10 = *ds_si;
	word16 cx_11;
	for (cx_11 = 0x04; cx_11 != 0x00; --cx_11)
	{
		uint16 dx_14 = dx_10 >> 0x01;
		word32 eax_55 = __ror(SEQ(SLICE(__ror(SEQ(SLICE(__ror(SEQ(SLICE(__ror(SEQ(eax_24_8, Mem20[SLICE(cond(dx_14), bool, 1) + 0x02 + ds_si:byte]), 0x08), word24, 8), Mem20[SLICE(cond(dx_14 >>u 0x01), bool, 1) + 0x02 + ds_si:byte]), 0x08), word24, 8), Mem20[SLICE(cond(dx_14 >>u 0x02), bool, 1) + 0x02 + ds_si:byte]), 0x08), word24, 8), Mem20[SLICE(cond(dx_14 >>u 0x03), bool, 1) + 0x02 + ds_si:byte]), 0x08);
		(es->*di).dw0000 = eax_55;
		dx_10 = dx_14 >> 0x03;
		eax_24_8 = SLICE(eax_55, word24, 8);
		++di;
	}
	return eax_55;
}

// 21CC:03CC: Register word16 fn21CC_03CC(Register word16 eax_16_16, Stack Eq_2 ptrArg04)
// Called from:
//      fn1D10_1153
word16 fn21CC_03CC(word16 eax_16_16, Eq_2 ptrArg04)
{
	byte cl_27 = *ptrArg04;
	struct Eq_24246 Eq_12853::* di_162 = &Eq_12853::t0C8A;
	struct Eq_24329 * ds_25 = SLICE(ptrArg04, selector, 16);
	byte Eq_24329::* si_111 = (word16) ptrArg04 + 0x01;
	byte cl_170 = cl_27;
	word16 cx_280 = SEQ(ch, cl_27);
	if (cl_27 != 0x00)
	{
		do
		{
			byte dl_36 = ds_25->*si_111;
			byte Eq_24329::* si_37 = si_111 + 1;
			uint16 ax_43 = (uint16) (dl_36 << 0x02);
			si_111 = si_37 + 1;
			di_162 += ((ax_43 << 0x08) + (ax_43 << 0x06)) / 320;
			word16 dx_202 = SEQ(ds_25->*si_37, dl_36);
			do
			{
				++si_111;
				word16 cx_192 = SEQ(ds_25->*si_111, cl_170);
				di_110 = di_162;
				do
				{
					word32 eax_101;
					struct Eq_24246 Eq_12853::* di_110;
					uint16 ax_68 = (uint16) (ds_25->*si_111);
					byte Eq_24329::* si_66 = si_111 + 1;
					di_110 += (ax_68 << 0x02) / 320;
					byte al_72 = ds_25->*si_66;
					si_111 = si_66 + 1;
					Eq_24244 eax_24_8_132 = SEQ(eax_16_16, SLICE(ax_68 << 0x02, byte, 8));
					if ((al_72 & 0x80) != 0x00)
					{
						uint16 cx_122 = (uint16) ((al_72 & 0x7F) + 0x01);
						do
						{
							eax_101 = fn21CC_037E(&(ds_25->*(si_66 + 1)), eax_24_8_132, di_110, 0xA000);
							eax_24_8_132.u0 = SLICE(eax_101, word24, 8);
							di_110 = &di_110->dw0000 + 1;
							cx_122 = cx_309 - 0x01;
							cx_309 = cx_122;
						} while (cx_309 != 0x01);
						si_111 = si_66 + 5;
					}
					else
					{
						uint16 cx_113 = (uint16) al_72;
						do
						{
							eax_101 = fn21CC_037E(&(ds_25->*si_111), eax_24_8_132, di_110, 0xA000);
							eax_24_8_132.u0 = SLICE(eax_101, word24, 8);
							di_110 = &di_110->dw0000 + 1;
							si_111 += 4;
							cx_113 = cx_308 - 0x01;
							cx_308 = cx_113;
						} while (cx_308 != 0x01);
					}
					byte ch_156 = SLICE(cx_192, byte, 8);
					cl_170 = (byte) cx_192;
					eax_16_16 = SLICE(eax_101, word16, 16);
					byte dl_198 = (byte) dx_202;
					byte dh_164 = SLICE(dx_202, byte, 8);
					cx_192 = SEQ(ch_156 - 0x01, cl_170);
				} while (ch_156 != 0x01);
				di_162 += 4;
				dx_202 = SEQ(dh_164 - 0x01, dl_198);
			} while (dh_164 != 0x01);
			--cl_170;
			cx_280 = SEQ(ch_156 - 0x01, cl_170 - 0x01);
		} while (cl_170 != 0x01);
	}
	return cx_280;
}

// 21CC:045A: Register uint16 fn21CC_045A(Stack Eq_2 ptrArg04)
// Called from:
//      fn1D10_1153
uint16 fn21CC_045A(Eq_2 ptrArg04)
{
	union Eq_24461 Eq_12853::* di_117 = &Eq_12853::t0C8A;
	struct Eq_24463 * ds_142 = SLICE(ptrArg04, selector, 16);
	union Eq_24465 Eq_24463::* si_143 = (word16) ptrArg04;
	word16 bx_121;
	for (bx_121 = 0x8C; bx_121 != 0x00; --bx_121)
	{
		ci16 dx_31 = 228;
		di_151 = di_117;
		do
		{
			uint16 cx_207;
			union Eq_24461 Eq_12853::* di_151;
			byte al_35 = ds_142->*si_143;
			si_143 = (union Eq_24465 Eq_24463::*) ((char *) si_143 + 1);
			if ((al_35 & 0x80) != 0x00)
			{
				uint16 cx_71 = (uint16) (al_35 & 0x7F);
				cx_207 = cx_71 + 0x01;
				byte al_73 = ds_142->*si_143;
				si_143 = (union Eq_24465 Eq_24463::*) ((char *) si_143 + 1);
				dx_31 -= cx_71 + 0x01;
				if (al_73 == 0x00)
					di_151 = (union Eq_24461 Eq_12853::*) ((char *) di_151 + (cx_71 + 0x01));
				else
				{
					cx_207 = cx_71 + 0x01 >> 0x01;
					word16 ax_153 = SEQ(al_73, al_73);
					if (cx_207 < 0x00)
					{
						0xA000->*di_151 = al_73;
						di_151 = (union Eq_24461 Eq_12853::*) ((char *) di_151 + 1);
						ax_153 = SEQ(al_73, al_73);
					}
					for (; cx_207 != 0x00; --cx_207)
					{
						0xA000->*di_151 = ax_153;
						di_151 = (union Eq_24461 Eq_12853::*) ((char *) di_151 + 2);
					}
				}
			}
			else
			{
				uint16 cx_42 = (uint16) al_35;
				dx_31 -= cx_42 + 0x01;
				cx_207 = cx_42 + 0x01 >> 0x01;
				if (cx_207 < 0x00)
				{
					0xA000->*di_151 = ds_142->*si_143;
					si_143 = (union Eq_24465 Eq_24463::*) ((char *) si_143 + 1);
					di_151 = (union Eq_24461 Eq_12853::*) ((char *) di_151 + 1);
				}
				if (cx_207 != 0x00)
				{
					for (; cx_207 != 0x00; --cx_207)
					{
						0xA000->*di_151 = ds_142->*si_143;
						si_143 = (union Eq_24465 Eq_24463::*) ((char *) si_143 + 2);
						di_151 = (union Eq_24461 Eq_12853::*) ((char *) di_151 + 2);
					}
				}
			}
		} while (dx_31 > 0x00);
		di_117 = (union Eq_24461 Eq_12853::*) ((char *) di_117 + 320);
	}
	return cx_207;
}

// 21CC:04BE: Register word16 fn21CC_04BE(Stack Eq_2 ptrArg04)
// Called from:
//      fn1D10_1153
word16 fn21CC_04BE(Eq_2 ptrArg04)
{
	struct Eq_24568 * ds_67 = SLICE(ptrArg04, selector, 16);
	word32 Eq_24568::* si_58 = (word16) ptrArg04;
	word32 Eq_12853::* di_24 = &Eq_12853::t0C8A;
	word16 cx_25 = 0x8C;
	do
	{
		word16 cx_35 = 0x39;
		di_61 = di_24;
		while (true)
		{
			word32 Eq_12853::* di_61;
			if (cx_35 == 0x00)
				break;
			0xA000->*di_61 = ds_67->*si_58;
			++si_58;
			++di_61;
			--cx_35;
		}
		di_24 += 80;
		cx_25 = cx_101 - 0x01;
		cx_101 = cx_25;
	} while (cx_101 != 0x01);
	return cx_25;
}

// 21CC:05CB: Register word16 fn21CC_05CB(Stack Eq_2 ptrArg04)
// Called from:
//      fn1D10_1153
word16 fn21CC_05CB(Eq_2 ptrArg04)
{
	word16 si_26 = (word16) ptrArg04;
	struct Eq_24603 * ds_25 = SLICE(ptrArg04, selector, 16);
	struct Eq_24605 Eq_12853::* di_233 = &Eq_12853::t0C8A;
	byte bh_27 = *ptrArg04;
	struct Eq_24611 Eq_24603::* si_101 = si_26 + 0x01;
	cui16 ax_487 = 0xA000;
	if ((bh_27 & 0x01) != 0x00)
	{
		si_101 = si_26 + 500;
		ax_487 = 499;
	}
	word16 cx_239;
	cu16 dx_266 = 0x00;
	cui16 ax_481 = ax_487;
	for (cx_239 = 0x8C; cx_239 != 0x02; cx_239 -= 0x02)
	{
		word16 cx_213 = 228;
		di_116 = di_233;
		do
		{
			struct Eq_24605 Eq_12853::* di_116;
			byte ah_90 = SLICE(ax_481, byte, 8);
			byte al_76 = (byte) ax_481;
			if ((bh_27 & 0x01) != 0x00)
			{
				if ((dx_266 & 0x07) == 0x00)
				{
					Eq_24663 ax_69 = dx_266 >> 0x03;
					ah_90 = SLICE((word32) ax_69 + 1, byte, 8);
					al_76 = (byte) *((word32) ptrArg04 + ((word32) ax_69 + 1));
				}
				uint8 al_83 = al_76 << 0x01;
				++dx_266;
				ax_481 = SEQ(ah_90, al_83);
				if (al_83 < 0x00)
					goto l21CC_0626;
				ax_481 = SEQ(ah_90, al_83);
			}
			else
			{
l21CC_0626:
				struct Eq_24628 Eq_24603::* si_103 = si_101 + 1;
				byte al_102 = (ds_25->*si_101).b0000;
				byte ah_104 = (ds_25->*si_103).b0000;
				bcu8 bl_106 = (ds_25->*si_103).b0001;
				si_101 = (struct Eq_24611 Eq_24603::*) (&si_103->b0001 + 1);
				if (bl_106 >> 0x01 < 0x00)
					(0xA000->*di_116).b0000 = ah_104;
				else
					(0xA000->*di_116).b0000 = al_102;
				if (bl_106 >> 0x02 < 0x00)
					(0xA000->*di_116).b0001 = ah_104;
				else
					(0xA000->*di_116).b0001 = al_102;
				if (bl_106 >> 0x03 < 0x00)
					(0xA000->*di_116).b0002 = ah_104;
				else
					(0xA000->*di_116).b0002 = al_102;
				if (bl_106 >> 0x04 < 0x00)
					(0xA000->*di_116).b0003 = ah_104;
				else
					(0xA000->*di_116).b0003 = al_102;
				if (bl_106 >> 0x05 < 0x00)
					di_116[80] = ah_104;
				else
					di_116[80] = al_102;
				if (bl_106 >> 0x06 < 0x00)
					(0xA000->*di_116).b0141 = ah_104;
				else
					(0xA000->*di_116).b0141 = al_102;
				if (bl_106 >> 0x07 < 0x00)
					(0xA000->*di_116).b0142 = ah_104;
				else
					(0xA000->*di_116).b0142 = al_102;
				if (bl_106 >> 0x08 < 0x00)
					(0xA000->*di_116).b0143 = ah_104;
				else
					(0xA000->*di_116).b0143 = al_102;
			}
			word16 cx_223 = cx_213 - 0x03;
			++di_116;
			cx_213 = cx_223 - 0x01;
		} while (cx_223 != 0x01);
		di_233 += 0x00A0;
	}
	return cx_239;
}

// 21CC:06C8: Register word16 fn21CC_06C8(Register word24 ebx_24_8, Stack Eq_2 ptrArg04, Register out Eq_16724 edxOut, Register out Eq_16725 ebxOut)
// Called from:
//      fn1D10_1153
word16 fn21CC_06C8(word24 ebx_24_8, Eq_2 ptrArg04, union Eq_16724 & edxOut, union Eq_16725 & ebxOut)
{
	word16 ebx_16_16_340 = SLICE(ebx_24_8, word16, 8);
	if (seg21CC->w07B3 != 0x04D2 || seg21CC->w07B9 != 0x10E1)
	{
		word16 Eq_12853::* di_293 = Eq_12853::a0000;
		word16 cx_295;
		for (cx_295 = 0x8000; cx_295 != 0x00; --cx_295)
		{
			0xA000->*di_293 = ~0x00;
			++di_293;
		}
		while (true)
			;
	}
	else
	{
		word16 si_33 = (word16) ptrArg04;
		struct Eq_24790 * ds_32 = SLICE(ptrArg04, selector, 16);
		uint8 ah_176 = 0xA0;
		struct Eq_24794 Eq_12853::* di_122 = &Eq_12853::t0C8A;
		struct Eq_24796 Eq_24790::* si_160 = si_33 + 0x01;
		if ((*ptrArg04 & 0x01) == 0x00)
		{
			word16 cx_131 = 0x46;
			do
			{
				seg21CC->w07B7 = (word16 *) cx_131;
				word16 cx_124;
				for (cx_124 = 0x39; cx_124 != 0x00; --cx_124)
				{
					word16 ax_46 = (ds_32->*si_160).t0000;
					ui32 ebx_49 = SEQ(ebx_24_8, si_160[2]);
					uint8 ah_58 = SLICE(ax_46, byte, 8);
					ui32 edx_57 = (seg21CC->*SEQ(SLICE(ebx_49 & 0x0F, byte, 8), (byte) (ebx_49 & 0x0F) << 0x02)).dw0006;
					uint8 al_69 = (byte) ax_46;
					seg21CC->w07B5 = (word16 *) SEQ(al_69, al_69);
					ui32 ebx_68 = SEQ(SEQ(SLICE(ebx_49 & 0x0F, word16, 16), ah_58, ah_58), ah_58, ah_58) & edx_57;
					ui32 eax_81 = SEQ(SEQ(eax_16_16, al_69, al_69), seg21CC->w07B5) & ~edx_57 | ebx_68;
					(0xA000->*di_122).dw0000 = eax_81;
					word16 ax_85 = (ds_32->*si_160).t0000;
					ui32 ebx_89 = SEQ(SLICE(ebx_68, word24, 8), si_160[2]);
					uint8 ah_97 = SLICE(ax_85, byte, 8);
					ui32 edx_96 = (seg21CC->*SEQ(SLICE(ebx_89 & 0xF0, byte, 8), (byte) (ebx_89 & 0xF0) >> 0x02)).dw0006;
					uint8 al_108 = (byte) ax_85;
					seg21CC->w07B5 = (word16 *) SEQ(al_108, al_108);
					Eq_16725 ebx_107 = SEQ(SEQ(SLICE(ebx_89 & 0xF0, word16, 16), ah_97, ah_97), ah_97, ah_97) & edx_96;
					Eq_16724 edx_116 = ~edx_96;
					ui32 eax_120 = SEQ(SEQ(SLICE(eax_81, word16, 16), al_108, al_108), seg21CC->w07B5) & edx_116 | ebx_107;
					(0xA000->*di_122).dw0140 = eax_120;
					si_160 += 3;
					ebx_24_8 = SLICE(ebx_107, word24, 8);
					eax_16_16 = SLICE(eax_120, word16, 16);
					di_122 = &di_122->dw0000 + 1;
				}
				word16 cx_130 = seg21CC->w07B7;
				++di_122;
				cx_131 = cx_130 - 0x01;
			} while (cx_130 != 0x01);
			edxOut = edx_116;
			ebxOut = ebx_107;
			return cx_130 - 0x01;
		}
		else
		{
			byte al_148 = *((word32) ptrArg04 + 1);
			word16 cx_149 = 0x46;
			byte dl_156 = 0x00;
			byte dh_173 = 0x00;
			word16 edx_16_16_392 = 0x00;
			Eq_16725 ebx_420 = SEQ(ebx_16_16_340, si_33 + 500);
			do
			{
				seg21CC->w07B7 = (word16 *) cx_149;
				word16 cx_155;
				for (cx_155 = 0x39; cx_155 != 0x00; --cx_155)
				{
					while (true)
					{
						struct Eq_24976 Eq_24790::* bx_179 = (word16) ebx_420;
						cu8 dl_157 = dl_156 + 0x01;
						word16 ebx_16_16_183 = SLICE(ebx_420, word16, 16);
						byte bh_184 = SLICE(bx_179, byte, 8);
						word16 dx_174 = SEQ(dh_173, dl_157);
						if (dl_157 < 0x09)
							break;
						++si_160;
						al_148 = (ds_32->*si_160).t0000;
						dl_156 = 0x00;
						dh_173 = 0x00;
						edx_16_16_392 = 0x00;
					}
					uint8 al_169 = al_148 << 0x01;
					word16 ax_177 = SEQ(ah_176, al_169);
					ui32 eax_417 = SEQ(eax_16_16, ah_176, al_169);
					Eq_16724 edx_423 = SEQ(edx_16_16_392, dh_173, dl_157);
					if (al_169 < 0x00)
					{
						seg21CC->ptr004A = (struct Eq_24796 *) si_160;
						seg21CC->w0046 = (word16 *) dx_174;
						seg21CC->w004E = (word16 *) ax_177;
						word16 ax_181 = (ds_32->*bx_179).w0000;
						ui32 ebx_185 = SEQ(ebx_16_16_183, bh_184, (ds_32->*bx_179).b0002);
						uint8 ah_194 = SLICE(ax_181, byte, 8);
						ui32 edx_193 = (seg21CC->*SEQ(SLICE(ebx_185 & 0x0F, byte, 8), (byte) (ebx_185 & 0x0F) << 0x02)).dw0006;
						uint8 al_205 = (byte) ax_181;
						seg21CC->w07B5 = (word16 *) SEQ(al_205, al_205);
						ui32 ebx_204 = SEQ(SEQ(SLICE(ebx_185 & 0x0F, word16, 16), ah_194, ah_194), ah_194, ah_194) & edx_193;
						ui32 eax_217 = SEQ(SEQ(eax_16_16, al_205, al_205), seg21CC->w07B5) & ~edx_193 | ebx_204;
						(0xA000->*di_122).dw0000 = eax_217;
						word16 ax_221 = (ds_32->*bx_179).w0000;
						ui32 ebx_225 = SEQ(SLICE(ebx_204, word24, 8), (ds_32->*bx_179).b0002);
						uint8 ah_233 = SLICE(ax_221, byte, 8);
						ui32 edx_232 = (seg21CC->*SEQ(SLICE(ebx_225 & 0xF0, byte, 8), (byte) (ebx_225 & 0xF0) >> 0x02)).dw0006;
						uint8 al_244 = (byte) ax_221;
						seg21CC->w07B5 = (word16 *) SEQ(al_244, al_244);
						ui32 ebx_243 = SEQ(SEQ(SLICE(ebx_225 & 0xF0, word16, 16), ah_233, ah_233), ah_233, ah_233) & edx_232;
						ui32 edx_252 = ~edx_232;
						ui32 eax_256 = SEQ(SEQ(SLICE(eax_217, word16, 16), al_244, al_244), seg21CC->w07B5) & edx_252 | ebx_243;
						(0xA000->*di_122).dw0140 = eax_256;
						word16 ax_262 = seg21CC->w004E;
						word16 dx_261 = seg21CC->w0046;
						si_160 = (struct Eq_24796 Eq_24790::*) seg21CC->ptr004A;
						eax_417 = SEQ(SLICE(eax_256, word16, 16), ax_262);
						ebx_420 = SEQ(SLICE(ebx_243, word16, 16), &bx_179->b0002 + 1);
						edx_423 = SEQ(SLICE(edx_252, word16, 16), dx_261);
					}
					edx_16_16_392 = SLICE(edx_423, word16, 16);
					eax_16_16 = SLICE(eax_417, word16, 16);
					ah_176 = SLICE(eax_417, byte, 8);
					dh_173 = SLICE(edx_423, byte, 8);
					al_148 = (byte) eax_417;
					dl_156 = (byte) edx_423;
					di_122 = &di_122->dw0000 + 1;
				}
				word16 cx_273 = seg21CC->w07B7;
				++di_122;
				cx_149 = cx_273 - 0x01;
			} while (cx_273 != 0x01);
			edxOut = edx_423;
			ebxOut = ebx_420;
			return cx_273 - 0x01;
		}
	}
}

// 21CC:08A2: Register uint16 fn21CC_08A2(Stack Eq_2 ptrArg04)
// Called from:
//      fn1D10_1153
uint16 fn21CC_08A2(Eq_2 ptrArg04)
{
	byte cl_29 = *((word32) ptrArg04 + 2);
	word16 si_25 = (word16) ptrArg04;
	struct Eq_25131 * ds_28 = SLICE(ptrArg04, selector, 16);
	uint16 cx_144 = (uint16) cl_29;
	if (cl_29 != 0x00)
	{
		Eq_25137 di_36 = 0x0C8A;
		struct Eq_25139 Eq_25131::* si_117 = si_25 + 0x04;
		uint16 bp_39 = cx_144;
		byte bh_538 = 0x00;
		do
		{
			word32 eax_47 = (ds_28->*si_117).t0000;
			uint16 ax_51 = (uint16) (byte) eax_47;
			word16 eax_16_16_66 = SLICE(eax_47, word16, 16);
			si_117 += 4;
			byte al_56 = (byte) ax_51;
			uint32 eax_65 = SEQ(eax_16_16_66, ax_51);
			if (ax_51 != 0x00)
			{
				ui16 ax_61 = (ax_51 << 0x06) + SEQ(al_56, 0x00);
				di_36 = (word16) di_36 + ax_61;
				eax_65 = SEQ(eax_16_16_66, ax_61);
			}
			uint32 eax_69 = eax_65 >> 0x10;
			word16 eax_16_16_244 = SLICE(eax_69, word16, 16);
			uint16 dx_428 = (uint16) (byte) eax_69;
			do
			{
				++si_117;
				word16 bx_369 = SEQ(bh_538, (ds_28->*si_117).t0000);
				di_101 = di_36;
				do
				{
					word32 eax_319;
					Eq_25137 di_101;
					word16 ax_91 = (ds_28->*si_117).t0000;
					Eq_25232 ax_100 = (uint16) (byte) ax_91;
					bcu8 ah_93 = SLICE(ax_91, byte, 8);
					si_117 += 2;
					di_101 += ax_100;
					if ((ah_93 & 0x80) != 0x00)
					{
						byte al_242 = (ds_28->*si_117).t0000;
						bcu8 ch_251 = (ah_93 & 0x7F) + 0x01;
						byte al_247 = (ds_28->*si_117).t0000;
						Eq_25186 eax_245 = SEQ(eax_16_16_244, al_242, al_242);
						++si_117;
						uint8 ch_253 = ch_251 & 0x03;
						word16 ax_267 = SEQ(al_247, al_247);
						if ((ch_251 & 0x03) != 0x00)
						{
							uint8 ch_257 = (ch_251 & 0x03) >> 0x01;
							ax_267 = SEQ(al_247, al_247);
							if (ch_257 < 0x00)
							{
								0xA000->*di_101 = al_247;
								di_101 = (word16) di_101 + 1;
								ax_267 = SEQ(al_247, al_247);
							}
							ch_253 = ch_257 >> 0x01;
							if (ch_257 >> 0x01 < 0x00)
							{
								0xA000->*di_101 = ax_267;
								di_101 = (word16) di_101 + 2;
							}
						}
						byte al_333 = (byte) ax_267;
						cx_144 = SEQ(ch_253, ch_251 >> 0x02);
						eax_319 = SEQ(eax_245, ax_267);
						if (ch_251 >> 0x02 == 0x00)
							goto l21CC_0A00;
						eax_319 = SEQ(eax_245, ax_267);
						if ((di_101 & 0x01) != 0x00)
						{
							uint8 cl_316 = (ch_251 >> 0x02) - 0x01;
							cx_144 = SEQ(ch_253, cl_316);
							if (cl_316 == 0x00)
								goto l21CC_0977;
							word32 eax_535 = SEQ(eax_245, ax_267);
							if ((di_101 & 0x02) == 0x00)
							{
								0xA000->*di_101 = al_333;
								0xA000->*((word16) di_101 + 1) = ax_267;
								Eq_25543 di_353 = (word16) di_101 + 3;
								word32 eax_537 = SEQ(eax_245, ax_267);
								do
								{
									0xA000->*di_353 = eax_537;
									byte al_363 = (byte) ax_267;
									di_353 = (word16) di_353 + 4;
									--cx_144;
								} while (cx_144 != 0x00);
								0xA000->*di_353 = al_363;
								di_101 = (word16) di_353 + 1;
								eax_319 = SEQ(eax_245, ax_267);
							}
							else
							{
								0xA000->*di_101 = al_333;
								Eq_25534 di_335 = (word16) di_101 + 1;
								do
								{
									0xA000->*di_335 = eax_535;
									byte al_347 = (byte) ax_267;
									di_335 = (word16) di_335 + 4;
									--cx_144;
								} while (cx_144 != 0x00);
								0xA000->*di_335 = ax_267;
								0xA000->*((word16) di_335 + 2) = al_347;
								di_101 = (word16) di_335 + 3;
								eax_319 = SEQ(eax_245, ax_267);
							}
						}
						else
						{
							eax_319 = SEQ(eax_245, ax_267);
							cx_144 = SEQ(ch_253, ch_251 >> 0x02);
							if (ch_251 >> 0x02 != 0x01)
							{
								word32 eax_530 = SEQ(eax_245, ax_267);
								cx_144 = SEQ(ch_253, ch_251 >> 0x02);
								if ((di_101 & 0x02) != 0x00)
								{
									0xA000->*di_101 = ax_267;
									Eq_25585 di_302 = (word16) di_101 + 2;
									word32 eax_533 = SEQ(eax_245, ax_267);
									cx_144 = SEQ(ch_253, (ch_251 >> 0x02) - 0x01);
									do
									{
										0xA000->*di_302 = eax_533;
										di_302 = (word16) di_302 + 4;
										--cx_144;
									} while (cx_144 != 0x00);
									0xA000->*di_302 = ax_267;
									di_101 = (word16) di_302 + 2;
									eax_319 = SEQ(eax_245, ax_267);
								}
								else
								{
									do
									{
										0xA000->*di_101 = eax_530;
										di_101 = (word16) di_101 + 4;
										--cx_144;
									} while (cx_144 != 0x00);
									eax_319 = SEQ(eax_245, ax_267);
								}
							}
							else
							{
l21CC_0977:
								0xA000->*di_101 = eax_319;
								di_101 = (word16) di_101 + 4;
							}
						}
						goto l21CC_0A00;
					}
					uint8 ch_107 = ah_93 + 0x01 & 0x03;
					if (ch_107 != 0x00)
					{
						if (ch_107 >> 0x01 < 0x00)
						{
							0xA000->*di_101 = (ds_28->*si_117).t0000;
							++si_117;
							di_101 = (word16) di_101 + 1;
						}
						ch_107 >>= 0x02;
						if (ch_107 >> 0x02 < 0x00)
						{
							0xA000->*di_101 = (ds_28->*si_117).t0000;
							si_117 += 2;
							di_101 = (word16) di_101 + 2;
						}
					}
					uint8 cl_134 = ah_93 + 0x01 >> 0x02;
					cx_144 = SEQ(ch_107, cl_134);
					eax_319 = SEQ(eax_16_16_244, ax_100);
					if (cl_134 != 0x00)
					{
						if ((di_101 & 0x01) != 0x00)
						{
							cx_144 = SEQ(ch_107, cl_134 - 0x01);
							if (cl_134 == 0x01)
								goto l21CC_09E8;
							if ((di_101 & 0x02) == 0x00)
							{
								0xA000->*di_101 = (ds_28->*si_117).t0000;
								struct Eq_25318 Eq_25131::* si_221 = si_117 + 1;
								Eq_25321 di_222 = (word16) di_101 + 1;
								0xA000->*di_222 = (ds_28->*si_221).t0000;
								struct Eq_25330 Eq_25131::* si_225 = si_221 + 2;
								Eq_25333 di_226 = (word16) di_222 + 2;
								for (; cx_144 != 0x00; --cx_144)
								{
									0xA000->*di_226 = (ds_28->*si_225).t0000;
									si_225 += 4;
									di_226 = (word16) di_226 + 4;
								}
								0xA000->*di_226 = (ds_28->*si_225).t0000;
								si_117 = (struct Eq_25139 Eq_25131::*) (si_225 + 1);
								di_101 = (word16) di_226 + 1;
								eax_319 = SEQ(eax_16_16_244, ax_100);
							}
							else
							{
								0xA000->*di_101 = (ds_28->*si_117).t0000;
								struct Eq_25306 Eq_25131::* si_198 = si_117 + 1;
								Eq_25309 di_199 = (word16) di_101 + 1;
								for (; cx_144 != 0x00; --cx_144)
								{
									0xA000->*di_199 = (ds_28->*si_198).t0000;
									si_198 += 4;
									di_199 = (word16) di_199 + 4;
								}
								0xA000->*di_199 = (ds_28->*si_198).t0000;
								struct Eq_25415 Eq_25131::* si_208 = si_198 + 2;
								Eq_25418 di_209 = (word16) di_199 + 2;
								0xA000->*di_209 = (ds_28->*si_208).t0000;
								si_117 = (struct Eq_25139 Eq_25131::*) (si_208 + 1);
								di_101 = (word16) di_209 + 1;
								eax_319 = SEQ(eax_16_16_244, ax_100);
							}
						}
						else
						{
							cx_144 = SEQ(ch_107, cl_134);
							if ((di_101 & 0x02) != 0x00)
							{
								cx_144 = SEQ(ch_107, cl_134 - 0x01);
								if (cl_134 != 0x01)
								{
									0xA000->*di_101 = (ds_28->*si_117).t0000;
									struct Eq_25459 Eq_25131::* si_164 = si_117 + 2;
									Eq_25462 di_165 = (word16) di_101 + 2;
									for (; cx_144 != 0x00; --cx_144)
									{
										0xA000->*di_165 = (ds_28->*si_164).t0000;
										si_164 += 4;
										di_165 = (word16) di_165 + 4;
									}
									0xA000->*di_165 = (ds_28->*si_164).t0000;
									si_117 = (struct Eq_25139 Eq_25131::*) (si_164 + 2);
									di_101 = (word16) di_165 + 2;
									eax_319 = SEQ(eax_16_16_244, ax_100);
								}
								else
								{
l21CC_09E8:
									0xA000->*di_101 = (ds_28->*si_117).t0000;
									si_117 += 4;
									di_101 = (word16) di_101 + 4;
									eax_319 = SEQ(eax_16_16_244, ax_100);
								}
							}
							else
							{
								while (true)
								{
									eax_319 = SEQ(eax_16_16_244, ax_100);
									if (cx_144 == 0x00)
										break;
									0xA000->*di_101 = (ds_28->*si_117).t0000;
									si_117 += 4;
									di_101 = (word16) di_101 + 4;
									--cx_144;
								}
							}
						}
					}
l21CC_0A00:
					--bx_369;
					eax_16_16_244 = SLICE(eax_319, word16, 16);
					bh_538 = SLICE(bx_369, byte, 8);
				} while (bx_369 != 0x00);
				di_36 = (word16) di_36 + 320;
				--dx_428;
			} while (dx_428 != 0x00);
			--bp_39;
		} while (bp_39 != 0x00);
	}
	return cx_144;
}

