// ZORTON_1312.c
// Generated by decompiling ZORTON.EXE
// using Reko decompiler version 0.9.2.3.

#include "ZORTON_1312.h"

// 1312:1037: void fn1312_1037(Stack Eq_2 ptrArg04)
// Called from:
//      fn0CE0_08FC
void fn1312_1037(Eq_2 ptrArg04)
{
	struct Eq_12840 * ds_70 = SLICE(ptrArg04, selector, 16);
	word32 Eq_12840::* si_36 = (word16) ptrArg04 + 0x0C80;
	word32 Eq_12853::* di_37 = Eq_12853::a0C80;
	word16 cx_39;
	for (cx_39 = 14400; cx_39 != 0x00; --cx_39)
	{
		0xA000->*di_37 = ds_70->*si_36;
		++si_36;
		++di_37;
	}
}

