// ZORTON_1ED0.c
// Generated by decompiling ZORTON.EXE
// using Reko decompiler version 0.9.2.3.

#include "ZORTON_1ED0.h"

// 1ED0:0009: Register word32 fn1ED0_0009(Register Eq_2 ds, Stack Eq_2 ptrArg04, Register out Eq_2 dsOut)
// Called from:
//      fn1D10_02AE
//      fn1D10_0E66
word32 fn1ED0_0009(Eq_2 ds, Eq_2 ptrArg04, union Eq_2 & dsOut)
{
	fn0800_1109(ds, seg28BA->tA18A);
	Eq_2 dx_ax_176 = <invalid>;
	word16 cx_179;
	word16 dx_180;
	word16 bx_181;
	fn0800_06AB(ds, seg28BA->tA18A, *ptrArg04 - dx_ax_176, 0x01, out cx_179, out dx_180, out bx_181);
	Eq_2 dx_ax_177 = <invalid>;
	if (dx_ax_177 == ~0x00)
	{
		word16 dx_182;
		struct Eq_17867 * es_183;
		fn263F_04B6(0x28BA, ds, out dx_182, out es_183, out ds);
	}
	Eq_2 eax_92 = *ptrArg04;
	Eq_2 es_90 = SLICE(ptrArg04, selector, 16);
	word16 eax_16_16_162 = SLICE(eax_92, word16, 16);
	if (eax_92 != dx_ax_177)
	{
		word16 dx_184;
		struct Eq_17876 * es_185;
		fn263F_04B6(es_90, ds, out dx_184, out es_185, out ds);
	}
	dsOut = ds;
	return SEQ(eax_16_16_162, 0x00);
}

