// ZORTON_263F.c
// Generated by decompiling ZORTON.EXE
// using Reko decompiler version 0.9.2.3.

#include "ZORTON_263F.h"

// 263F:0008: Register word16 fn263F_0008(Register Eq_2 ds, Register out Eq_2 dsOut)
// Called from:
//      fn263F_00A6
word16 fn263F_0008(Eq_2 ds, union Eq_2 & dsOut)
{
	Eq_8347 bp_11 = fp - 2;
	struct Eq_29760 Eq_5151::* sp_14 = fp - 166;
	do
	{
		struct Eq_29774 Eq_5151::* sp_15 = sp_14 - 4;
		(ss->*sp_15).t0000 = ss->*((word16) bp_11 + 6);
		(ss->*sp_15).tFFFFFFFE.u0 = 0x50;
		(ss->*sp_15).tFFFFFFFC = ss;
		(ss->*sp_15).tFFFFFFFA = bp_11 - 0x54;
		fn0800_2CD5(ds, (ss->*sp_15).tFFFFFFFA, (ss->*sp_15).tFFFFFFFE, (ss->*sp_15).t0000);
		(ss->*sp_15).t0002 = ss;
		(ss->*sp_15).t0000 = bp_11 - 0x54;
		(bp_11 - 0x54)[(fn0800_3E0F((ss->*sp_15).t0000) - 0x01) / 0x0C] = 0x00;
		(ss->*sp_15).t0000 = ss->*((word16) bp_11 + 6);
		(ss->*sp_15).tFFFFFFFE.u0 = 0x50;
		(ss->*sp_15).tFFFFFFFC = ss;
		(ss->*sp_15).tFFFFFFFA = bp_11 - 0xA4;
		fn0800_2CD5(ds, (ss->*sp_15).tFFFFFFFA, (ss->*sp_15).tFFFFFFFE, (ss->*sp_15).t0000);
		(ss->*sp_15).t0002 = ss;
		(ss->*sp_15).t0000 = bp_11 - 0xA4;
		(bp_11 - 0xA4)[(fn0800_3E0F((ss->*sp_15).t0000) - 0x01) / 0x0C] = 0x00;
		sp_14 = (struct Eq_29760 Eq_5151::*) ((char *) &sp_15->t0002 + 2);
		if ((bp_11 - 0x54 | ss) != 0x00)
		{
			(ss->*sp_15).t0002 = ss;
			(ss->*sp_15).t0000 = bp_11 - 0x04;
			(ss->*sp_15).tFFFFFFFE = ss;
			(ss->*sp_15).tFFFFFFFC = bp_11 - 0xA4;
			cui16 ax_112 = ss->*((word16) bp_11 + 0x0A);
			++ss->*((word16) bp_11 + 0x0A);
			(ss->*sp_15).tFFFFFFFA = ds;
			(ss->*sp_15).wFFFFFFF8 = (ax_112 << 0x02) + 43166;
			(ss->*sp_15).tFFFFFFF6 = ss;
			(ss->*sp_15).tFFFFFFF4 = bp_11 - 0x54;
			Eq_2 sp_134 = <invalid>;
			bp_11 = fn263F_033E(ds, (ss->*sp_15).tFFFFFFF4, out ds);
			sp_14 = (struct Eq_29760 Eq_5151::*) ((word32) sp_134 + 16);
		}
	} while ((*((word16) (ss->*((word16) bp_11 + 6)) + 2) & 0x20) == 0x00);
	word16 bp_154 = ss->*bp_11;
	dsOut = ds;
	return bp_154;
}

// 263F:00A6: Register word16 fn263F_00A6(Register Eq_2 ds, Register out (ptr16 Eq_29944) dsOut)
// Called from:
//      fn268D_034A
word16 fn263F_00A6(Eq_2 ds, struct Eq_29944 & dsOut)
{
	seg28BA->tA183 == 0x00;
	word16 ax_36 = fn0800_2D71((byte) (fp - 0x38), ds, SEQ(ds, 0x8A68), SEQ(ss, fp - 0x38), 0x00);
	while (ax_36 == 0x00)
		ax_36 = fn0800_2DA4((byte) (fp - 0x38), ds, SEQ(ss, fp - 0x38));
	struct Eq_29973 Eq_2::* bp_83;
	Eq_2 bx_84;
	Eq_2 cx_85;
	Eq_2 dx_87;
	Eq_2 ds_114;
	Eq_2 ax_82 = fn0800_1D38(ds, 65000, 0x00, out cx_85, out dx_87, out bx_84, out bp_83, out ds_114);
	*((word32) ds_114 + 0x0000A884) = dx_87;
	*((word32) ds_114 + 0x0000A882) = ax_82;
	if ((ax_82 | dx_87) == 0x00)
	{
		word16 dx_792;
		word16 bx_793;
		fn263F_043F(cx_85, dx_87, bx_84, ds_114, SEQ(ds_114, 35438), out dx_792, out bx_793, out ds_114);
	}
	(ss->*bp_83).dwFFFFFFFC -= 65000;
	(ss->*bp_83).dwFFFFFFFC -= 0x8000;
	seg28BA->tA51C = 0x00;
	seg28BA->tA51E = 0x00;
	ci16 v18_139 = seg28BA->t9804 + 0x01;
	seg28BA->t9804 = v18_139;
	if (v18_139 < 0x00)
	{
		struct Eq_30040 * ax_163 = seg28BA->t9812;
		byte Eq_30040::* bx_164 = seg28BA->t9810;
		seg28BA->t9810 = seg28BA->t9810 + 0x01;
		ax_163->*bx_164 = 0x0A;
	}
	else
		fn0800_37EE(ds_114, 0x0A, 0x28BA9804);
	Eq_2 ds_197;
	Eq_8347 bp_194 = fn263F_033E(ds_114, SEQ(ds_114, 35451), out ds_197);
	Eq_2 sp_201 = <invalid>;
	ss->*((word32) sp_201 + 0x0E) = ss;
	ss->*((word32) sp_201 + 0x0C) = bp_194 - 0x04;
	ss->*((word32) sp_201 + 0x0A) = ds_197;
	ss->*((word32) sp_201 + 8) = 35483;
	ss->*((word32) sp_201 + 6) = 0x28BA;
	ss->*((word32) sp_201 + 4) = ~0x7807;
	ss->*((word32) sp_201 + 2) = ds_197;
	(ss->*sp_201).u0 = 35473;
	Eq_2 ds_231;
	Eq_8347 bp_228 = fn263F_033E(ds_197, ss->*sp_201, out ds_231);
	Eq_2 sp_235 = <invalid>;
	ss->*((word32) sp_235 + 0x0E) = ss;
	ss->*((word32) sp_235 + 0x0C) = bp_228 - 0x04;
	ss->*((word32) sp_235 + 0x0A) = ds_231;
	ss->*((word32) sp_235 + 8) = 0x8AAA;
	ss->*((word32) sp_235 + 6) = 0x28BA;
	ss->*((word32) sp_235 + 4) = 0x87CC;
	ss->*((word32) sp_235 + 2) = ds_231;
	(ss->*sp_235).u0 = 0x8AA1;
	Eq_2 ds_265;
	Eq_8347 bp_262 = fn263F_033E(ds_231, ss->*sp_235, out ds_265);
	Eq_2 sp_269 = <invalid>;
	ss->*((word32) sp_269 + 0x0E) = ss;
	ss->*((word32) sp_269 + 0x0C) = bp_262 - 0x04;
	ss->*((word32) sp_269 + 0x0A) = ds_265;
	ss->*((word32) sp_269 + 8) = 35516;
	ss->*((word32) sp_269 + 6) = 0x28BA;
	ss->*((word32) sp_269 + 4) = 0x880E;
	ss->*((word32) sp_269 + 2) = ds_265;
	(ss->*sp_269).u0 = 35503;
	Eq_2 ds_299;
	Eq_8347 bp_296 = fn263F_033E(ds_265, ss->*sp_269, out ds_299);
	Eq_2 sp_303 = <invalid>;
	ss->*((word32) sp_303 + 0x0E) = ss;
	ss->*((word32) sp_303 + 0x0C) = bp_296 - 0x04;
	ss->*((word32) sp_303 + 0x0A) = ds_299;
	ss->*((word32) sp_303 + 8) = 35536;
	ss->*((word32) sp_303 + 6) = 0x28BA;
	ss->*((word32) sp_303 + 4) = 34742;
	ss->*((word32) sp_303 + 2) = ds_299;
	(ss->*sp_303).u0 = 35523;
	Eq_2 ds_333;
	Eq_8347 bp_330 = fn263F_033E(ds_299, ss->*sp_303, out ds_333);
	Eq_2 sp_337 = <invalid>;
	ss->*((word32) sp_337 + 0x0E) = ss;
	ss->*((word32) sp_337 + 0x0C) = bp_330 - 0x04;
	ss->*((word32) sp_337 + 0x0A) = ds_333;
	ss->*((word32) sp_337 + 8) = 35557;
	ss->*((word32) sp_337 + 6) = 0x28BA;
	ss->*((word32) sp_337 + 4) = 0x883A;
	ss->*((word32) sp_337 + 2) = ds_333;
	(ss->*sp_337).u0 = 35544;
	Eq_2 ds_367;
	Eq_8347 bp_364 = fn263F_033E(ds_333, ss->*sp_337, out ds_367);
	Eq_2 sp_371 = <invalid>;
	ss->*((word32) sp_371 + 0x0E) = ss;
	ss->*((word32) sp_371 + 0x0C) = bp_364 - 0x04;
	ss->*((word32) sp_371 + 0x0A) = ds_367;
	ss->*((word32) sp_371 + 8) = 35583;
	ss->*((word32) sp_371 + 6) = 0x28BA;
	ss->*((word32) sp_371 + 4) = 0x8824;
	ss->*((word32) sp_371 + 2) = ds_367;
	(ss->*sp_371).u0 = 35570;
	Eq_2 sp_405 = <invalid>;
	Eq_2 ds_401;
	Eq_8347 bp_398 = fn263F_033E(ds_367, ss->*sp_371, out ds_401);
	struct Eq_30298 Eq_2::* sp_413 = (word32) sp_405 + 16;
	if (seg28BA->tA183 != 0x00)
	{
		ss->*((word32) sp_405 + 0x0E) = ds_401;
		(ss->*((word32) sp_405 + 0x0C)).u0 = 0x8B05;
		Eq_2 edx_427 = <invalid>;
		Eq_2 dx_436 = (word16) edx_427;
		struct Eq_30315 Eq_2::* bp_422;
		Eq_2 bx_423;
		Eq_2 cx_424;
		word16 dx_794;
		Eq_2 ds_425;
		cui16 ax_438 = (word16) (uint32) fn209F_02E3(ds_401, ss->*((word32) sp_405 + 0x0C), out cx_424, out dx_794, out bx_423, out bp_422, out ds_425);
		*((word32) ds_425 + 0x0000A894) = dx_436;
		*((word32) ds_425 + 43154) = ax_438;
		Eq_2 sp_429 = <invalid>;
		if ((ax_438 | dx_436) == 0x00)
		{
			ss->*sp_429 = (ss->*bp_422).tFFFFFFFC;
			ss->*((word32) sp_429 - 2) = ds_425;
			(ss->*((word32) sp_429 - 4)).u0 = 0x8B0E;
			word16 dx_798;
			word16 bx_799;
			fn263F_043F(cx_424, dx_436, bx_423, ds_425, ss->*((word32) sp_429 - 4), out dx_798, out bx_799, out ds_425);
		}
		else
			(ss->*bp_422).tFFFFFFFC -= (int32) **((word32) ds_425 + 0x0000A88A);
		ss->*((word32) sp_429 + 2) = ds_425;
		(ss->*sp_429).u0 = 35633;
		Eq_2 edx_486 = <invalid>;
		Eq_2 dx_495 = (word16) edx_486;
		struct Eq_30463 Eq_2::* bp_481;
		Eq_2 bx_482;
		Eq_2 cx_483;
		word16 dx_800;
		Eq_2 ds_484;
		cui16 ax_497 = (word16) (uint32) fn209F_02E3(ds_425, ss->*sp_429, out cx_483, out dx_800, out bx_482, out bp_481, out ds_484);
		*((word32) ds_484 + 0x0000A890) = dx_495;
		*((word32) ds_484 + 0x0000A88E) = ax_497;
		Eq_2 sp_488 = <invalid>;
		if ((ax_497 | dx_495) == 0x00)
		{
			ss->*sp_488 = (ss->*bp_481).tFFFFFFFC;
			ss->*((word32) sp_488 - 2) = ds_484;
			(ss->*((word32) sp_488 - 4)).u0 = 0x8B0E;
			word16 dx_802;
			word16 bx_803;
			fn263F_043F(cx_483, dx_495, bx_482, ds_484, ss->*((word32) sp_488 - 4), out dx_802, out bx_803, out ds_484);
		}
		ss->*((word32) sp_488 + 2) = ds_484;
		(ss->*sp_488).u0 = 0x8B3A;
		Eq_2 edx_538 = <invalid>;
		Eq_2 dx_547 = (word16) edx_538;
		struct Eq_30499 Eq_2::* bp_533;
		Eq_2 bx_534;
		Eq_2 cx_535;
		word16 dx_801;
		Eq_2 ds_536;
		cui16 ax_549 = (word16) (uint32) fn209F_02E3(ds_484, ss->*sp_488, out cx_535, out dx_801, out bx_534, out bp_533, out ds_536);
		*((word32) ds_536 + 43164) = dx_547;
		*((word32) ds_536 + 0x0000A89A) = ax_549;
		Eq_2 sp_540 = <invalid>;
		if ((ax_549 | dx_547) == 0x00)
		{
			ss->*sp_540 = (ss->*bp_533).tFFFFFFFC;
			ss->*((word32) sp_540 - 2) = ds_536;
			(ss->*((word32) sp_540 - 4)).u0 = 0x8B0E;
			word16 dx_805;
			word16 bx_806;
			fn263F_043F(cx_535, dx_547, bx_534, ds_536, ss->*((word32) sp_540 - 4), out dx_805, out bx_806, out ds_536);
		}
		ss->*((word32) sp_540 + 2) = ds_536;
		(ss->*sp_540).u0 = 35651;
		Eq_2 edx_590 = <invalid>;
		Eq_2 dx_599 = (word16) edx_590;
		Eq_2 bx_586;
		Eq_2 cx_587;
		word16 dx_804;
		Eq_2 ds_588;
		cui16 ax_601 = (word16) (uint32) fn209F_02E3(ds_536, ss->*sp_540, out cx_587, out dx_804, out bx_586, out bp_398, out ds_588);
		*((word32) ds_588 + 0x0000A898) = dx_599;
		*((word32) ds_588 + 0x0000A896) = ax_601;
		Eq_2 sp_592 = <invalid>;
		if ((ax_601 | dx_599) == 0x00)
		{
			ss->*sp_592 = ss->*((word16) bp_398 - 4);
			ss->*((word32) sp_592 - 2) = ds_588;
			(ss->*((word32) sp_592 - 4)).u0 = 0x8B0E;
			word16 dx_807;
			word16 bx_808;
			fn263F_043F(cx_587, dx_599, bx_586, ds_588, ss->*((word32) sp_592 - 4), out dx_807, out bx_808, out ds_588);
		}
		ss->*((word32) sp_592 + 2) = ss;
		ss->*sp_592 = bp_398 - 0x04;
		ds_401 = fn209F_04CB(ds_588, ss->*sp_592);
		sp_413 = (struct Eq_30298 Eq_2::*) ((word32) sp_592 + 4);
	}
	struct Eq_30341 Eq_2::* sp_653 = sp_413 - 2;
	(ss->*sp_653).t0000 = ds_401;
	(ss->*sp_653).tFFFFFFFE.u0 = 0x8B56;
	(ss->*sp_653).tFFFFFFFC = ds_401;
	(ss->*sp_653).tFFFFFFFA.u0 = 35660;
	Eq_2 ds_666;
	Eq_5386 dx_667;
	word16 bx_796;
	word16 cx_795;
	Eq_2 ax_663 = fn0800_302B(ds_401, (ss->*sp_653).tFFFFFFFA, (ss->*sp_653).tFFFFFFFE, out cx_795, out dx_667, out bx_796, out ds_666);
	ss->*((word16) bp_398 - 8) = dx_667;
	ss->*((word16) bp_398 - 0x0A) = ax_663;
	(ss->*sp_653).t0000.u0 = 0x00;
	(ss->*sp_653).tFFFFFFFE = dx_667;
	(ss->*sp_653).tFFFFFFFC = ax_663;
	Eq_2 ds_691;
	struct Eq_30393 Eq_2::* bp_689 = fn263F_0008(ds_666, out ds_691);
	Eq_2 sp_693 = <invalid>;
	ss->*((word32) sp_693 + 2) = (ss->*bp_689).tFFFFFFF6;
	struct Eq_29944 * ds_709;
	word16 bx_797;
	fn0800_2B50(ds_691, ss->*((word32) sp_693 + 2), out bx_797, out ds_709);
	word16 bp_717 = (ss->*bp_689).w0000;
	dsOut = ds_709;
	return bp_717;
}

// 263F:033E: Register word16 fn263F_033E(Register Eq_2 ds, Stack Eq_2 dwArg04, Register out Eq_2 dsOut)
// Called from:
//      fn0CE0_0007
//      fn1F0F_0BF7
//      fn263F_0008
//      fn263F_00A6
word16 fn263F_033E(Eq_2 ds, Eq_2 dwArg04, union Eq_2 & dsOut)
{
	Eq_2 bx_16;
	Eq_2 cx_17;
	Eq_2 dx_18;
	Eq_2 ax_19 = fn0800_3615(ds, dwArg04, 0x8001, 0x00, out cx_17, out dx_18, out bx_16);
	if (ax_19 == ~0x00)
	{
		word16 dx_246;
		word16 bx_247;
		word16 di_248;
		fn263F_03F3(cx_17, dx_18, bx_16, ds, out dx_246, out bx_247, out di_248, out ds);
	}
	word16 cx_242;
	word16 dx_243;
	word16 bx_244;
	fn0800_06AB(ds, ax_19, 0x00, 0x02, out cx_242, out dx_243, out bx_244);
	Eq_2 dx_ax_240 = <invalid>;
	struct Eq_30670 Eq_30686::* bp_78;
	Eq_2 cx_80;
	Eq_2 dx_82;
	word16 bx_245;
	Eq_2 ds_114;
	Eq_2 ax_77 = fn0800_1D38(ds, (word16) dx_ax_240, SLICE(dx_ax_240, word16, 16), out cx_80, out dx_82, out bx_245, out bp_78, out ds_114);
	Eq_30685 es_bx_89 = (ss->*bp_78).t000A;
	*((word32) es_bx_89 + 2) = dx_82;
	*es_bx_89 = ax_77;
	if ((ax_77 | dx_82) == 0x00)
	{
		word16 dx_257;
		word16 bx_258;
		fn263F_043F(cx_80, dx_82, (ss->*bp_78).t0012, ds_114, (ss->*bp_78).t000E, out dx_257, out bx_258, out ds_114);
	}
	word16 cx_249;
	word16 dx_250;
	word16 bx_251;
	fn0800_06AB(ds_114, (ss->*bp_78).tFFFFFFFA, 0x00, 0x00, out cx_249, out dx_250, out bx_251);
	word16 cx_252;
	word16 dx_253;
	word16 bx_254;
	fn0800_3C87(ds_114, (ss->*bp_78).tFFFFFFFA, *(ss->*bp_78).t000A, (ss->*bp_78).tFFFFFFFC, out cx_252, out dx_253, out bx_254);
	Eq_915 eax_168 = (ss->*bp_78).tFFFFFFFC;
	Eq_2 es_bx_167 = (ss->*bp_78).t0012;
	*es_bx_167 -= eax_168;
	word16 dx_255;
	word16 bx_256;
	fn0800_2A93((byte) eax_168, ds_114, (ss->*bp_78).tFFFFFFFA, out dx_255, out bx_256);
	word16 bp_192 = (ss->*bp_78).w0000;
	dsOut = ds_114;
	return bp_192;
}

// 263F:03F3: Register Eq_2 fn263F_03F3(Register Eq_2 cx, Register Eq_2 dx, Register Eq_2 bx, Register Eq_2 ds, Register out Eq_2 dxOut, Register out ptr16 bxOut, Register out Eq_962 diOut, Register out Eq_2 dsOut)
// Called from:
//      fn0CE0_0007
//      fn0CE0_08FC
//      fn0E31_0002
//      fn1D10_12D4
//      fn209F_02E3
//      fn209F_08D2
//      fn2476_0630
//      fn2504_094D
//      fn263F_033E
//      fn268D_000F
//      fn268D_03E2
Eq_2 fn263F_03F3(Eq_2 cx, Eq_2 dx, Eq_2 bx, Eq_2 ds, union Eq_2 & dxOut, ptr16 & bxOut, union Eq_962 & diOut, union Eq_2 & dsOut)
{
	if ((seg28BA->t302A & 0x01) != 0x00)
	{
		cx = fn2476_03E6(0x28BA, ds, out dx, out bx, out ds);
		seg28BA->t302A = seg28BA->t302A & ~0x01;
	}
	fn0800_37D3(cx, dx, bx, ds, SEQ(ds, 35673));
	Eq_962 di_68 = fn0800_37D3(cx, dx, bx, ds, SEQ(ds, 0x8B87));
	fn0800_20A6(ds);
	ptr16 bx_89;
	struct Eq_30801 * es_121;
	dxOut = fn268D_03E2(ds, 0x01, out bx_89, out es_121);
	bxOut = bx_89;
	diOut = di_68;
	dsOut = ds;
	return 0x01;
}

// 263F:043F: Register Eq_2 fn263F_043F(Register Eq_2 cx, Register Eq_2 dx, Register Eq_2 bx, Register Eq_2 ds, Stack Eq_2524 dwArg04, Register out Eq_2 dxOut, Register out ptr16 bxOut, Register out Eq_2 dsOut)
// Called from:
//      fn0CE0_05FB
//      fn0CE0_08FC
//      fn1744_0972
//      fn209F_0149
//      fn209F_02E3
//      fn226D_00F9
//      fn2476_0282
//      fn263F_00A6
//      fn263F_033E
Eq_2 fn263F_043F(Eq_2 cx, Eq_2 dx, Eq_2 bx, Eq_2 ds, Eq_2524 dwArg04, union Eq_2 & dxOut, ptr16 & bxOut, union Eq_2 & dsOut)
{
	if ((seg28BA->t302A & 0x01) != 0x00)
	{
		cx = fn2476_03E6(0x28BA, ds, out dx, out bx, out ds);
		seg28BA->t302A = seg28BA->t302A & ~0x01;
	}
	fn0800_37D3(cx, dx, bx, ds, SEQ(ds, ~0x7461));
	fn0800_37D3(cx, dx, bx, ds, dwArg04);
	fn0800_37D3(cx, dx, bx, ds, SEQ(ds, 35779));
	Eq_2 bx_90;
	Eq_2 dx_92;
	Eq_2 cx_91 = fn0800_2056(ds, out dx_92, out bx_90);
	fn0800_37D3(cx_91, dx_92, bx_90, ds, SEQ(ds, 35813));
	fn0800_37D3(cx_91, dx_92, bx_90, ds, SEQ(ds, 0x8B87));
	fn0800_20A6(ds);
	ptr16 bx_140;
	struct Eq_30859 * es_181;
	dxOut = fn268D_03E2(ds, 0x01, out bx_140, out es_181);
	bxOut = bx_140;
	dsOut = ds;
	return 0x01;
}

// 263F:04B6: Register word16 fn263F_04B6(Register Eq_2 es, Register Eq_2 ds, Register out Eq_2 dxOut, Register out (ptr16 Eq_16465) esOut, Register out Eq_2 dsOut)
// Called from:
//      fn1D10_0FB3
//      fn1ED0_0009
//      fn2331_0000
//      fn2331_00BA
//      main
word16 fn263F_04B6(Eq_2 es, Eq_2 ds, union Eq_2 & dxOut, struct Eq_16465 & esOut, union Eq_2 & dsOut)
{
	Eq_2 bx_12;
	Eq_2 ds_15;
	Eq_2 dx_16;
	Eq_2 cx_13 = fn2476_03E6(es, ds, out dx_16, out bx_12, out ds_15);
	seg28BA->t302A = seg28BA->t302A & ~0x01;
	fn0800_37D3(cx_13, dx_16, bx_12, ds_15, SEQ(ds_15, 35838));
	fn0800_37D3(cx_13, dx_16, bx_12, ds_15, SEQ(ds_15, 0x8C08));
	struct Eq_16465 * es_70;
	word16 bx_94;
	dxOut = fn268D_03E2(ds_15, 0x01, out bx_94, out es_70);
	esOut = es_70;
	dsOut = ds_15;
	return 0x01;
}

