// ZORTON_23F8.c
// Generated by decompiling ZORTON.EXE
// using Reko decompiler version 0.9.2.3.

#include "ZORTON_23F8.h"

// 23F8:0004: Register Eq_2 fn23F8_0004(Register Eq_2 ds)
// Called from:
//      fn1ED7_000E
//      fn1F0F_000F
Eq_2 fn23F8_0004(Eq_2 ds)
{
	*((word32) ds + 34770) = ds;
	*((word32) ds + 0x000087D0) = 0x87D8;
	*((word32) ds + 0x000087EC) = ds;
	*((word32) ds + 34794) = 34754;
	*((word32) ds + 34772) = 0x00;
	*((word32) ds + 0x000087E6) = 0x00;
	seg28BA->t85E8 = 330;
	*((word32) ds + 34803) = 0x00;
	seg28BA->t85A8 = 330;
	*((word32) ds + 34803) = 0x00;
	*((word32) ds + 0x00008848) = ds;
	((word32) ds + 0x00008846)->u0 = 34754;
	Eq_2 ds_27;
	fn23F8_00A0(ds, out ds_27);
	return ds_27;
}

// 23F8:0055: void fn23F8_0055(Register Eq_2 ds, Stack Eq_18103 dwArg04)
// Called from:
//      fn1ED7_000E
//      fn1F0F_000F
void fn23F8_0055(Eq_2 ds, Eq_18103 dwArg04)
{
	Eq_18103 ptrLoc06_45 = SEQ(ds, 34754);
	do
	{
		if (*((word32) ptrLoc06_45 + 0x0E) == 0x00)
		{
			*((word32) ptrLoc06_45 + 0x0E) = dwArg04;
			*((word32) dwArg04 + 18) = ptrLoc06_45;
			((word32) dwArg04 + 0x0E)->u0 = 0x00;
			return;
		}
		Eq_18103 eax_24 = *((word32) ptrLoc06_45 + 0x0E);
		ptrLoc06_45 = eax_24;
	} while (eax_24 != dwArg04);
}

// 23F8:00A0: Register word32 fn23F8_00A0(Register Eq_2 ds, Register out (ptr16 Eq_18146) dsOut)
// Called from:
//      fn1ED7_000E
//      fn1F0F_000F
//      fn1F0F_057A
//      fn23F8_0004
//      fn23F8_01EB
word32 fn23F8_00A0(Eq_2 ds, struct Eq_18146 & dsOut)
{
	__cli();
	word32 ebx_17;
	word16 cx_254;
	struct Eq_27887 * es_256;
	word32 edx_255;
	fn2425_01E8(ds, out cx_254, out edx_255, out ebx_17, out es_256);
	__sti();
	Eq_2 v8_25 = seg28BA->tAA80;
	Eq_2 v9_30 = seg28BA->tA8B2;
	byte al_257;
	word16 bx_258;
	fn216E_01DC(0xF9, 11, v9_30, SLICE(v9_30, word16, 16), v8_25, SLICE(v8_25, word16, 16), out al_257, out bx_258);
	ci16 wLoc08_198 = 0x0E;
	word16 ebx_16_16_240 = SLICE(ebx_17, word16, 16);
	Eq_27852 dwLoc06_210 = SEQ(ds, 34754);
	while (dwLoc06_210 != *((word32) ds + 0x00008846) && *((word32) dwLoc06_210 + 0x0E) != 0x00)
	{
		*((word32) dwLoc06_210 + 5) = 0x00;
		(*((word32) dwLoc06_210 + 6))->u0 = 330;
		dwLoc06_210 = *((word32) dwLoc06_210 + 0x0E);
	}
	while (true)
	{
		Eq_2 es_100 = SLICE(dwLoc06_210, selector, 16);
		if ((word32) *((word32) dwLoc06_210 + 1) + wLoc08_198 >= 0x48 || dwLoc06_210 == 0x00)
			break;
		if (*((word32) dwLoc06_210 + 0x0A) != 0x00)
		{
			Eq_2 v16_127 = seg28BA->tAA80;
			Eq_2 v17_132 = *((word32) dwLoc06_210 + 0x0A);
			int32 dx_ax_141 = (int32) (66 - *((word32) dwLoc06_210 + 3));
			word16 bx_260;
			byte al_259;
			fn216E_01DC(((word16) dx_ax_141 - SLICE(dx_ax_141, word16, 16) >> 0x01) + 0xF9, wLoc08_198 + 11, v17_132, SLICE(v17_132, word16, 16), v16_127, SLICE(v16_127, word16, 16), out al_259, out bx_260);
		}
		struct Eq_27943 * es_bx_165 = *((word32) dwLoc06_210 + 6);
		es_bx_165->w0000 = 0xF9;
		es_bx_165->w0002 = wLoc08_198 + 11;
		es_bx_165->w0004 = 0x0125;
		*((word32) *((word32) dwLoc06_210 + 6) + 6) = (word32) *((word32) dwLoc06_210 + 1) + wLoc08_198 + 11;
		*((word32) dwLoc06_210 + 5) = 0x01;
		wLoc08_198 += (word32) *((word32) dwLoc06_210 + 1) + 2;
		dwLoc06_210 = *((word32) dwLoc06_210 + 0x0E);
	}
	while (dwLoc06_210 != 0x00)
	{
		*((word32) dwLoc06_210 + 5) = 0x00;
		(*((word32) dwLoc06_210 + 6))->u0 = 330;
		es_100 = SLICE(dwLoc06_210, selector, 16);
		dwLoc06_210 = *((word32) dwLoc06_210 + 0x0E);
	}
	__cli();
	word16 bx_103;
	struct Eq_18146 * ds_106;
	word16 cx_261;
	word16 dx_262;
	fn2425_0286(es_100, ds, out cx_261, out dx_262, out bx_103, out ds_106);
	__sti();
	dsOut = ds_106;
	return SEQ(ebx_16_16_240, bx_103);
}

// 23F8:01EB: Register Eq_2 fn23F8_01EB(Register Eq_2 ds, Stack (ptr32 Eq_19860) ptrArg04)
// Called from:
//      fn1F0F_0BF7
Eq_2 fn23F8_01EB(Eq_2 ds, struct Eq_19860 * ptrArg04)
{
	if (ptrArg04->t0012 != 0x00)
	{
		Eq_28069 dx_15 = ptrArg04->t000E;
		Eq_28064 es_bx_16 = ptrArg04->t0012;
		((word32) es_bx_16 + 16)->u0 = ptrArg04->w0010;
		*((word32) es_bx_16 + 0x0E) = dx_15;
	}
	if (ptrArg04->t000E != 0x00)
	{
		Eq_28064 dx_30 = ptrArg04->t0012;
		Eq_28069 es_bx_31 = ptrArg04->t000E;
		((word32) es_bx_31 + 20)->u0 = ptrArg04->w0014;
		*((word32) es_bx_31 + 18) = dx_30;
	}
	if (ptrArg04->b0005 != 0x00)
	{
		*ptrArg04->ptr0006 = 330;
		ptrArg04->b0005 = 0x00;
		fn23F8_00A0(ds, out ds);
	}
	return ds;
}

