// ZORTON_2864.c
// Generated by decompiling ZORTON.EXE
// using Reko decompiler version 0.9.3.0.

#include "ZORTON.h"

struct seg2864_t * g_ptr28640 = &g_t000B; // 00028640
word16 g_w0088 = 0x00; // 2864:0088
