// ZORTON_1F0F.c
// Generated by decompiling ZORTON.EXE
// using Reko decompiler version 0.9.2.3.

#include "ZORTON_1F0F.h"

// 1F0F:000F: Register Eq_2 fn1F0F_000F(Register Eq_2 ds, Stack ci16 wArg04)
// Called from:
//      fn268D_0282
Eq_2 fn1F0F_000F(Eq_2 ds, ci16 wArg04)
{
	seg2862->t0000 = 0x02;
	seg28BA->t8586 = 0x02;
	Eq_2 ds_21 = fn23F8_0004(ds);
	seg28BA->t9BE0 = ~0x00;
	Eq_18443 wLoc04_692 = 39898;
	while (wLoc04_692 < 25644)
	{
		0x28BA->*wLoc04_692 = 0x00;
		wLoc04_692 = (word16) wLoc04_692 + 1;
	}
	if (wArg04 != 0x00)
	{
		seg28BA->t3051 = 0x28BA;
		seg28BA->t304F = 0x3034;
		if (seg28BA->t3036 >= 0x06)
		{
			seg28BA->t3034 = 0x06;
			seg28BA->t3036 = seg28BA->t3036 - 0x06;
		}
		else
		{
			seg28BA->t3034 = seg28BA->t3036;
			seg28BA->t3036 = 0x00;
		}
		if ((seg28BA->tA520 & 0x04) != 0x00)
		{
			fn23F8_0055(ds_21, 683313068);
			if (seg28BA->t3048 >= 0x02)
			{
				seg28BA->t3046 = 0x02;
				seg28BA->t3048 = seg28BA->t3048 - 0x02;
			}
			else
			{
				seg28BA->t3046 = seg28BA->t3048;
				seg28BA->t3048 = 0x00;
			}
		}
		if ((seg28BA->tA520 & 0x08) != 0x00)
		{
			fn23F8_0055(ds_21, 683313134);
			if (seg28BA->t303F >= 0x06)
			{
				seg28BA->t303D = 0x06;
				seg28BA->t303F = seg28BA->t303F - 0x06;
			}
			else
			{
				seg28BA->t303D = seg28BA->t303F;
				seg28BA->t303F = 0x00;
			}
		}
		if ((seg28BA->tA520 & 0x3F00) != 0x00)
			fn23F8_0055(ds_21, 0x28BA8830);
	}
	else
	{
		seg28BA->tA520 = 0x03;
		seg28BA->tA17D = 0x00;
		seg28BA->tA17E = seg28BA->t3096;
		seg28BA->tA182 = 0x19;
		seg28BA->t3035 = 0x06;
		seg28BA->t3034 = 0x06;
		seg28BA->t3036 = 0x12;
		seg28BA->t3038 = 0x00;
		seg28BA->t303D = 0x04;
		seg28BA->t303E = 0x06;
		seg28BA->t303F = 0x00;
		seg28BA->t3046 = 0x01;
		seg28BA->t3047 = 0x02;
		seg28BA->t3048 = 0x01;
		seg28BA->t3051 = 0x28BA;
		seg28BA->t304F = 0x3034;
	}
	Eq_2 ds_230;
	word16 cx_762;
	word32 edx_763;
	word32 ebx_764;
	struct Eq_18538 Eq_18548::* bp_227;
	fn226D_00F9(ds_21, out cx_762, out edx_763, out ebx_764, out bp_227, out ds_230);
	Eq_2 sp_236 = <invalid>;
	(ss->*((word32) sp_236 - 2)).u0 = 0x00;
	fn226D_0656(ds_230, ss->*((word32) sp_236 - 2));
	Eq_2 ds_258;
	fn23F8_00A0(ds_230, out ds_258);
	Eq_2 ds_272 = fn226D_057F(ds_258);
	while ((ss->*bp_227).wFFFFFFFC < 0x1E)
	{
		fn2476_000A();
		seg28BA->t8402 = 0x00;
		Eq_2 ds_306;
		word32 edx_766;
		word32 ebx_767;
		word16 cx_765;
		struct Eq_18608 Eq_18548::* bp_303;
		fn226D_00F9(ds_272, out cx_765, out edx_766, out ebx_767, out bp_303, out ds_306);
		__cli();
		word16 cx_768;
		word32 edx_769;
		word32 ebx_770;
		struct Eq_18621 * es_771;
		fn2425_01E8(ds_306, out cx_768, out edx_769, out ebx_770, out es_771);
		__sti();
		Eq_2 sp_312 = <invalid>;
		(ss->*((word32) sp_312 - 2)).u0 = 0x00;
		fn226D_0656(ds_306, ss->*((word32) sp_312 - 2));
		Eq_2 ds_343;
		fn23F8_00A0(ds_306, out ds_343);
		Eq_2 sp_340 = sp_312;
		ds_272 = fn226D_057F(ds_343);
		if ((seg28BA->tA184 & 0x01) != 0x00)
			seg28BA->t2E1A = seg28BA->t2E1A + 0x15;
		if (seg28BA->t2E1A > 11802)
		{
			seg28BA->t2E1C = 0x28BA;
			seg28BA->t2E1A = 0x2D72;
		}
		if ((ss->*bp_303).tFFFFFFFC > 0x1B)
		{
			Eq_2 ds_398;
			fn23F8_00A0(ds_272, out ds_398);
			seg28BA->t3034 = 0x00;
			seg28BA->t3036 = 0x00;
			seg28BA->t3038 = 0x00;
			seg28BA->t303D = 0x00;
			seg28BA->t303F = 0x00;
			seg28BA->t3046 = 0x00;
			seg28BA->t3048 = 0x00;
			seg28BA->t3051 = 0x28BA;
			seg28BA->t304F = 0x3034;
			word16 cx_772;
			word32 edx_773;
			word32 ebx_774;
			fn226D_00F9(ds_398, out cx_772, out edx_773, out ebx_774, out bp_303, out ds_272);
			sp_340.u0 = <invalid>;
		}
		if ((ss->*bp_303).tFFFFFFFC > 0x1C)
		{
			seg28BA->t3034 = 0x02;
			word16 cx_778;
			word32 edx_779;
			word32 ebx_780;
			fn226D_00F9(ds_272, out cx_778, out edx_779, out ebx_780, out bp_303, out ds_272);
			sp_340.u0 = <invalid>;
		}
		struct Eq_18750 * es_777;
		word16 bx_776;
		word16 dx_775;
		fn209F_02A7(ds_272, out dx_775, out bx_776, out es_777);
		seg28BA->tA17D = (ss->*bp_303).tFFFFFFFC;
		*((word32) ds_272 + 32866) = (ss->*bp_303).tFFFFFFFC;
		Mem494[ds_272:0x8064:word32] = SEQ(ds_272, 0x8070)[Mem490[ss:bp_303 + -4:word16] * 0x0C];
		Eq_18697 bx_495 = (ss->*bp_303).tFFFFFFFC;
		word16 dx_499 = SEQ(ds_272, 0x7FEA)[bx_495 * 0x04];
		Mem500[ss:bp_303 + -6:word16] = SEQ(ds_272, 0x7FEC)[bx_495 * 0x04];
		(ss->*bp_303).tFFFFFFF8 = dx_499;
		seg28BA->t3026 = (ss->*bp_303).tFFFFFFF8;
		do
		{
			Eq_2 edx_510 = <invalid>;
			word16 ebx_16_16_565 = SLICE(ebx_509, word16, 16);
			word16 dx_781;
			word32 ebx_509;
		} while (((word16) (uint32) fn2331_0167(ds_272, out dx_781, out ebx_509) | (word16) edx_510) != 0x00);
		do
		{
			Eq_11798 ebx_566 = SEQ(ebx_16_16_565, bx_525);
			ds_784 = ds_272;
			word16 cx_782;
			word16 bx_525;
			cui16 dx_528;
		} while (((word16) (uint32) fn2331_0118(ds_784, out cx_782, out dx_528, out bx_525, out ds_272) | dx_528) != 0x00);
		if ((ss->*bp_303).tFFFFFFFC > 0x15 && seg28BA->tA18C != 0xFF)
		{
			word16 ebx_16_16_647;
			Eq_2 es_573;
			word16 sp_581;
			if (seg28BA->tA18C == 0x08)
			{
				(ss->*((byte) sp_340.u0 - 2)).u0 = 0x01;
				word32 ebx_590;
				fn0CE0_08FC(ds_272, out ebx_590, out bp_303, out es_573, out ds_272);
				Eq_2 sp_594 = <invalid>;
				ebx_16_16_647 = SLICE(ebx_590, word16, 16);
				sp_581 = (word16) ((word32) sp_594 + 2);
			}
			else
			{
				struct Eq_18881 Eq_18548::* sp_560 = sp_340 - 2;
				(ss->*sp_560).w0000 = 0x28BA;
				(ss->*sp_560).tFFFFFFFE.u0 = 0x28B8;
				word16 dx_783;
				word32 ebx_571;
				fn1D10_02AE(ebx_566, ds_272, (ss->*sp_560).tFFFFFFFE, out dx_783, out ebx_571, out bp_303, out es_573, out ds_272);
				Eq_2 sp_576 = <invalid>;
				ebx_16_16_647 = SLICE(ebx_571, word16, 16);
				sp_581 = (word16) ((word32) sp_576 + 4);
			}
			struct Eq_18924 Eq_18548::* sp_604 = sp_581 - 4;
			(ss->*sp_604).t0000.u1 = 0x00;
			(ss->*sp_604).tFFFFFFFE.u0 = 0x05;
			fn2331_00BA(es_573, ds_272, (ss->*sp_604).tFFFFFFFE, (ss->*sp_604).t0000, (ss->*sp_604).w0002);
			(ss->*bp_303).tFFFFFFF8.u1 = 0x00;
			--(ss->*bp_303).tFFFFFFFC;
			seg28BA->tA17D = (ss->*bp_303).tFFFFFFFC;
			*((word32) ds_272 + 32866) = (ss->*bp_303).tFFFFFFFC;
			Eq_18697 bx_631 = (ss->*bp_303).tFFFFFFFC;
			Mem635[ds_272:0x8064:word32] = SEQ(ds_272, 0x8070)[bx_631 * 0x0C];
			seg28BA->t3026 = 0x00;
			sp_340 = &sp_604->w0002 + 1;
			ebx_566 = SEQ(ebx_16_16_647, bx_631 *s 0x0C);
		}
		ss->*((byte) sp_340.u0 - 4) = (ss->*bp_303).tFFFFFFF8;
		bp_227 = fn1F0F_057A(ebx_566, ds_272);
		if ((int16) seg28BA->tA182 == 0x00 || seg2862->t0000 == 0x10)
			return ds_272;
		++(ss->*bp_227).wFFFFFFFC;
	}
	return ds_272;
}

// 1F0F:057A: Register (memptr (ptr16 Eq_19009) Eq_18998) fn1F0F_057A(Register Eq_11798 ebx, Register Eq_2 ds)
// Called from:
//      fn1F0F_000F
struct Eq_18998 Eq_19009::* fn1F0F_057A(Eq_11798 ebx, Eq_2 ds)
{
	struct Eq_18998 Eq_19009::* bp_11 = fp - 2;
	Eq_2 sp_112 = fp - 8;
	Eq_11798 ebx_377 = ebx;
	while (true)
	{
		word16 ebx_16_16_94 = SLICE(ebx_377, word16, 16);
		if ((ss->*bp_11).ptr0006 == 0x00 || seg28BA->tA182 == 0x00)
			break;
		struct Eq_19024 * es_bx_19 = (ss->*bp_11).ptr0006;
		if ((es_bx_19->w0019 & 0x01) != 0x00)
		{
			if (es_bx_19->dw0015 != 0x00)
				seg28BA->t3026 = es_bx_19->dw0015;
			else
				seg28BA->t3026 = (ss->*bp_11).ptr0006;
		}
		word32 edx_39 = (ss->*bp_11).ptr0006;
		seg28BA->tA179 = edx_39;
		seg2862->t0000 = 0x02;
		ss->*((word32) sp_112 - 4) = (ss->*bp_11).ptr0006;
		struct Eq_19058 * es_bx_50 = (ss->*bp_11).ptr0006;
		struct Eq_19062 Eq_19009::* sp_55;
		word32 eax_56;
		word32 edx_58;
		word16 cx_59;
		word32 ebx_270;
		es_bx_50->ptr001B();
		bp_11[2] = (word16) edx_58;
		(ss->*bp_11).ptr0006 = (word16) eax_56;
		word16 bx_323 = (word16) ebx_270;
		sp_112 = (char *) &sp_55->t0002 + 2;
		if (bp_11[2] == ds && (ss->*bp_11).ptr0006 == 0xA3D2)
		{
l1F0F_0604:
			(ss->*sp_55).t0000 = (ss->*bp_11).ptr0006;
			word16 ebx_16_16_261 = SLICE(fn1F0F_0BF7(ebx_16_16_94, ds, (ss->*sp_55).t0000, (ss->*sp_55).t0002, out bp_11, out ds), word16, 16);
			(ss->*bp_11).ptr0006 = seg28BA->t3026;
			Eq_2 sp_105 = <invalid>;
			sp_112 = (word32) sp_105 + 4;
			if (bp_11[2] == 0x28BA && (ss->*bp_11).ptr0006 == 11066)
			{
				Eq_2 ds_123;
				fn23F8_00A0(ds, out ds_123);
				seg28BA->t3034 = 0x02;
				seg28BA->t3036 = 0x00;
				seg28BA->t3038 = 0x00;
				seg28BA->t303D = 0x00;
				seg28BA->t303F = 0x00;
				seg28BA->t3046 = 0x00;
				seg28BA->t3048 = 0x00;
				seg28BA->t3051 = 0x28BA;
				seg28BA->t304F = 0x3034;
				word16 cx_385;
				word32 edx_386;
				word32 ebx_161;
				fn226D_00F9(ds_123, out cx_385, out edx_386, out ebx_161, out bp_11, out ds);
				sp_112.u0 = <invalid>;
				ebx_16_16_261 = SLICE(ebx_161, word16, 16);
			}
			Eq_18697 bx_174 = *((word32) ds + 32866);
			Mem177[ds:0x8064:word32] = SEQ(ds, 0x8070)[bx_174 * 0x0C];
			ebx_377 = SEQ(ebx_16_16_261, bx_174 *s 0x0C);
			if (seg2862->t0000 == 0x10)
				break;
			continue;
		}
		if (bp_11[2] == ds)
		{
			if ((ss->*bp_11).ptr0006 != ~0x5C0C)
			{
				ebx_377 = SEQ(ebx_16_16_94, bx_323);
				continue;
			}
			goto l1F0F_0604;
		}
		ebx_377 = SEQ(ebx_16_16_94, bx_323);
	}
	if ((int16) seg28BA->tA182 != 0x00)
	{
		*((word32) ds + 32866) = (word32) *((word32) ds + 32866) + 1;
		while (true)
		{
			Eq_2 edx_199 = <invalid>;
			cui16 dx_207 = (word16) edx_199;
			word32 ebx_384;
			word16 dx_383;
			cui16 ax_210 = (word16) (uint32) fn2331_0167(ds, out dx_383, out ebx_384);
			(ss->*bp_11).wFFFFFFFE = dx_207;
			(ss->*bp_11).tFFFFFFFC = ax_210;
			if ((ax_210 | dx_207) == 0x00)
				break;
			(ss->*bp_11).wFFFFFFFA = (uint16) *(ss->*bp_11).tFFFFFFFC;
			word16 cx_223;
			struct Eq_19134 Eq_28::* bx_224 = Eq_28::a0780;
			for (cx_223 = 0x08; cx_223 != 0x00; --cx_223)
			{
				if ((seg1F0F->*bx_224).w0000 == (ss->*bp_11).wFFFFFFFA)
				{
					word32 ebx_236;
					word32 edx_237;
					word16 cx_238;
					bx_224[8]();
					word16 bx_373 = (word16) ebx_236;
					return bp_11;
				}
				++bx_224;
			}
		}
	}
	return (ss->*bp_11).w0000;
}

// 1F0F:0BF7: Register Eq_11798 fn1F0F_0BF7(Register word16 ebx_16_16, Register Eq_2 ds, Stack Eq_19147 wArg04, Stack Eq_2 wArg06, Register out Eq_10477 bpOut, Register out Eq_2 dsOut)
// Called from:
//      fn1F0F_057A
Eq_11798 fn1F0F_0BF7(word16 ebx_16_16, Eq_2 ds, Eq_19147 wArg04, Eq_2 wArg06, union Eq_10477 & bpOut, union Eq_2 & dsOut)
{
	ci16 bx_11 = *((word32) ds + 33236);
	++*((word32) ds + 33236);
	Eq_11798 ebx_1201 = SEQ(ebx_16_16, bx_11 << 0x02);
	if (*((word32) ds + 33236) > 0x10)
		*((word32) ds + 33236) = 0x00;
	if ((int16) seg28BA->t309E == 0x00)
	{
		byte al_33 = seg2863->b0004;
		__cli();
		word32 ebx_41;
		struct Eq_19315 * es_1516;
		word32 edx_1515;
		word16 cx_1514;
		fn2425_01E8(ds, out cx_1514, out edx_1515, out ebx_41, out es_1516);
		__sti();
		word16 ebx_16_16_1206 = SLICE(ebx_41, word16, 16);
		Eq_2 es_54 = fn226D_0656(ds, ~0x04);
		if (al_33 != 0x00)
			__cli();
		word16 bx_66;
		word16 dx_1518;
		word16 cx_1517;
		fn2425_0286(es_54, ds, out cx_1517, out dx_1518, out bx_66, out ds);
		__sti();
		ebx_1201 = SEQ(ebx_16_16_1206, bx_66);
	}
	Eq_11798 ebx_1091;
	Eq_2 ds_1064;
	Eq_10477 bp_1052;
	Eq_2 sp_146 = fp - 44;
	if ((int16) seg28BA->tA182 == 0x00)
	{
		struct Eq_19349 * es_1520;
		word16 dx_1519;
		fn1D10_02AE(ebx_1201, ds, 683293196, out dx_1519, out ebx_1091, out bp_1052, out es_1520, out ds_1064);
	}
	else
	{
		if (wArg06 != ds || wArg04 != 0xA3D2)
			goto l1F0F_1016;
		cu16 wLoc18_1263 = fn0800_083F(ds) & 0x07;
		if (*((word32) ds + 0x00007F88) != 0x00)
			wLoc18_1263 = 0x01;
		if (seg28BA->t30A1 != 0x00)
			wLoc18_1263 = 0x00;
		if (wLoc18_1263 > 0x06)
			goto l1F0F_1016;
		switch (wLoc18_1263 - 0x01 << 0x01)
		{
		case 0x00:
			if (seg28BA->tA17E != 0x00)
			{
				fn209F_08D2(ds, SEQ(ds, 0x81E0), 0x00);
				if (*((word32) ds + 0x00007F88) == 0x00)
					seg28BA->tA17E = 0x00;
				else
					seg28BA->tA17E = 0x01;
				fn0800_3DE6(SEQ(ss, fp - 44), SEQ(ds, 33261));
				ds = fn2504_094D(ds, 300, 110, SEQ(ss, fp - 44), 0x05, 0x06, 0x04);
				sp_146 = fp - 44;
				do
					;
				while (seg28BA->tA422 == 0x01);
			}
			goto l1F0F_1016;
		case 0x01:
			if (seg28BA->t3036 != 0x00 && seg28BA->t8586 == 0x02)
			{
				fn209F_08D2(ds, SEQ(ds, 33273), 0x00);
				seg28BA->t3036 = 0x00;
				word16 bp_657;
				Eq_2 ds_660;
				word16 cx_1541;
				word32 edx_1542;
				word32 ebx_1543;
				fn226D_00F9(ds, out cx_1541, out edx_1542, out ebx_1543, out bp_657, out ds_660);
				Eq_2 sp_666 = <invalid>;
				ss->*((word32) sp_666 - 2) = ds_660;
				(ss->*((word32) sp_666 - 4)).u0 = 0x8206;
				ss->*((word32) sp_666 - 6) = ss;
				ss->*((word32) sp_666 - 8) = bp_657 - 0x2A;
				fn0800_3DE6(ss->*((word32) sp_666 - 8), ss->*((word32) sp_666 - 4));
				(ss->*((word32) sp_666 - 4)).u0 = 0x00040005;
				(ss->*((word32) sp_666 - 6)).u0 = 0x05;
				ss->*((word32) sp_666 - 8) = ss;
				ss->*((word32) sp_666 - 0x0A) = bp_657 - 0x2A;
				(ss->*((word32) sp_666 - 0x0E)).u3 = 8847674;
				ds = fn2504_094D(ds_660, ss->*((word32) sp_666 - 0x0E), ss->*((word32) sp_666 - 0x0C), ss->*((word32) sp_666 - 0x0A), ss->*((word32) sp_666 - 6), ss->*((word32) sp_666 - 4), ss->*((word32) sp_666 - 2));
				sp_146 = sp_666;
				do
					;
				while (seg28BA->tA422 == 0x01);
			}
			goto l1F0F_1016;
		case 0x02:
			if ((seg28BA->tA520 & 0x04) != 0x00)
			{
				if (seg28BA->t8586 == 0x04)
				{
					if (seg28BA->t3048 != 0x00)
					{
						seg28BA->t3048 = 0x00;
						word16 bp_544;
						Eq_2 ds_547;
						word16 cx_1544;
						word32 edx_1545;
						word32 ebx_1546;
						fn226D_00F9(ds, out cx_1544, out edx_1545, out ebx_1546, out bp_544, out ds_547);
						Eq_2 sp_553 = <invalid>;
						(ss->*((word32) sp_553 - 2)).u0 = 0x00;
						ss->*((word32) sp_553 - 4) = ds_547;
						(ss->*((word32) sp_553 - 6)).u0 = 33273;
						fn209F_08D2(ds_547, ss->*((word32) sp_553 - 6), ss->*((word32) sp_553 - 2));
						ss->*((word32) sp_553 - 2) = ds_547;
						(ss->*((word32) sp_553 - 4)).u0 = 0x8206;
						ss->*((word32) sp_553 - 6) = ss;
						ss->*((word32) sp_553 - 8) = bp_544 - 0x2A;
						fn0800_3DE6(ss->*((word32) sp_553 - 8), ss->*((word32) sp_553 - 4));
						(ss->*((word32) sp_553 - 4)).u0 = 0x00040005;
						(ss->*((word32) sp_553 - 6)).u0 = 0x05;
						ss->*((word32) sp_553 - 8) = ss;
						ss->*((word32) sp_553 - 0x0A) = bp_544 - 0x2A;
						(ss->*((word32) sp_553 - 0x0E)).u3 = 8847674;
						ds = fn2504_094D(ds_547, ss->*((word32) sp_553 - 0x0E), ss->*((word32) sp_553 - 0x0C), ss->*((word32) sp_553 - 0x0A), ss->*((word32) sp_553 - 6), ss->*((word32) sp_553 - 4), ss->*((word32) sp_553 - 2));
						sp_146 = sp_553;
						do
							;
						while (seg28BA->tA422 == 0x01);
					}
				}
				else
				{
					seg28BA->tA520 = seg28BA->tA520 & ~0x04;
					selector ds_458 = fn23F8_01EB(ds, 683313068);
					fn209F_08D2(ds_458, SEQ(ds_458, 0x8211), 0x00);
					fn0800_3DE6(SEQ(ss, fp - 44), SEQ(ds_458, 33309));
					ds = fn2504_094D(ds_458, 0x0127, 0x29, SEQ(ss, fp - 44), 0x05, 0x04, 0x04);
					sp_146 = fp - 44;
					do
						;
					while (seg28BA->tA422 == 0x01);
				}
			}
			goto l1F0F_1016;
		case 0x03:
l1F0F_1016:
			Eq_2 ds_827 = fn226D_057F(ds);
			__cli();
			word32 ebx_842;
			struct Eq_19371 * es_1523;
			word16 cx_1521;
			word32 edx_1522;
			fn2425_01E8(ds_827, out cx_1521, out edx_1522, out ebx_842, out es_1523);
			struct Eq_19380 Eq_2::* sp_856 = sp_146 - 4;
			(ss->*sp_856).dw0000 = 0x00;
			(ss->*sp_856).tFFFFFFFE.u0 = 0x01;
			(ss->*sp_856).tFFFFFFFA.u0 = 0x00;
			(ss->*sp_856).tFFFFFFF8.u0 = 0x01;
			(ss->*sp_856).tFFFFFFF6.u1 = 0x00;
			(ss->*sp_856).tFFFFFFF4.u0 = 0x00;
			(ss->*sp_856).tFFFFFFF2.u0 = 0x01;
			(ss->*sp_856).tFFFFFFF0.u0 = 0x00;
			Eq_2 es_873;
			fn2353_0004(ds_827, (ss->*sp_856).tFFFFFFF0, (ss->*sp_856).tFFFFFFF2, (ss->*sp_856).tFFFFFFF4, (ss->*sp_856).tFFFFFFF6, (ss->*sp_856).tFFFFFFF8, (ss->*sp_856).tFFFFFFFA, (ss->*sp_856).tFFFFFFFE, out bp_1052, out es_873);
			word16 bx_885;
			word16 dx_1525;
			word16 cx_1524;
			fn2425_0286(es_873, ds_827, out cx_1524, out dx_1525, out bx_885, out ds_1064);
			__sti();
			Eq_2 sp_878 = <invalid>;
			word16 sp_883 = (word32) sp_878 + 20;
			ebx_1091 = SEQ(SLICE(ebx_842, word16, 16), bx_885);
			if ((int16) seg28BA->t3095 == 0x00)
			{
				ss->*((word32) sp_878 + 16) = ss->*((word16) bp_1052 - 0x0C);
				struct Eq_19483 * es_1527;
				word16 dx_1526;
				fn1D10_02AE(ebx_1091, ds_1064, ss->*((word32) sp_878 + 16), out dx_1526, out ebx_1091, out bp_1052, out es_1527, out ds_1064);
				Eq_2 sp_921 = <invalid>;
				sp_883 = (word16) ((word32) sp_921 + 4);
			}
			if (*((word32) ds_1064 + 0x00007F88) == 0x00)
			{
				__cli();
				word32 ebx_936;
				word16 cx_1528;
				word32 edx_1529;
				struct Eq_19507 * es_1530;
				fn2425_01E8(ds_1064, out cx_1528, out edx_1529, out ebx_936, out es_1530);
				__sti();
				struct Eq_19516 Eq_2::* sp_946 = sp_883 - 4;
				(ss->*sp_946).t0000 = seg28BA->tAA80;
				(ss->*sp_946).tFFFFFFFC.u1 = 0x8C;
				(ss->*sp_946).tFFFFFFF8.u1 = 0x00E4000A;
				(ss->*sp_946).tFFFFFFF6.u0 = 0x0A;
				fn216E_03D8((ss->*sp_946).tFFFFFFF6, (ss->*sp_946).tFFFFFFF8, (ss->*sp_946).tFFFFFFFA, (ss->*sp_946).tFFFFFFFC, (ss->*sp_946).tFFFFFFFE, (ss->*sp_946).t0000, (ss->*sp_946).t0002);
				(ss->*sp_946).t0002 = ss;
				(ss->*sp_946).t0000 = bp_1052 - 0x08;
				(ss->*sp_946).tFFFFFFFE = ds_1064;
				(ss->*sp_946).tFFFFFFFC.u0 = 33374;
				(ss->*sp_946).tFFFFFFFA = ss;
				(ss->*sp_946).tFFFFFFF8 = bp_1052 - 0x04;
				(ss->*sp_946).tFFFFFFF6 = ds_1064;
				(ss->*sp_946).tFFFFFFF4.u0 = 33363;
				Eq_2 ds_984;
				Eq_8347 bp_981 = fn263F_033E(ds_1064, (ss->*sp_946).tFFFFFFF4, out ds_984);
				Eq_2 sp_988 = <invalid>;
				ss->*((word32) sp_988 + 0x0C) = seg28BA->tAA80;
				ss->*((word32) sp_988 + 8) = ss->*((word16) bp_981 - 4);
				(ss->*((word32) sp_988 + 4)).u3 = 0x003C0024;
				byte al_1531;
				word16 bx_1532;
				fn216E_01DC(ss->*((word32) sp_988 + 4), ss->*((word32) sp_988 + 6), ss->*((word32) sp_988 + 8), ss->*((word32) sp_988 + 0x0A), ss->*((word32) sp_988 + 0x0C), ss->*((word32) sp_988 + 0x0E), out al_1531, out bx_1532);
				ss->*((word32) sp_988 + 0x0C) = ss->*((word16) bp_981 - 4);
				Eq_2 ds_1020;
				word16 cx_1533;
				word16 dx_1534;
				word16 bx_1535;
				fn0800_1C24(ds_984, ss->*((word32) sp_988 + 0x0E), out cx_1533, out dx_1534, out bx_1535, out ds_1020);
				__cli();
				(ss->*((word32) sp_988 + 0x0C)).u0 = 0x00;
				(ss->*((word32) sp_988 + 0x0A)).u0 = 0x01;
				(ss->*((word32) sp_988 + 6)).u0 = 0x00;
				(ss->*((word32) sp_988 + 4)).u0 = 0x01;
				(ss->*((word32) sp_988 + 2)).u1 = 0x01;
				(ss->*sp_988).u0 = 0x01;
				(ss->*((word32) sp_988 - 2)).u0 = 0x01;
				(ss->*((word32) sp_988 - 4)).u0 = 0x01;
				Eq_2 es_1049;
				fn2353_0004(ds_1020, ss->*((word32) sp_988 - 4), ss->*((word32) sp_988 - 2), ss->*sp_988, ss->*((word32) sp_988 + 2), ss->*((word32) sp_988 + 4), ss->*((word32) sp_988 + 6), ss->*((word32) sp_988 + 0x0A), out bp_1052, out es_1049);
				word16 bx_1061;
				word16 cx_1536;
				word16 dx_1537;
				fn2425_0286(es_1049, ds_1020, out cx_1536, out dx_1537, out bx_1061, out ds_1064);
				__sti();
				Eq_2 sp_1054 = <invalid>;
				word16 sp_1059 = (word32) sp_1054 + 20;
				ebx_1091 = SEQ(SLICE(ebx_936, word16, 16), bx_1061);
				if (*((word32) ds_1064 + 32646) == 0x00)
				{
					seg2862->t0000 = seg2862->t0000 | 0x20;
					while (seg28BA->tA182 != 0x00)
					{
						Eq_2 edx_1092 = <invalid>;
						cui16 dx_1100 = (word16) edx_1092;
						word16 dx_1538;
						Eq_19789 ax_1103 = (word16) (uint32) fn2331_0167(ds_1064, out dx_1538, out ebx_1091);
						ss->*((word16) bp_1052 - 16) = dx_1100;
						ss->*((word16) bp_1052 - 18) = ax_1103;
						word16 ebx_16_16_1453 = SLICE(ebx_1091, word16, 16);
						if ((ax_1103 | dx_1100) != 0x00)
						{
							ss->*((word16) bp_1052 - 20) = (uint16) *(ss->*((word16) bp_1052 - 18)).u1;
							word16 cx_1116;
							struct Eq_19875 Eq_28::* bx_1117 = Eq_28::a1217;
							for (cx_1116 = 0x08; cx_1116 != 0x00; --cx_1116)
							{
								if ((seg1F0F->*bx_1117).w0000 == ss->*((word16) bp_1052 - 20))
								{
									Eq_11798 ebx_1129;
									bx_1117[8]();
									bpOut = bp_1052;
									dsOut = ds_1064;
									return ebx_1129;
								}
								++bx_1117;
								ebx_1091 = SEQ(ebx_16_16_1453, bx_1117);
							}
							seg2862->t0000 = seg2862->t0000 | 0x20;
						}
						word16 ebx_16_16_1455 = SLICE(ebx_1091, word16, 16);
						if (seg28BA->t302C == 0x00)
						{
							struct Eq_19883 Eq_2::* sp_1152 = sp_1059 - 4;
							(ss->*sp_1152).dw0000 = 0x00;
							(ss->*sp_1152).tFFFFFFFE.u0 = 0x01;
							(ss->*sp_1152).tFFFFFFFA.u0 = 0x00;
							(ss->*sp_1152).tFFFFFFF8.u0 = 0x01;
							(ss->*sp_1152).tFFFFFFF6.u1 = 0x01;
							(ss->*sp_1152).tFFFFFFF4.u0 = 0x01;
							(ss->*sp_1152).tFFFFFFF2.u0 = 0x01;
							(ss->*sp_1152).tFFFFFFF0.u0 = 0x01;
							Eq_2 es_1171;
							fn2353_0004(ds_1064, (ss->*sp_1152).tFFFFFFF0, (ss->*sp_1152).tFFFFFFF2, (ss->*sp_1152).tFFFFFFF4, (ss->*sp_1152).tFFFFFFF6, (ss->*sp_1152).tFFFFFFF8, (ss->*sp_1152).tFFFFFFFA, (ss->*sp_1152).tFFFFFFFE, out bp_1052, out es_1171);
							Eq_2 sp_1176 = <invalid>;
							__cli();
							word16 bx_1183;
							word16 cx_1539;
							word16 dx_1540;
							fn2425_0286(es_1171, ds_1064, out cx_1539, out dx_1540, out bx_1183, out ds_1064);
							__sti();
							sp_1059 = (word16) ((word32) sp_1176 + 20);
							ebx_1091 = SEQ(ebx_16_16_1455, bx_1183);
						}
					}
				}
			}
			break;
		case 0x04:
			if ((seg28BA->tA520 & 0x08) != 0x00)
			{
				if (seg28BA->t8586 == 0x08)
				{
					if (seg28BA->t303F != 0x00)
					{
						seg28BA->t303F = 0x00;
						word16 bp_350;
						Eq_2 ds_353;
						word16 cx_1547;
						word32 edx_1548;
						word32 ebx_1549;
						fn226D_00F9(ds, out cx_1547, out edx_1548, out ebx_1549, out bp_350, out ds_353);
						Eq_2 sp_359 = <invalid>;
						(ss->*((word32) sp_359 - 2)).u0 = 0x00;
						ss->*((word32) sp_359 - 4) = ds_353;
						(ss->*((word32) sp_359 - 6)).u0 = 33273;
						fn209F_08D2(ds_353, ss->*((word32) sp_359 - 6), ss->*((word32) sp_359 - 2));
						ss->*((word32) sp_359 - 2) = ds_353;
						(ss->*((word32) sp_359 - 4)).u0 = 0x8206;
						ss->*((word32) sp_359 - 6) = ss;
						ss->*((word32) sp_359 - 8) = bp_350 - 0x2A;
						fn0800_3DE6(ss->*((word32) sp_359 - 8), ss->*((word32) sp_359 - 4));
						(ss->*((word32) sp_359 - 4)).u0 = 0x00040005;
						(ss->*((word32) sp_359 - 6)).u0 = 0x05;
						ss->*((word32) sp_359 - 8) = ss;
						ss->*((word32) sp_359 - 0x0A) = bp_350 - 0x2A;
						(ss->*((word32) sp_359 - 0x0E)).u3 = 8847674;
						ds = fn2504_094D(ds_353, ss->*((word32) sp_359 - 0x0E), ss->*((word32) sp_359 - 0x0C), ss->*((word32) sp_359 - 0x0A), ss->*((word32) sp_359 - 6), ss->*((word32) sp_359 - 4), ss->*((word32) sp_359 - 2));
						sp_146 = sp_359;
						do
							;
						while (seg28BA->tA422 == 0x01);
					}
				}
				else
				{
					seg28BA->tA520 = seg28BA->tA520 & ~0x08;
					selector ds_264 = fn23F8_01EB(ds, 683313134);
					fn209F_08D2(ds_264, SEQ(ds_264, 33319), 0x00);
					fn0800_3DE6(SEQ(ss, fp - 44), SEQ(ds_264, 33332));
					ds = fn2504_094D(ds_264, 0x0127, 0x29, SEQ(ss, fp - 44), 0x05, 0x03, 0x04);
					sp_146 = fp - 44;
					do
						;
					while (seg28BA->tA422 == 0x01);
				}
			}
			goto l1F0F_1016;
		case 0x05:
			if (seg28BA->tA18C != 0x00 && seg28BA->tA18C != 0xFF)
			{
				seg28BA->tA18C = seg28BA->tA18C - 0x01;
				if (seg28BA->tA18C == 0x00)
					ds = fn23F8_01EB(ds, 0x28BA8830);
				fn209F_08D2(ds, SEQ(ds, 33341), 0x00);
				fn0800_3DE6(SEQ(ss, fp - 44), SEQ(ds, 33353));
				ds = fn2504_094D(ds, 0x0127, 0x29, SEQ(ss, fp - 44), 0x05, 0x04, 0x04);
				sp_146 = fp - 44;
				do
					;
				while (seg28BA->tA422 == 0x01);
			}
			goto l1F0F_1016;
		}
	}
	bpOut = ss->*bp_1052;
	dsOut = ds_1064;
	return ebx_1091;
}

