// ZORTON_2141.c
// Generated by decompiling ZORTON.EXE
// using Reko decompiler version 0.9.2.3.

#include "ZORTON_2141.h"

// 2141:020E: Register word16 fn2141_020E(Register Eq_2 ds)
// Called from:
//      main
word16 fn2141_020E(Eq_2 ds)
{
	word16 dx_14;
	Eq_147 ax_12 = fn0800_0436(0x1C, out dx_14);
	*((word32) ds + 42032) = dx_14;
	*((word32) ds + 42030) = ax_12;
	fn0800_0445(0x1C, 557907975);
	__outb(0x43, 0x36);
	__outb(0x40, 0xC6);
	__outb(0x40, 0x49);
	word16 bx_45 = fn0800_10B1(ds, null);
	*((word32) ds + 42034) = 0x00400049;
	seg28BA->t302A = seg28BA->t302A | 0x04;
	return bx_45;
}

// 2141:0271: Register byte fn2141_0271(Register Eq_2 ds)
// Called from:
//      fn268D_03E2
byte fn2141_0271(Eq_2 ds)
{
	fn0800_0445(0x1C, *((word32) ds + 42030));
	__outb(0x43, 0x36);
	__outb(0x40, 0x00);
	__outb(0x40, 0x00);
	__syscall(0x1A);
	__syscall(33);
	return 0x00;
}

