// ZORTON_18D5.c
// Generated by decompiling ZORTON.EXE
// using Reko decompiler version 0.9.2.3.

#include "ZORTON_18D5.h"

// 18D5:11FB: void fn18D5_11FB(Stack Eq_2 ptrArg04, Stack Eq_2 wArg08, Stack Eq_2 wArg0A)
// Called from:
//      fn0CE0_08FC
void fn18D5_11FB(Eq_2 ptrArg04, Eq_2 wArg08, Eq_2 wArg0A)
{
	word16 Eq_14403::* di_32 = (word16) ptrArg04;
	struct Eq_14403 * es_175 = SLICE(ptrArg04, selector, 16);
	word16 Eq_12853::* si_168 = Eq_12853::aFFFFBB80;
	word16 cx_174 = 8000;
	di_170 = di_32;
	while (true)
	{
		word16 Eq_14403::* di_170;
		if (cx_174 == 0x00)
			break;
		es_175->*di_170 = 0xA000->*si_168;
		++si_168;
		++di_170;
		--cx_174;
	}
	seg18D5->w1299 = (word32) wArg08 + 48000;
	cu16 cx_113 = 0x00;
	do
	{
		fn18D5_12E5();
		Eq_14431 di_137 = (cx_275 << 0x06) + SEQ((byte) cx_275, 0x00) + 48000;
		word16 Eq_2::* si_161 = seg18D5->w1299;
		word16 cx_167;
		for (cx_167 = 0x05; cx_167 != 0x00; --cx_167)
		{
			0xA000->*di_137 = wArg0A->*si_161;
			++si_161;
			di_137 = (word16) di_137 + 2;
		}
		word16 si_152 = di_137 + wArg08;
		word16 cx_159;
		for (cx_159 = 0x96; cx_159 != 0x00; --cx_159)
		{
			0xA000->*di_137 = wArg0A->*si_152;
			++si_152;
			di_137 = (word16) di_137 + 2;
		}
		word16 Eq_2::* si_148 = seg18D5->w1299 + 155;
		word16 cx_150;
		for (cx_150 = 0x05; cx_150 != 0x00; --cx_150)
		{
			0xA000->*di_137 = wArg0A->*si_148;
			++si_148;
			di_137 = (word16) di_137 + 2;
		}
		seg18D5->w1299 = (word16 *) si_148;
		cui16 cx_105 = 0x32 - (cx_275 + 0x01);
		word16 Eq_14403::* si_102 = di_32;
		ui16 cx_109;
		for (cx_109 = (cx_105 << 0x07) + (cx_105 << 0x05); cx_109 != 0x00; --cx_109)
		{
			0xA000->*di_137 = es_175->*si_102;
			++si_102;
			di_137 = (word16) di_137 + 2;
		}
		cx_113 = cx_275 + 0x01;
		cx_275 = cx_113;
	} while (cx_275 < 0x28);
}

// 18D5:129B: void fn18D5_129B(Stack Eq_2 wArg04, Stack Eq_2 wArg06)
// Called from:
//      fn0CE0_08FC
void fn18D5_129B(Eq_2 wArg04, Eq_2 wArg06)
{
	word16 Eq_12853::* di_30 = &Eq_12853::wFFFFED80;
	word16 bx_33;
	word16 cx_34 = 0x0640;
	for (bx_33 = 0x29; bx_33 != 0x00; --bx_33)
	{
		fn18D5_12E5();
		Eq_2 si_48 = wArg04;
		cx_49 = cx_34;
		di_82 = di_30;
		while (true)
		{
			word16 Eq_12853::* di_82;
			word16 cx_49;
			if (cx_49 == 0x00)
				break;
			0xA000->*di_82 = wArg06->*si_48;
			si_48 = (word16) si_48 + 2;
			++di_82;
			--cx_49;
		}
		cx_34 += 0xA0;
		di_30 -= 0x0140;
	}
}

// 18D5:12E5: void fn18D5_12E5()
// Called from:
//      fn18D5_11FB
//      fn18D5_129B
void fn18D5_12E5()
{
	do
		;
	while ((__inb(0x03DA) & 0x08) == 0x00);
	do
		;
	while ((__inb(0x03DA) & 0x08) != 0x00);
}

