// ZORTON_28BA.c
// Generated by decompiling ZORTON.EXE
// using Reko decompiler version 0.9.3.0.

#include "ZORTON.h"

Eq_2 g_t28BA0 = // 00028BA0
	{
		0x00
	};
Eq_33166 g_a3053[] = // 2864:3053
	{
	};
