// ZORTON_2057.c
// Generated by decompiling ZORTON.EXE
// using Reko decompiler version 0.9.2.3.

#include "ZORTON_2057.h"

// 2057:0000: Register word16 fn2057_0000(Register Eq_2 ds, Stack Eq_947 bArg04)
// Called from:
//      fn2057_005C
//      fn2057_0283
//      fn2057_0384
//      fn2057_0453
word16 fn2057_0000(Eq_2 ds, Eq_947 bArg04)
{
	word16 ax_11 = *((word32) ds + 38606);
	__cli();
	cup16 wLoc06_38;
	for (wLoc06_38 = ~0x00; wLoc06_38 > 0x00; --wLoc06_38)
	{
		dx = ax_11 + 0x0C;
		if ((__inb(ax_11 + 0x0C) & 0x80) == 0x00)
		{
			__outb(ax_11 + 0x0C, bArg04);
			break;
		}
	}
	__sti();
	return dx;
}

// 2057:005C: void fn2057_005C(Register Eq_2 bx, Register Eq_2 ds)
// Called from:
//      main
void fn2057_005C(Eq_2 bx, Eq_2 ds)
{
	if (seg28BA->tA183 != 0x00)
	{
		Eq_2524 ptrLoc0C_167;
		Eq_20446 ax_15 = *((word32) ds + 0x000096D2);
		fn2057_0000(ds, 0xD1);
		fn2057_0000(ds, 0x40);
		Eq_947 al_41 = seg28BA->t82E4;
		Eq_2 ax_44 = SEQ(0x28, al_41);
		Eq_2 dx_47 = fn2057_0000(ds, al_41);
		if (ax_15 < 11)
		{
			bx = ax_15 - 0x02;
			int16 ax_62 = (int16) (ds->*((word16) ax_15 + 33407));
			if (ax_62 != 0x00)
			{
				__cli();
				word16 dx_71;
				Eq_147 ax_69 = fn0800_0436((byte) ax_62, out dx_71);
				*((word32) ds + 42008) = dx_71;
				*((word32) ds + 42006) = ax_69;
				fn0800_0445((byte) ax_62, 0x20570182);
				__outb(33, __inb(33) & ds->*((word16) ax_15 + 33380));
				if (ax_15 == 0x0A)
					__outb(161, __inb(161) & ds->*((word16) ax_15 + 33380));
				__sti();
				goto l2057_0111;
			}
			ptrLoc0C_167 = SEQ(ds, 0x8292);
		}
		else
			ptrLoc0C_167 = SEQ(ds, 33461);
		fn0800_37D3(ax_44, dx_47, bx, ds, ptrLoc0C_167);
		seg28BA->tA183 = 0x00;
	}
	else
	{
l2057_0111:
		seg28BA->t302A = seg28BA->t302A | 0x10;
	}
}

// 2057:011E: Register (memptr Eq_2 Eq_20533) fn2057_011E(Register Eq_2 ds)
// Called from:
//      fn268D_03E2
struct Eq_20533 Eq_2::* fn2057_011E(Eq_2 ds)
{
	if (seg28BA->tA183 != 0x00)
	{
		__cli();
		Eq_20446 ax_15 = *((word32) ds + 0x000096D2);
		fn0800_0445((byte) (int16) (ds->*((word16) ax_15 + 33407)), *((word32) ds + 42006));
		__outb(33, __inb(33) | ~(ds->*((word16) ax_15 + 33380)));
		bx = ax_15 - 0x02;
		if (ax_15 == 0x0A)
			__outb(161, __inb(161) | ~(ds->*((word16) ax_15 + 33380)));
		__sti();
	}
	return bx;
}

// 2057:0283: Register byte fn2057_0283(Register Eq_2 ds, Stack byte bArg04, Stack Eq_947 bArg06, Stack Eq_947 bArg08, Stack Eq_20586 bArg0A, Register out Eq_20587 cxOut, Register out Eq_947 bxOut)
// Called from:
//      fn209F_049A
byte fn2057_0283(Eq_2 ds, byte bArg04, Eq_947 bArg06, Eq_947 bArg08, Eq_20586 bArg0A, union Eq_20587 & cxOut, union Eq_947 & bxOut)
{
	Eq_947 bArg0A_222 = (byte) (wArg0A - 0x01);
	if (seg28BA->tA183 == 0x00)
	{
l2057_0382:
		cxOut = cx;
		bxOut = bx;
		return ~0x45;
	}
	if (((uint16) __inb(0x0A) & 0x04) == 0x00)
		__outb(0x0A, *((word32) ds + 0x000096D4) | 0x04);
	Eq_947 bLoc04_253;
	Eq_947 bLoc04_231;
	__outb(0x0C, 0x00);
	__outb(11, *((word32) ds + 0x000096D4) | 0x48 | 0x10);
	Eq_947 bx_35 = *((word32) ds + 0x000096D4);
	__outb((int16) (ds->*((word16) bx_35 + 0x0000828A)), bArg06);
	__outb((int16) (ds->*((word16) bx_35 + 0x0000828A)), bArg08);
	__outb(SEQ(ds, 33391)[bx_35 * 0x02], bArg04 & 0x0F);
	bx = *((word32) ds + 0x000096D4);
	__outb((int16) (ds->*((word16) bx + 0x0000828E)), bArg0A_222);
	__outb((int16) (ds->*((word16) bx + 0x0000828E)), (byte) (wArg0A - 0x01 >> 0x08));
	__outb(0x0A, *((word32) ds + 0x000096D4));
	uint16 ax_85 = (uint16) seg28BA->tA427;
	if (ax_85 != 0x01)
	{
		if (ax_85 != 0x04)
		{
			fn2057_0000(ds, 0x48);
			fn2057_0000(ds, 0xB8);
			fn2057_0000(ds, 0x01);
			bLoc04_253.u0 = 0x1C;
			goto l2057_0372;
		}
		fn2057_0000(ds, 0xC6);
		bLoc04_231.u0 = 0x00;
	}
	else
		bLoc04_231.u0 = 0x14;
	fn2057_0000(ds, bLoc04_231);
	fn2057_0000(ds, 0xB8);
	bLoc04_253.u0 = 0x01;
l2057_0372:
	fn2057_0000(ds, bLoc04_253);
	seg28BA->tA422 = 0x01;
	cx.u0 = (uint16) bLoc04_253;
	goto l2057_0382;
}

// 2057:0384: void fn2057_0384(Register Eq_2 ds)
// Called from:
//      fn0CE0_08FC
//      fn1D10_02AE
//      fn1D10_09C2
void fn2057_0384(Eq_2 ds)
{
	if (seg28BA->tA183 != 0x00)
	{
		__cli();
		if (((uint16) __inb(0x0A) & 0x04) == 0x00)
			__outb(0x0A, *((word32) ds + 0x000096D4) | 0x04);
		fn2057_0000(ds, 0xD0);
		seg28BA->tA422 = 0x02;
		__sti();
	}
}

// 2057:041E: Register cui16 fn2057_041E(Register Eq_2 ds, Register out Eq_9040 dxOut)
// Called from:
//      fn1D10_09C2
//      fn209F_06D8
cui16 fn2057_041E(Eq_2 ds, union Eq_9040 & dxOut)
{
	__cli();
	__outb(0x0C, 0x00);
	Eq_947 bx_13 = *((word32) ds + 0x000096D4);
	uint16 ax_22 = (uint16) __inb((int16) (ds->*((word16) bx_13 + 0x0000828A)));
	Eq_9040 ax_26 = (int16) (ds->*((word16) bx_13 + 0x0000828A));
	cui16 v14_34 = ax_22 & 0xFF | (uint16) __inb(ax_26) << 0x08;
	__sti();
	dxOut = ax_26;
	return v14_34;
}

// 2057:0453: void fn2057_0453(Register Eq_2 ds)
// Called from:
//      fn1D10_02AE
void fn2057_0453(Eq_2 ds)
{
	if (seg28BA->tA183 != 0x00)
	{
		__cli();
		if ((__inb(0x0A) & 0x04) != 0x00)
			__outb(0x0A, *((word32) ds + 0x000096D4));
		fn2057_0000(ds, 212);
		seg28BA->tA422 = 0x01;
		__sti();
	}
}

