// ZORTON_209F.c
// Generated by decompiling ZORTON.EXE
// using Reko decompiler version 0.9.2.3.

#include "ZORTON_209F.h"

// 209F:0002: void fn209F_0002(Register Eq_2 cx, Register Eq_2 dx, Register Eq_2 bx, Register Eq_2 ds, Stack (ptr32 Eq_947) ptrArg04, Stack (ptr32 Eq_947) ptrArg08)
// Called from:
//      fn209F_00DD
void fn209F_0002(Eq_2 cx, Eq_2 dx, Eq_2 bx, Eq_2 ds, union Eq_947 * ptrArg04, union Eq_947 * ptrArg08)
{
	word16 ax_11 = *((word32) ds + 38606);
	ci16 wLoc06_173;
	for (wLoc06_173 = 0x00; wLoc06_173 < 100; ++wLoc06_173)
	{
		__outb(ax_11 + 0x06, 0x01);
		int32 dwLoc0A_176;
		for (dwLoc0A_176 = 0x00; dwLoc0A_176 < 10000; ++dwLoc0A_176)
			;
		__outb(ax_11 + 0x06, 0x00);
		do
			;
		while (((uint16) __inb(ax_11 + 0x0E) & 0x80) == 0x00);
		dx = ax_11 + 0x0A;
		if (__inb(ax_11 + 0x0A) == 0xAA)
			break;
	}
	if (wLoc06_173 == 100)
	{
		fn0800_37D3(cx, dx, bx, ds, SEQ(ds, 33623));
		fn0800_20A6(ds);
		fn0800_03B9(ds, 0x01);
	}
	do
		;
	while ((__inb(ax_11 + 0x0C) & 0x80) != 0x00);
	__outb(ax_11 + 0x0C, 225);
	do
		;
	while (((uint16) __inb(ax_11 + 0x0E) & 0x80) == 0x00);
	*ptrArg04 = (union Eq_947 *) __inb(ax_11 + 0x0A);
	do
		;
	while (((uint16) __inb(ax_11 + 0x0E) & 0x80) == 0x00);
	*ptrArg08 = (union Eq_947 *) __inb(ax_11 + 0x0A);
}

// 209F:00DD: Register Eq_2 fn209F_00DD(Register Eq_2 ds)
// Called from:
//      fn268D_034A
Eq_2 fn209F_00DD(Eq_2 ds)
{
	seg28BA->tA183 = 0x00;
	if (fn27FB_050A() == 0x00 && (fn27FB_00DC() != 0x00 && fn27FB_02C4() != 0x00))
	{
		Eq_2 bx_52;
		Eq_2 cx_53;
		Eq_2 dx_54;
		if (fn27FB_039A(out cx_53, out dx_54, out bx_52) >= 0x00)
		{
			fn209F_0002(cx_53, dx_54, bx_52, ds, fp - 0x03, fp - 0x04);
			*((word32) ds + 42023) = bLoc03;
			*((word32) ds + 42024) = bLoc04;
			seg28BA->tA183 = 0x01;
			return 0x28BA;
		}
	}
	fn0800_1A83(ds, 0xFA);
	return 0x28BA;
}

// 209F:0149: Register Eq_756 fn209F_0149(Register Eq_2 ds, Register out Eq_2 dxOut, Register out ptr16 bpOut, Register out Eq_2 dsOut)
// Called from:
//      fn209F_04CB
Eq_756 fn209F_0149(Eq_2 ds, union Eq_2 & dxOut, ptr16 & bpOut, union Eq_2 & dsOut)
{
	Eq_2 bx_18;
	struct Eq_20970 * es_342;
	Eq_20971 bp_128;
	Eq_2 dx_124;
	Eq_2 ds_153;
	Eq_756 ax_16 = fn0800_1D2E(ds, 0x11, out dx_124, out bx_18, out bp_128, out es_342, out ds_153);
	ss->*((word16) bp_128 - 4) = dx_124;
	ss->*((word16) bp_128 - 6) = ax_16;
	Eq_2 cx_159 = 0x11;
	if (ss->*((word16) bp_128 - 6) == 0x00)
	{
		word16 bx_343;
		cx_159 = fn263F_043F(0x11, dx_124, bx_18, ds_153, SEQ(ds_153, 33682), out dx_124, out bx_343, out ds_153);
	}
	ss->*((word16) bp_128 - 2) = 0x00;
	while (ss->*((word16) bp_128 - 2) < 0x28)
	{
		Eq_21015 bx_66 = bp_128 - 0xAA + (ss->*((word16) bp_128 - 2) << 0x02);
		ss->*((word16) bx_66 + 2) = 0x00;
		ss->*bx_66 = 0x00;
		++ss->*((word16) bp_128 - 2);
	}
	ss->*((word16) bp_128 - 2) = 0x00;
	while (ss->*((word16) bp_128 - 2) < 0x27)
	{
		int32 eax_82 = (int32) (ss->*((word16) bp_128 + 6) + 500);
		word16 bx_344;
		Eq_2 ax_87 = fn0800_1D38(ds_153, (word16) eax_82, SLICE(eax_82, word16, 16), out cx_159, out dx_124, out bx_344, out bp_128, out ds_153);
		Eq_756 es_bx_99 = ss->*((word16) bp_128 - 6);
		*((word32) es_bx_99 + 6) = dx_124;
		*((word32) es_bx_99 + 4) = ax_87;
		if ((ax_87 | dx_124) == 0x00)
			break;
		Eq_756 es_bx_108 = ss->*((word16) bp_128 - 6);
		Eq_21093 eax_114 = ((word32) *((word32) es_bx_108 + 6) << 0x04) + (word32) (*((word32) es_bx_108 + 4));
		ss->*((word16) bp_128 - 0x0A) = eax_114;
		*((word32) es_bx_108 + 0x0E) = (byte) (eax_114 >> 0x10);
		*((word32) es_bx_108 + 0x0F) = ss->*((word16) bp_128 - 0x0A);
		struct Eq_21120 * es_109 = SLICE(es_bx_108, selector, 16);
		dx_124 = ~0x00 - *((word32) es_bx_108 + 0x0F);
		if (ss->*((word16) bp_128 + 6) << 0x01 <= dx_124)
			break;
		Eq_756 si_233 = ss->*((word16) bp_128 - 6);
		Eq_21137 bx_231 = bp_128 - 0xAA + (ss->*((word16) bp_128 - 2) << 0x02) / 8;
		dx_124 = es_109->*((word32) si_233 + 4);
		ss->*((word16) bx_231 + 2) = es_109->*((word32) si_233 + 6);
		ss->*bx_231 = dx_124;
		++ss->*((word16) bp_128 - 2);
	}
	ss->*((word16) bp_128 - 2) = 0x00;
	while (ss->*((word16) bp_128 - 2) < 0x28)
	{
		Eq_21166 bx_138 = bp_128 - 0xAA + (ss->*((word16) bp_128 - 2) << 0x02) / 8;
		if ((ss->*bx_138 | ss->*((word16) bx_138 + 2)) == 0x00)
			break;
		word16 bx_347;
		fn0800_1C24(ds_153, Mem132[ss:(Mem132[ss:bp_128 + -2:word16] << 0x02) + (bp_128 - 0xAA) + 0x02:word16], out cx_159, out dx_124, out bx_347, out ds_153);
		++ss->*((word16) bp_128 - 2);
	}
	Eq_756 es_bx_172 = ss->*((word16) bp_128 - 6);
	Eq_2 bx_174 = (word16) es_bx_172;
	if (*((word32) es_bx_172 + 4) == 0x00)
	{
		word16 bx_346;
		word16 dx_345;
		fn263F_043F(cx_159, dx_124, bx_174, ds_153, SEQ(ds_153, 33705), out dx_345, out bx_346, out ds_153);
	}
	Eq_756 es_bx_212 = ss->*((word16) bp_128 - 6);
	((word32) es_bx_212 + 2)->u0 = ss->*((word16) bp_128 + 6);
	*((word32) es_bx_212 + 8) = 0x00;
	*((word32) es_bx_212 + 0x0A) = 0x00;
	*((word32) es_bx_212 + 0x0C) = 0x00;
	*es_bx_212 = 0x00;
	ptr16 bp_226 = ss->*bp_128;
	dxOut.u0 = <invalid>;
	bpOut = bp_226;
	dsOut = ds_153;
	return ss->*((word16) bp_128 - 6);
}

// 209F:02A7: Register word16 fn209F_02A7(Register Eq_2 ds, Register out ptr16 dxOut, Register out ptr16 bxOut, Register out Eq_2 esOut)
// Called from:
//      fn0CE0_08FC
//      fn1D10_02AE
//      fn1D10_09C2
//      fn1D10_0E66
//      fn1F0F_000F
//      fn209F_08D2
word16 fn209F_02A7(Eq_2 ds, ptr16 & dxOut, ptr16 & bxOut, union Eq_2 & esOut)
{
	Eq_2 es_26 = 0x28BA;
	if (seg28BA->tA183 != 0x00)
	{
		Eq_21271 es_bx_10 = *((word32) ds + 0x0000A423);
		*((word32) es_bx_10 + 8) = 0x00;
		*((word32) es_bx_10 + 0x0A) = 0x00;
		*((word32) es_bx_10 + 0x0C) = 0x00;
		*es_bx_10 = 0x00;
		bx = (word16) es_bx_10;
		cx = fn0800_3556(*((word32) es_bx_10 + 4), 0x80, 0x2274, out dx, out es_26);
	}
	dxOut = dx;
	bxOut = bx;
	esOut = es_26;
	return cx;
}

// 209F:02E3: Register word16 fn209F_02E3(Register Eq_2 ds, Stack Eq_2 dwArg04, Register out Eq_2 cxOut, Register out Eq_2 dxOut, Register out Eq_2 bxOut, Register out Eq_21306 bpOut, Register out Eq_2 dsOut)
// Called from:
//      fn263F_00A6
word16 fn209F_02E3(Eq_2 ds, Eq_2 dwArg04, union Eq_2 & cxOut, union Eq_2 & dxOut, union Eq_2 & bxOut, union Eq_21306 & bpOut, union Eq_2 & dsOut)
{
	Eq_2 bx_19;
	Eq_2 cx_20;
	Eq_2 dx_21;
	if (fn0800_3615(ds, dwArg04, 0x8001, 0x00, out cx_20, out dx_21, out bx_19) == ~0x00)
	{
		word16 dx_492;
		word16 bx_493;
		word16 di_494;
		fn263F_03F3(cx_20, dx_21, bx_19, ds, out dx_492, out bx_493, out di_494, out ds);
	}
	word32 eax_423;
	cui16 dx_60;
	Eq_21322 bp_112;
	Eq_2 bx_290;
	Eq_2 cx_286;
	Eq_2 ds_123;
	Eq_2 ax_55 = fn0800_1D38(ds, 0x09, 0x00, out cx_286, out dx_60, out bx_290, out bp_112, out ds_123);
	ss->*((word16) bp_112 - 2) = dx_60;
	ss->*((word16) bp_112 - 4) = ax_55;
	if ((ax_55 | dx_60) != 0x00)
	{
		word16 dx_496;
		word16 bx_497;
		word16 cx_495;
		Eq_915 ax_80 = fn0800_06AB(ds_123, ss->*((word16) bp_112 - 6), 0x00, 0x02, out cx_495, out dx_496, out bx_497);
		*(ss->*((word16) bp_112 - 4)) = ax_80;
		ss->*((word16) bp_112 - 8) = 0x00;
		byte al_266 = (byte) ax_80;
		while (ss->*((word16) bp_112 - 8) < 0x28)
		{
			Eq_21394 bx_103 = bp_112 - 0xAC + (ss->*((word16) bp_112 - 8) << 0x02) / 2;
			ss->*((word16) bx_103 + 2) = 0x00;
			ss->*bx_103 = 0x00;
			++ss->*((word16) bp_112 - 8);
			al_266 = (byte) (bp_112 - 0xAC);
		}
		ss->*((word16) bp_112 - 8) = 0x00;
		while (ss->*((word16) bp_112 - 8) < 0x27)
		{
			int32 eax_119 = (int32) *(ss->*((word16) bp_112 - 4));
			cui16 dx_129;
			word16 cx_498;
			word16 bx_499;
			Eq_2 ax_124 = fn0800_1D38(ds_123, (word16) eax_119, SLICE(eax_119, word16, 16), out cx_498, out dx_129, out bx_499, out bp_112, out ds_123);
			Eq_2 es_bx_136 = ss->*((word16) bp_112 - 4);
			*((word32) es_bx_136 + 4) = dx_129;
			*((word32) es_bx_136 + 2) = ax_124;
			cui16 ax_141 = ax_124 | dx_129;
			eax_16_16 = SLICE(eax_119, word16, 16);
			al_266 = (byte) ax_141;
			if (ax_141 == 0x00)
				break;
			Eq_2 es_bx_145 = ss->*((word16) bp_112 - 4);
			Eq_14279 eax_151 = ((word32) *((word32) es_bx_145 + 4) << 0x04) + (word32) (*((word32) es_bx_145 + 2));
			ss->*((word16) bp_112 - 0x0C) = eax_151;
			*((word32) es_bx_145 + 8) = (byte) (eax_151 >> 0x10);
			*((word32) es_bx_145 + 6) = ss->*((word16) bp_112 - 0x0C);
			struct Eq_21507 * es_146 = SLICE(es_bx_145, selector, 16);
			eax_16_16 = SLICE(eax_151 >> 0x10, word16, 16);
			if (~0x00 - *((word32) es_bx_145 + 6) >= *es_bx_145)
			{
				word16 dx_503;
				word16 bx_504;
				word16 cx_502;
				fn0800_06AB(ds_123, ss->*((word16) bp_112 - 6), 0x00, 0x00, out cx_502, out dx_503, out bx_504);
				Eq_2 es_bx_179 = ss->*((word16) bp_112 - 4);
				word16 bx_507;
				word16 dx_506;
				word16 cx_505;
				al_266 = (byte) fn0800_3C87(ds_123, ss->*((word16) bp_112 - 6), *((word32) es_bx_179 + 2), *es_bx_179, out cx_505, out dx_506, out bx_507);
				break;
			}
			Eq_2 si_208 = ss->*((word16) bp_112 - 4);
			word16 ax_209 = es_146->*((word32) si_208 + 4);
			Eq_21625 bx_206 = bp_112 - 0xAC + (ss->*((word16) bp_112 - 8) << 0x02) / 2;
			word16 dx_210 = es_146->*((word32) si_208 + 2);
			ss->*((word16) bx_206 + 2) = ax_209;
			ss->*bx_206 = dx_210;
			++ss->*((word16) bp_112 - 8);
			al_266 = (byte) ax_209;
		}
		ss->*((word16) bp_112 - 8) = 0x00;
		while (ss->*((word16) bp_112 - 8) < 0x28)
		{
			Eq_21520 bx_227 = bp_112 - 0xAC + (ss->*((word16) bp_112 - 8) << 0x02) / 2;
			cui16 ax_229 = ss->*bx_227 | ss->*((word16) bx_227 + 2);
			al_266 = (byte) ax_229;
			if (ax_229 == 0x00)
				break;
			word16 bx_510;
			word16 cx_508;
			word16 dx_509;
			al_266 = SLICE(CONVERT(fn0800_1C24(ds_123, Mem221[ss:(Mem221[ss:bp_112 + -8:word16] << 0x02) + (bp_112 - 0xAC) + 0x02:word16], out cx_508, out dx_509, out bx_510, out ds_123), byte, uint16), byte, 0);
			++ss->*((word16) bp_112 - 8);
		}
		Eq_2 v20_261 = ss->*((word16) bp_112 - 6);
		Eq_2 dx_281;
		word16 bx_500;
		fn0800_2A93(al_266, ds_123, v20_261, out dx_281, out bx_500);
		Eq_2 es_bx_288 = ss->*((word16) bp_112 - 4);
		cx_286 = v20_261;
		bx_290 = (word16) es_bx_288;
		if (*((word32) es_bx_288 + 2) == 0x00)
		{
			if ((int16) *((word32) ds_123 + 33511) != 0x00)
				goto l209F_0324;
			eax_16_16 = SLICE((int32) *es_bx_288, word16, 16);
			word16 dx_501;
			cx_286 = fn263F_043F(v20_261, dx_281, bx_290, ds_123, SEQ(ds_123, 33729), out dx_501, out bx_290, out ds_123);
		}
		eax_423 = SEQ(eax_16_16, ss->*((word16) bp_112 - 4));
l209F_0497:
		Eq_21306 bp_342 = ss->*bp_112;
		cxOut = cx_286;
		dxOut.u0 = <invalid>;
		bxOut = bx_290;
		bpOut = bp_342;
		dsOut = ds_123;
		return (word16) eax_423;
	}
	else
	{
l209F_0324:
		eax_423 = SEQ(eax_16_16, 0x00);
		goto l209F_0497;
	}
}

// 209F:049A: Register byte fn209F_049A(Register Eq_2 ds, Register out ptr16 cxOut, Register out ptr16 bxOut)
// Called from:
//      fn1D10_02AE
//      fn1D10_09C2
//      fn1D10_0E66
//      fn209F_08D2
byte fn209F_049A(Eq_2 ds, ptr16 & cxOut, ptr16 & bxOut)
{
	Eq_2 ax_32 = 0x28BA;
	if (seg28BA->tA183 != 0x00)
	{
		Eq_21271 es_bx_13 = *((word32) ds + 0x0000A423);
		ax_32 = (uint16) fn2057_0283(ds, *((word32) es_bx_13 + 0x0E), *((word32) es_bx_13 + 0x0F), (byte) (*((word32) es_bx_13 + 0x0F) >> 0x08), 0x2274, out cx, out bx);
	}
	cxOut = cx;
	bxOut = bx;
	return (byte) ax_32;
}

// 209F:04CB: Register Eq_2 fn209F_04CB(Register Eq_2 ds, Stack Eq_2 ptrArg04)
// Called from:
//      fn263F_00A6
Eq_2 fn209F_04CB(Eq_2 ds, Eq_2 ptrArg04)
{
	if ((int16) seg28BA->tA183 != 0x00)
	{
		Eq_2 edx_25 = <invalid>;
		cui16 dx_35 = (word16) edx_25;
		struct Eq_21724 Eq_21751::* bp_20;
		word16 dx_119;
		Eq_21271 ax_37 = (word16) (uint32) fn209F_0149(ds, out dx_119, out bp_20, out ds);
		*((word32) ds + 42021) = dx_35;
		*((word32) ds + 0x0000A423) = ax_37;
		if ((ax_37 | dx_35) == 0x00)
			return ds;
		word32 * es_bx_47 = (ss->*bp_20).ptr0006;
		*es_bx_47 -= (int32) *((word32) *((word32) ds + 0x0000A423) + 2);
		return ds;
	}
	else
	{
		*ptrArg04 -= 0x2274;
		return ds;
	}
}

// 209F:0516: Register word32 fn209F_0516(Register Eq_2 ds, Stack Eq_2 wArg04, Stack Eq_915 wArg06, Register out ptr16 cxOut, Register out (ptr16 Eq_14819) dxOut, Register out ptr16 bxOut)
// Called from:
//      fn1D10_02AE
//      fn1D10_09C2
//      fn1D10_1368
//      fn1D10_155B
//      fn209F_08D2
word32 fn209F_0516(Eq_2 ds, Eq_2 wArg04, Eq_915 wArg06, ptr16 & cxOut, struct Eq_14819 & dxOut, ptr16 & bxOut)
{
	word32 eax_266;
	ptr16 bx_167;
	if (seg28BA->tA183 == 0x00)
	{
		Eq_2 eax_180 = (int32) wArg06;
		fn0800_06AB(ds, wArg04, eax_180, 0x01, out cx, out dx, out bx_167);
		eax_266 = SEQ(SLICE(eax_180, word16, 16), 0x00);
	}
	else
	{
		Eq_21271 es_bx_15 = *((word32) ds + 0x0000A423);
		bx_167 = (word16) es_bx_15;
		if (*((word32) es_bx_15 + 2) - *((word32) es_bx_15 + 0x0C) >= wArg06)
		{
			Eq_915 ax_25 = **((word32) ds + 0x0000A423);
			if (ax_25 != 0x00)
			{
				if (ax_25 >= wArg06)
					ax_25 = wArg06;
				Eq_21271 es_bx_44 = *((word32) ds + 0x0000A423);
				word16 dx_300;
				fn0800_350E(SEQ(Mem51[es_bx_44 + 0x06:word16], Mem43[es_bx_44 + 0x04:word16] + Mem51[es_bx_44 + 0x08:word16]), Mem39[ds:42025:word32], ax_25, out dx_300);
				Eq_21271 es_bx_73 = *((word32) ds + 0x0000A423);
				Mem78[es_bx_73 + 0x08:word16] = Mem62[es_bx_73 + 0x08:word16] + ax_25;
				Mem80[es_bx_73 + 0x0C:word16] = Mem78[es_bx_73 + 0x0C:word16] + ax_25;
				*es_bx_73 -= ax_25;
				Mem86[ds:42025:word16] = Mem84[ds:42025:word16] + ax_25;
				Eq_2 eax_90 = (int32) ax_25;
				word16 bx_301;
				fn0800_06AB(ds, wArg04, eax_90, 0x01, out cx, out dx, out bx_301);
				wArg06 -= ax_25;
				eax_16_16 = SLICE(eax_90, word16, 16);
			}
			if (wArg06 != 0x00)
			{
				Eq_21271 es_bx_116 = *((word32) ds + 0x0000A423);
				word16 bx_302;
				word16 ax_138 = fn0800_3C87(ds, wArg04, SEQ(Mem123[es_bx_116 + 0x06:word16], Mem114[es_bx_116 + 0x04:word16] + Mem123[es_bx_116 + 0x08:word16]), wArg06, out cx, out dx, out bx_302);
				Eq_21271 es_bx_150 = *((word32) ds + 0x0000A423);
				Mem155[es_bx_150 + 0x08:word16] = Mem149[es_bx_150 + 0x08:word16] + ax_138;
				Mem158[es_bx_150 + 0x0C:word16] = Mem155[es_bx_150 + 0x0C:word16] + ax_138;
				wArg06 -= ax_138;
			}
			Eq_21271 es_bx_165 = *((word32) ds + 0x0000A423);
			bx_167 = (word16) es_bx_165;
			if (*((word32) es_bx_165 + 8) >= *((word32) es_bx_165 + 2))
				*((word32) es_bx_165 + 8) = 0x00;
		}
		eax_266 = SEQ(eax_16_16, wArg06);
	}
	cxOut = cx;
	dxOut = dx;
	bxOut = bx_167;
	return eax_266;
}

// 209F:06D8: Register Eq_2 fn209F_06D8(Register Eq_2 ds, Stack (ptr32 Eq_14737) ptrArg04, Register out ptr16 cxOut, Register out Eq_2 dxOut, Register out ptr16 bxOut)
// Called from:
//      fn1D10_02AE
//      fn1D10_0E66
Eq_2 fn209F_06D8(Eq_2 ds, struct Eq_14737 * ptrArg04, ptr16 & cxOut, union Eq_2 & dxOut, ptr16 & bxOut)
{
	Eq_2 eax_171 = SEQ(eax_16_16, 0x28BA);
	if (seg28BA->tA183 != 0x00)
	{
		Eq_915 ax_18 = *((word32) *((word32) ds + 0x0000A423) + 8);
		word16 ax_20 = fn2057_041E(ds, out dx);
		Eq_21271 es_bx_27 = *((word32) ds + 0x0000A423);
		Eq_915 ax_30 = ax_20 - *((word32) es_bx_27 + 0x0F);
		Eq_915 wLoc0A_335 = ax_30;
		if (ax_30 < 0x00 || *((word32) es_bx_27 + 2) <= ax_30)
			wLoc0A_335.u0 = 0x00;
		if (*((word32) *((word32) ds + 0x0000A423) + 0x0C) <= 441)
		{
			**((word32) ds + 0x0000A423) = ptrArg04->t0000;
			bx = (word16) ptrArg04;
			eax_171 = ptrArg04->t0002;
		}
		else
		{
			Eq_915 wLoc0C_338 = wLoc0A_335;
			if (wLoc0A_335 >= 0x2274)
				wLoc0C_338.u0 = 0x00;
			if (ax_18 >= wLoc0C_338)
			{
				Eq_915 ax_227 = ax_18 - wLoc0C_338;
				Eq_915 ax_232 = ptrArg04->t0000;
				if (ax_232 <= ax_227)
				{
					Eq_21271 es_bx_288 = *((word32) ds + 0x0000A423);
					bx = (word16) es_bx_288;
					cx = fn0800_350E(SEQ(Mem287[es_bx_288 + 0x06:word16], Mem287[es_bx_288 + 0x04:word16] + wLoc0C_338), Mem284[ptrArg04 + 0x02:word32], ax_232, out dx);
					eax_171 = SEQ(eax_16_16, ax_299);
				}
				else
				{
					Eq_21271 es_bx_244 = *((word32) ds + 0x0000A423);
					word16 dx_470;
					cx = fn0800_350E(SEQ(Mem243[es_bx_244 + 0x06:word16], Mem243[es_bx_244 + 0x04:word16] + wLoc0C_338), Mem237[ptrArg04 + 0x02:word32], ax_227, out dx_470);
					**((word32) ds + 0x0000A423) = ptrArg04->t0000 - ax_227;
					word16 ax_277 = ptrArg04->w0004;
					dx = Mem273[ptrArg04 + 0x02:word16] + ax_227;
					*((word32) ds + 42027) = ax_277;
					*((word32) ds + 42025) = dx;
					bx = (word16) ptrArg04;
					eax_171 = SEQ(eax_16_16, ax_277);
				}
				goto l209F_08D0;
			}
			Eq_915 ax_62 = 0x2274 - wLoc0C_338;
			Eq_915 ax_67 = ptrArg04->t0000;
			if (ax_67 <= ax_62)
			{
				Eq_21271 es_bx_205 = *((word32) ds + 0x0000A423);
				bx = (word16) es_bx_205;
				cx = fn0800_350E(SEQ(Mem204[es_bx_205 + 0x06:word16], Mem204[es_bx_205 + 0x04:word16] + wLoc0C_338), Mem201[ptrArg04 + 0x02:word32], ax_67, out dx);
				eax_171 = SEQ(eax_16_16, ax_216);
				goto l209F_08D0;
			}
			Eq_2 eax_73 = ptrArg04->t0002;
			Eq_21271 es_bx_85 = *((word32) ds + 0x0000A423);
			word16 dx_471;
			fn0800_350E(SEQ(Mem83[es_bx_85 + 0x06:word16], Mem83[es_bx_85 + 0x04:word16] + wLoc0C_338), eax_73, ax_62, out dx_471);
			**((word32) ds + 0x0000A423) = ptrArg04->t0000 - ax_62;
			word16 dx_120 = Mem114[ptrArg04 + 0x02:word16] + ax_62;
			*((word32) ds + 42027) = ptrArg04->w0004;
			*((word32) ds + 42025) = dx_120;
			Eq_21271 es_bx_129 = *((word32) ds + 0x0000A423);
			word16 wLoc04_360 = SLICE(eax_73, word16, 16);
			word16 v23_124 = (word16) ax_62.u1 + (word16) eax_73;
			word16 eax_16_16_431 = SLICE(eax_73, word16, 16);
			Eq_915 ax_132 = *es_bx_129;
			Eq_2 dwLoc06_361 = SEQ(wLoc04_360, v23_124);
			if (ax_132 <= ax_18)
			{
				cx = fn0800_350E(SEQ(*((word32) es_bx_129 + 6), *((word32) es_bx_129 + 4)), dwLoc06_361, ax_132, out dx);
				Eq_21271 es_bx_196 = *((word32) ds + 0x0000A423);
				*es_bx_196 = 0x00;
				bx = (word16) es_bx_196;
				eax_171 = SEQ(eax_16_16_431, ax_185);
				goto l209F_08D0;
			}
			Eq_21271 es_bx_141 = *((word32) ds + 0x0000A423);
			cx = fn0800_350E(SEQ(*((word32) es_bx_141 + 6), *((word32) es_bx_141 + 4)), dwLoc06_361, ax_18, out dx);
			Eq_21271 es_bx_165 = *((word32) ds + 0x0000A423);
			*es_bx_165 -= ax_18;
			bx = (word16) es_bx_165;
			eax_171 = SEQ(wLoc04_360, (word32) ax_18 + v23_124);
		}
		*((word32) ds + 42025) = eax_171;
		goto l209F_08D0;
	}
	else
	{
l209F_08D0:
		cxOut = cx;
		dxOut = dx;
		bxOut = bx;
		return eax_171;
	}
}

// 209F:08D2: void fn209F_08D2(Register Eq_2 ds, Stack Eq_2 dwArg04, Stack Eq_2 bArg08)
// Called from:
//      fn0CE0_014B
//      fn1F0F_0BF7
//      fn226D_0656
void fn209F_08D2(Eq_2 ds, Eq_2 dwArg04, Eq_2 bArg08)
{
	if ((int16) seg28BA->tA183 != 0x00)
	{
		Eq_2 bx_24;
		Eq_2 cx_25;
		Eq_2 dx_26;
		Eq_2 ax_27 = fn0800_3615(ds, dwArg04, 0x8001, 0x00, out cx_25, out dx_26, out bx_24);
		if (ax_27 == ~0x00)
		{
			word16 bx_436;
			word16 di_437;
			word16 dx_435;
			fn263F_03F3(cx_25, dx_26, bx_24, ds, out dx_435, out bx_436, out di_437, out ds);
		}
		else
		{
			Eq_915 ax_96;
			word16 dx_427;
			word16 bx_428;
			word16 cx_426;
			fn0800_06AB(ds, ax_27, 0x00, 0x02, out cx_426, out dx_427, out bx_428);
			word16 bx_431;
			word16 cx_429;
			word16 dx_430;
			fn0800_06AB(ds, ax_27, 0x00, 0x00, out cx_429, out dx_430, out bx_431);
			word16 dx_432;
			word16 bx_433;
			struct Eq_22229 * es_434;
			fn209F_02A7(ds, out dx_432, out bx_433, out es_434);
			Eq_2 dx_ax_425 = <invalid>;
			Eq_915 ax_42 = (word16) dx_ax_425;
			if (*((word32) *((word32) ds + 0x0000A423) + 2) > ax_42)
				ax_96 = ax_42;
			else
				ax_96 = *((word32) *((word32) ds + 0x0000A423) + 2);
			word16 bx_442;
			word16 dx_441;
			word16 cx_440;
			Eq_915 ax_120 = (word16) fn209F_0516(ds, ax_27, ax_96, out cx_440, out dx_441, out bx_442);
			ci16 wLoc10_319 = ax_42 - (ax_96 - ax_120);
			Eq_915 wLoc0C_320 = ax_120;
			word16 bx_444;
			word16 cx_443;
			byte al_197 = (byte) (uint16) fn209F_049A(ds, out cx_443, out bx_444);
			while (wLoc10_319 != 0x00)
			{
				if (wLoc0C_320 != 0x00)
				{
					word16 cx_450;
					word16 dx_451;
					word16 bx_452;
					Eq_915 ax_185 = (word16) fn209F_0516(ds, ax_27, wLoc0C_320, out cx_450, out dx_451, out bx_452);
					wLoc10_319 -= wLoc0C_320 - ax_185;
					al_197 = (byte) ax_185;
					wLoc0C_320 = ax_185;
				}
				else
				{
					word16 cx_447;
					word16 dx_448;
					word16 bx_449;
					Eq_915 ax_162 = (word16) fn209F_0516(ds, ax_27, 441, out cx_447, out dx_448, out bx_449);
					ci16 ax_165 = 441 - ax_162;
					wLoc0C_320 = ax_162;
					al_197 = (byte) ax_165;
					wLoc10_319 -= ax_165;
				}
			}
			word16 dx_445;
			word16 bx_446;
			fn0800_2A93(al_197, ds, ax_27, out dx_445, out bx_446);
		}
		Eq_722 dwLoc18_337;
		Eq_21271 es_bx_232 = *((word32) ds + 0x0000A423);
		Eq_915 ax_235 = *((word32) es_bx_232 + 8);
		if (0x2274 - ax_235 >= 441)
			dwLoc18_337 = SEQ(Mem253[es_bx_232 + 0x06:word16], Mem253[es_bx_232 + 0x04:word16] + ax_235);
		else
			dwLoc18_337 = *((word32) *((word32) ds + 0x0000A423) + 4);
		struct Eq_22269 * es_439;
		word16 dx_438;
		fn0800_3556(dwLoc18_337, 0x80, 441, out dx_438, out es_439);
		if (bArg08 != 0x00)
		{
			do
				;
			while (*((word32) ds + 0x0000A422) == 0x01);
		}
	}
}

