// ZORTON.globals.c
// Generated by decompiling ZORTON.EXE
// using Reko decompiler version 0.9.2.3.

#include "ZORTON.h"

struct Eq_12853 * g_ptrFFFA0000;
Eq_40 g_tFFFFB8CB;
Eq_46 g_tFFFFFFFF;
struct Eq_32795 * g_ptr0000;
Eq_47 g_t000B;
Eq_28 g_t0300;
Eq_2 g_t0400;
Eq_25 g_t06C4;
Eq_46 g_t2863;
Eq_33 g_t5E07;
Eq_27 g_t7DB0;
Eq_2 g_t8000 = 
	{
		~0x45
	};
struct Eq_25 * g_ptr1D100 = &g_t06C4;
struct Eq_27 * g_ptr1ED70 = &g_t7DB0;
struct Eq_28 * g_ptr1F0F0 = &g_t0300;
struct Eq_33 * g_ptr21CC0 = &g_t5E07;
struct Eq_40 * g_ptr25040 = &g_tFFFFB8CB;
Eq_2 g_t28620 = 
	{
		0x00
	};
struct Eq_46 * g_ptr28630 = &g_tFFFFFFFF;
struct Eq_47 * g_ptr28640 = &g_t000B;
Eq_2 g_t28BA0 = 
	{
		0x00
	};

