// ZORTON_2863.c
// Generated by decompiling ZORTON.EXE
// using Reko decompiler version 0.9.3.0.

#include "ZORTON.h"

struct seg2863_t * g_ptr28630 = &g_tFFFFFFFF; // 00028630
Eq_2 g_t0002 = // 2863:0002
	{
		~0x00
	};
byte g_b0004 = 0x00; // 2863:0004
