// ZORTON_1ED7.c
// Generated by decompiling ZORTON.EXE
// using Reko decompiler version 0.9.2.3.

#include "ZORTON_1ED7.h"

// 1ED7:000E: Register word16 fn1ED7_000E(Register Eq_2 ds, Register out ptr16 cxOut, Register out Eq_17885 bpOut, Register out Eq_2 dsOut)
// Called from:
//      fn268D_0282
word16 fn1ED7_000E(Eq_2 ds, ptr16 & cxOut, union Eq_17885 & bpOut, union Eq_2 & dsOut)
{
	__cli();
	word16 cx_529;
	word32 edx_530;
	word32 ebx_531;
	struct Eq_17892 * es_532;
	fn2425_01E8(ds, out cx_529, out edx_530, out ebx_531, out es_532);
	__sti();
	seg28BA->t302C = 0x00;
	seg2862->t0000 = 0x01;
	__cli();
	seg28BA->tA51E = 0x00;
	seg28BA->tA51C = 0x00;
	__sti();
	struct Eq_17917 * es_bx_46 = seg28BA->tA8AE;
	fn2476_043B((byte) (uint16) (seg28BA->tA8B0->*(word16) es_bx_46), (uint16) es_bx_46->b0001, SEQ(seg28BA->tA8B0, seg28BA->tA8AE + 0x02));
	seg28BA->tA182 = 0x19;
	fn226D_0656(ds, 0x00);
	seg28BA->tA17E = 0x00;
	Eq_2 ds_93 = fn226D_057F(ds);
	seg28BA->t2E1C = 0x28BA;
	seg28BA->t2E1A = 0x2D72;
	uint16 wLoc08_509;
	for (wLoc08_509 = 0x00; wLoc08_509 < 0x08; ++wLoc08_509)
		SEQ(0x28BA, 0x2D72)[wLoc08_509 * 0x15] = 0x00;
	seg28BA->t83D4 = 0x00;
	seg28BA->tA35C = 0x00;
	seg28BA->tA18C = 0x00;
	seg28BA->tA27E = 0x00;
	cui16 ax_140 = seg28BA->tA188;
	Mem151[28BA:3059:word16] = CONVERT(SEQ(ds_93, 0x7F5D)[(ax_140 & 0x03) * 0x08], byte, uint16);
	Mem158[28BA:3061:word16] = CONVERT(SEQ(ds_93, 32606)[(ax_140 & 0x03) * 0x08], byte, uint16);
	Mem165[28BA:3069:word16] = CONVERT(SEQ(ds_93, 0x7F5F)[(ax_140 & 0x03) * 0x08], byte, uint16);
	Mem172[28BA:3071:word16] = CONVERT(SEQ(ds_93, 0x7F60)[(ax_140 & 0x03) * 0x08], byte, uint16);
	Mem179[28BA:3079:word16] = CONVERT(SEQ(ds_93, 0x7F61)[(ax_140 & 0x03) * 0x08], byte, uint16);
	Mem186[28BA:3081:word16] = CONVERT(SEQ(ds_93, 0x7F62)[(ax_140 & 0x03) * 0x08], byte, uint16);
	Mem193[28BA:3089:word16] = CONVERT(SEQ(ds_93, 32611)[(ax_140 & 0x03) * 0x08], byte, uint16);
	Mem201[28BA:3091:word16] = CONVERT(SEQ(ds_93, 32612)[(ax_140 & 0x03) * 0x08], byte, uint16);
	seg28BA->tA520 = 0x03;
	seg28BA->t3034 = 0x06;
	seg28BA->t3035 = 0x06;
	seg28BA->t8586 = 0x02;
	seg28BA->t3051 = 0x28BA;
	seg28BA->t304F = 0x3034;
	Eq_2 ds_220;
	word16 cx_533;
	word32 edx_534;
	word32 ebx_535;
	word16 bp_536;
	fn226D_00F9(ds_93, out cx_533, out edx_534, out ebx_535, out bp_536, out ds_220);
	Eq_2 sp_226 = <invalid>;
	Eq_2 ds_235 = fn23F8_0004(ds_220);
	ss->*((word32) sp_226 - 2) = 0x28BA;
	(ss->*((word32) sp_226 - 4)).u0 = 34732;
	fn23F8_0055(ds_235, ss->*((word32) sp_226 - 4));
	ss->*((word32) sp_226 - 2) = 0x28BA;
	(ss->*((word32) sp_226 - 4)).u0 = ~0x7811;
	fn23F8_0055(ds_235, ss->*((word32) sp_226 - 4));
	ss->*((word32) sp_226 - 2) = 0x28BA;
	(ss->*((word32) sp_226 - 4)).u0 = 0x8830;
	fn23F8_0055(ds_235, ss->*((word32) sp_226 - 4));
	Eq_2 ds_288;
	word16 ebx_16_16_489 = SLICE(fn23F8_00A0(ds_235, out ds_288), word16, 16);
	seg28BA->tA520 = seg28BA->tA520 | 0x010C;
	(ss->*((word32) sp_226 - 4)).u0 = 0x00;
	(ss->*((word32) sp_226 - 6)).u0 = 0x01;
	(ss->*((word32) sp_226 - 0x0A)).u0 = 0x00;
	(ss->*((word32) sp_226 - 0x0C)).u0 = 0x01;
	(ss->*((word32) sp_226 - 0x0E)).u1 = 0x00;
	(ss->*((word32) sp_226 - 16)).u0 = 0x00;
	(ss->*((word32) sp_226 - 18)).u0 = 0x01;
	(ss->*((word32) sp_226 - 20)).u0 = 0x01;
	Eq_2 sp_328 = <invalid>;
	word16 sp_333 = (word32) sp_328 + 20;
	struct Eq_18192 * es_537;
	struct Eq_18193 Eq_18099::* bp_326;
	Eq_11798 ebx_346 = SEQ(ebx_16_16_489, fn2353_0004(ds_288, ss->*((word32) sp_226 - 20), ss->*((word32) sp_226 - 18), ss->*((word32) sp_226 - 16), ss->*((word32) sp_226 - 0x0E), ss->*((word32) sp_226 - 0x0C), ss->*((word32) sp_226 - 0x0A), ss->*((word32) sp_226 - 6), out bp_326, out es_537));
	while (true)
	{
l1ED7_0250:
		Eq_11798 ebx_425;
		(ss->*bp_326).tFFFFFFF8.u0 = 0x28BA;
		(ss->*bp_326).tFFFFFFF6.u0 = 32539;
		while (true)
		{
			union Eq_2 Eq_18099::* sp_344 = sp_333 - 4;
			ss->*sp_344 = (ss->*bp_326).tFFFFFFF6;
			Eq_2 edx_353 = <invalid>;
			Eq_17885 bp_356;
			word16 dx_542;
			word32 ebx_543;
			struct Eq_18408 * es_544;
			word16 ax_366 = (word16) (uint32) fn1D10_02AE(ebx_346, ds_288, ss->*sp_344, out dx_542, out ebx_543, out bp_356, out es_544, out ds_288);
			ss->*((word16) bp_356 - 8) = (word16) edx_353;
			ss->*((word16) bp_356 - 0x0A) = ax_366;
			Eq_2 sp_357 = <invalid>;
			while (true)
			{
				Eq_2 edx_372 = <invalid>;
				cui16 dx_380 = (word16) edx_372;
				word16 dx_538;
				word32 ebx_539;
				Eq_18226 ax_383 = (word16) (uint32) fn2331_0167(ds_288, out dx_538, out ebx_539);
				ss->*((word16) bp_356 - 2) = dx_380;
				ss->*((word16) bp_356 - 4) = ax_383;
				if ((ax_383 | dx_380) == 0x00)
					break;
				if (ss->*((word16) bp_356 - 4) != 0x00)
				{
					ss->*((word16) bp_356 - 0x0C) = (uint16) *(ss->*((word16) bp_356 - 4));
					word16 cx_463;
					struct Eq_18363 Eq_27::* bx_464 = Eq_27::a037F;
					for (cx_463 = 0x04; cx_463 != 0x00; --cx_463)
					{
						if ((seg1ED7->*bx_464).w0000 == ss->*((word16) bp_356 - 0x0C))
						{
							word32 eax_476;
							ptr16 cx_479;
							bx_464[4]();
							cxOut = cx_479;
							bpOut = bp_356;
							dsOut = ds_288;
							return (word16) eax_476;
						}
						++bx_464;
					}
				}
			}
			seg2862->t0000 = 0x01;
			ss->*sp_357 = 0x00;
			(ss->*((word16) sp_357 - 2)).u0 = 0x01;
			(ss->*((word16) sp_357 - 6)).u0 = 0x00;
			(ss->*((word16) sp_357 - 8)).u0 = 0x01;
			(ss->*((word16) sp_357 - 0x0A)).u1 = 0x00;
			(ss->*((word16) sp_357 - 0x0C)).u0 = 0x00;
			(ss->*((word16) sp_357 - 0x0E)).u0 = 0x01;
			(ss->*((word16) sp_357 - 16)).u0 = 0x01;
			struct Eq_18279 * es_540;
			fn2353_0004(ds_288, ss->*((word16) sp_357 - 16), ss->*((word16) sp_357 - 0x0E), ss->*((word16) sp_357 - 0x0C), ss->*((word16) sp_357 - 0x0A), ss->*((word16) sp_357 - 8), ss->*((word16) sp_357 - 6), ss->*((word16) sp_357 - 2), out bp_326, out es_540);
			Eq_2 sp_415 = <invalid>;
			sp_333 = (word16) ((word32) sp_415 + 20);
			do
			{
				Eq_2 edx_426 = <invalid>;
				word16 ebx_16_16_491 = SLICE(ebx_425, word16, 16);
				word16 dx_541;
			} while (((word16) (uint32) fn2331_0167(ds_288, out dx_541, out ebx_425) | (word16) edx_426) != 0x00);
			if ((ss->*bp_326).tFFFFFFF6 == 0x00)
				break;
			Eq_2 es_bx_444 = (ss->*bp_326).tFFFFFFF6;
			ebx_346 = SEQ(ebx_16_16_491, (word16) es_bx_444);
			if (*((word32) es_bx_444 + 16) <= 0x00)
				goto l1ED7_0250;
			union Eq_2 * es_bx_449 = *((word32) es_bx_444 + 0x0011);
			(ss->*bp_326).tFFFFFFF6 = *es_bx_449;
			ebx_346 = SEQ(ebx_16_16_491, (word16) es_bx_449);
		}
		ebx_346 = ebx_425;
	}
}

